### ISSUE TITLE
Spezifikation (Grundstruktur und Eingabelogiken) und Stammdaten sind auf NextCloud

### ISSUE THREAD

**Issue by simonkriegnerschramml** [w3geo/bml-fast#1]
Hallo zusammen,

Die Spezifikation mit der Beschreibung der Grundstruktur, der Daten aus dem Inspire Agraratlas und der Maßnahmenbeschreibung, sowie die Einzelnen Stammdatenbereiche für Kulturen, Düngehöhen und Düngemittel sind hochgeladen und befinden sich im Ordner Spezifikation der Next Cloud.

Die Spezifikation wird noch um die Informationen in der Hauptliste (Zusammenfassung der in den Masken eingetragenen Informationen) und die auf dieser Liste basierenden Berechnungslogiken erweitert.

LG
Simon

**Comment by simonkriegnerschramml** [comment]
Bei Rückfragen bitte gerne hier Fragen stellen oder unter der 05069021563 anrufen.

**Comment by simonkriegnerschramml** [comment]
Ich habe nun die Systematik der Basiskategorie nochmals erweitert. Ich hatte die Vorfrüchte vergessen und die Gehaltsklassen für Phosphor und Kalium.

Ich gebe das neue File, nach abgeschlossener Bearbeitung, in die Next Cloud.

LG
Simon

**Comment by arnold-pichler** [comment]
Schließe das mal hier
