### ISSUE TITLE
N-Saldo aus dem Vorjahr wird erst nach Erfassung einer Vorfrucht berücksichtigt

### ISSUE THREAD

**Issue by simonkriegnerschramml** [w3geo/bml-fast#100]
Hallo Arnold,

Ich habe eine Fläche im GW Layer (Grundwasserschutz - Acker) und einen N-Saldo (BAS16) von 20 kg. Keine ZWF wurde angebaut. Hier muss der Wert von 20 kg der Düngeobergrenze HF 1 in Abzug gebracht werden. Gleichzeitig muss der Wert Teil des anrechenbaren Stickstoffs sein.

Der Wert wird komischerweise erst nach Erfassung einer Vorfrucht korrekt mit in die Berechnung aufgenommen. die Vorfrucht ist kein Pflichtfeld. Wenn da nichts drinsteht, dann haben wir einfach keine Info darüber und der VFW ist dann einfach 0.

Das kann man anhand des Feldstücks "Testfeld A5" erkennen.

[fast-export-2024-10-25.txt](https://github.com/user-attachments/files/17517780/fast-export-2024-10-25.txt)

LG
Simon

**Comment by simonkriegnerschramml** [comment]
Das ist der Debugging Text:

SCHLAG-DATEN:
{
  "fnar_code": "A",
  "inspire_id": "https://data.inspire.gv.at/0095/bbd8ee1b-76a1-451f-88ef-84e9c7a1faaf/elu.ExistingLandUseObject/114901036/MFA-2024",
  "sl_flaeche_brutto_ha": 8.02910667,
  "snar_bezeichnung": "KÖRNERMAIS",
  "layer": "invekos_schlaege_polygon",
  "loading": false,
  "id": 1395009,
  "extent": [
    14.246310107409967,
    48.111657792504985,
    14.250819236040117,
    48.11464083140021
  ],
  "parts": [
    {
      "type": "Polygon",
      "coordinates": [
        [
          [
            14.249482154846204,
            48.114476753092134
          ],
          [
            14.249482154846204,
            48.112080209933225
          ],
          [
            14.248840101063264,
            48.11200275580521
          ],
          [
            14.248123280704032,
            48.11191075089448
          ],
          [
            14.247504360973847,
            48.11182255138502
          ],
          [
            14.247074872255336,
            48.11175987143858
          ],
          [
            14.246520660817634,
            48.111657792504985
          ],
          [
            14.246405325829993,
            48.1116757011045
          ],
          [
            14.246332570910468,
            48.11173659029615
          ],
          [
            14.246310107409967,
            48.11188836524653
          ],
          [
            14.24631513655187,
            48.11197634078687
          ],
          [
            14.246344305574908,
            48.1120070090696
          ],
          [
            14.246323518455041,
            48.1120273799626
          ],
          [
            14.246321506798278,
            48.112080881500304
          ],
          [
            14.246341288089766,
            48.11219527163044
          ],
          [
            14.246372468769561,
            48.11237323619946
          ],
          [
            14.24641437828542,
            48.11268260207129
          ],
          [
            14.24642946571113,
            48.11278020191645
          ],
          [
            14.246438518166554,
            48.112840865946964
          ],
          [
            14.24644991755487,
            48.11291361791865
          ],
          [
            14.246471710503114,
            48.11304457120809
          ],
          [
            14.246471039950858,
            48.11304457120809
          ],
          [
            14.246512949466718,
            48.11330356673116
          ],
          [
            14.24656726419927,
            48.113625462545315
          ],
          [
            14.246615208685412,
            48.113895199835326
          ],
          [
            14.249482154846204,
            48.114476753092134
          ]
        ]
      ]
    },
    {
      "type": "Polygon",
      "coordinates": [
        [
          [
            14.250291176140312,
            48.11464083140021
          ],
          [
            14.250301234424118,
            48.114586437148745
          ],
          [
            14.250305928289894,
            48.11456964878792
          ],
          [
            14.250307939946653,
            48.11456382882156
          ],
          [
            14.250417910516266,
            48.114277754277396
          ],
          [
            14.250428304076197,
            48.114249997351095
          ],
          [
            14.250429980456834,
            48.11424619196487
          ],
          [
            14.25061605870724,
            48.11381416687294
          ],
          [
            14.250623434782034,
            48.11380185522384
          ],
          [
            14.250697195529941,
            48.113625462545315
          ],
          [
            14.25071764737368,
            48.11356547098873
          ],
          [
            14.25071865320206,
            48.11356211325031
          ],
          [
            14.250726699829107,
            48.11353793752701
          ],
          [
            14.250754192471506,
            48.11345779939995
          ],
          [
            14.250754863023763,
            48.11345556090302
          ],
          [
            14.250771962106231,
            48.11340519469556
          ],
          [
            14.250773973762993,
            48.11339377834835
          ],
          [
            14.25077430903912,
            48.11339221139855
          ],
          [
            14.250774644315248,
            48.113389972898716
          ],
          [
            14.250808171927934,
            48.11321425035854
          ],
          [
            14.250809848308569,
            48.113165674722296
          ],
          [
            14.250819236040117,
            48.112885412551094
          ],
          [
            14.25081387162209,
            48.11286571355501
          ],
          [
            14.250813536345964,
            48.112863922736835
          ],
          [
            14.250793419778349,
            48.112788708316174
          ],
          [
            14.250772967934614,
            48.11275826435272
          ],
          [
            14.250622764229776,
            48.11253597810227
          ],
          [
            14.25055537372828,
            48.11244934664455
          ],
          [
            14.250455796718603,
            48.11232130194864
          ],
          [
            14.250432327389722,
            48.11229712564159
          ],
          [
            14.250354208052164,
            48.112210717636344
          ],
          [
            14.249675273895269,
            48.11210349091999
          ],
          [
            14.249053001403812,
            48.1120284992422
          ],
          [
            14.249053001403812,
            48.11438967721517
          ],
          [
            14.250291176140312,
            48.11464083140021
          ]
        ]
      ]
    }
  ]
}
{
  "nitrataktionsprogramm": 0,
  "bdfl_l16_grundwasserschutz_acker": 0,
  "bdfl_l26_wasserrahmenrichtlinie_ertragslagen-el_hoch_3": 0,
  "bdfl_l26_wasserrahmenrichtlinie_ertragslagen-el_hoch_2": 0,
  "bdfl_l26_wasserrahmenrichtlinie_ertragslagen-el_hoch_1": 0,
  "bdfl_l26_wasserrahmenrichtlinie_ertragslagen-el_mittel": 0,
  "bdfl_l26_wasserrahmenrichtlinie_ertragslagen-el_mittel_10": 0,
  "bdfl_l26_wasserrahmenrichtlinie_ertragslagen-el_niedrig": 0,
  "schwere_boeden": 0
}

**Comment by arnold-pichler** [comment]
Auch hier: Denn Fall bitte exportieren und den Export hier reinstellen

**Comment by simonkriegnerschramml** [comment]
Habe das File im Kommentar ergänzt.

**Comment by arnold-pichler** [comment]
Das sollte in der neuen Test-Version passen. Bitte testen, und wenn es passt, dieses Issue schließen!

**Comment by simonkriegnerschramml** [comment]
Das passt jetzt so. Der N-Saldo wird laufend berücksichtigt. Ich schließe das Issue.

LG
Simon
