### ISSUE TITLE
Ackerzahl <=30 zeigt keine Auswirkung

### ISSUE THREAD

**Issue by simonkriegnerschramml** [w3geo/bml-fast#101]
Hallo Arnold,

Ich habe die Ackerzahl auf die Option <=30 gesetzt und kann dennoch alle Ertragslagen auswählen. Hier muss eine Einschränkung auf die Ertragslagen niedrig und mittel erfolgen.

erkennbar am Feldstück Auweidenholz 1.

[fast-export-2024-10-25 (2).txt](https://github.com/user-attachments/files/17518111/fast-export-2024-10-25.2.txt)

LG
Simon

**Comment by simonkriegnerschramml** [comment]
Eigentlich lautet der Verordnungstext nicht auf kleiner/gleich 30 sondern auf kleiner 30.

LG
Simon

**Comment by arnold-pichler** [comment]
Das sollte in der neuen Test-Version passen. Bitte testen, und wenn es passt, dieses Issue schließen!

**Comment by simonkriegnerschramml** [comment]
Ist umgesetzt. Issue wird geschlossen
