### ISSUE TITLE
N-Saldo Berechnung nur für Ackerkulturen von Relevanz

### ISSUE THREAD

**Issue by simonkriegnerschramml** [w3geo/bml-fast#102]
Hallo Arnold,

diese Vorgabe haben wir noch nicht bedacht bzw. habe ich diese noch nirgends in den Systematiken erfasst denke ich. In der Systematik müsste daher ergänzt werden, dass ausschließlich bei der Flächennutzungsart "Ackerland" BAS08 und BAS09 zum Zuge kommen können. Demnach ist der N-Saldo für Ackerflächen mit BAS08 ist zutreffend, BAS09=JA von Relevanz. Für alle anderen Flächennutzungsarten darf kein N-Saldo berechnet werden. Zur Erinnerung der N-Saldo ist das Ergebnis aus Bilanzüberschuss x Reduktionsfaktor (BAS10). Bilanziert müssen aber alle Kulturen (mit Ausnahme der ungenutzten Zwischenfrucht) im System werden.

LG
Simon

**Comment by arnold-pichler** [comment]
Ich denke, das ist jetzt schon so? Bitte überprüfen, sonst Gegenbeispiel senden!

**Comment by simonkriegnerschramml** [comment]
Issue ist bereits ursprünglich umgesetzt gewesen. Es bestand also kein Handlungsbedarf. Ich schließe das Issue.

LG
Simon
