### ISSUE TITLE
Bezeichnung der Einheit bei Wirtschaftsdüngern und Sekundärrohstoffen bei Stickstoffkonzentration

### ISSUE THREAD

**Issue by simonkriegnerschramml** [w3geo/bml-fast#104]
Hallo Arnold,

bei Wirtschaftsdüngern bitte anstatt "N(kg/m3)" die Bezeichnung "Njw(kg/m3) einfügen.
bei Sekundärrohstoffen bitte anstatt "N(kg/t|m3) die Bezeichnung "Njw(kg/t|m3) einfügen.

LG
Simon

**Comment by arnold-pichler** [comment]
Das sollte in der neuen Test-Version passen. Bitte testen, und wenn es passt, dieses Issue schließen!

**Comment by simonkriegnerschramml** [comment]
Danke, das passt nun so. Ich schließe das Issue.

LG
Simon
