### ISSUE TITLE
WRRL Düngeklasse wird nicht berücksichtigt

### ISSUE THREAD

**Issue by simonkriegnerschramml** [w3geo/bml-fast#106]
Hallo Arnold,

Derzeit wird auf Flächen, welche in die Wasserrahmenrichtlinie Graz - Radkersburg fällt nicht korrekt berücksichtigt.

Konkret habe ich eine Fläche mit der Düngeklasse B - Das entspricht der Spalte WRRL Steiermark mittel -10% in den Stammdaten.
Für die Kultur Winterweichweizen <14% RP bedeutet das einen Basiswert für die Düngeobergrenze von 108 kg N. Hier wird aber bei der Auswahl der Ertragslage hoch 1 ein Wert von 170 kg N ausgegeben. Der strengere Wert muss hier schlagend werden und dieser Stammt aus der Vorgabe der Wasserrahmenrichtlinie Graz-Radkersburg in Düngeklasse B.

Bitte entsprechend berücksichtigen.
Wie in folgendem File beschrieben. Möglicherweise passt die Logik nicht mehr, weil es BAS06 nicht mehr gibt. Aber die gab es bei der Erstellung der Systematik schon gar nicht mehr.
Sobald also ein Eintrag für die Düngeklasse WRRL vorhanden ist, muss der Vergleich nach Auswahl der Ertragslage (niedrig bis hoch3) stattfinden.

[Aussaat Hauptfrucht - EL Auswahl - Düngeobergrenzen.xlsx](https://github.com/user-attachments/files/17519663/Aussaat.Hauptfrucht.-.EL.Auswahl.-.Dungeobergrenzen.xlsx)

Das kann man am Beispiel "Baldau 1" erkennen.

[fast-export-2024-10-25 (4).txt](https://github.com/user-attachments/files/17519700/fast-export-2024-10-25.4.txt)

LG
Simon

**Comment by arnold-pichler** [comment]
> Wie in folgendem File beschrieben. Möglicherweise passt die Logik nicht mehr, weil es BAS06 nicht mehr gibt

Die gibt es schon, sie wird nur nicht explizit angezeigt (weil ja aus dem Schlag ausgelesen und nicht änderbar), allerdings erscheint die "Düngeklasse WRRL" nur, wenn die Fläche auch in der WRRL ist!

![image](https://github.com/user-attachments/assets/eec7c963-40d2-42a0-b590-e56b9b7fd41d)


Muss mir das Beispiel anschauen...

**Comment by arnold-pichler** [comment]
Das sollte in der neuen Test-Version passen. Bitte testen, und wenn es passt, dieses Issue schließen!

**Comment by simonkriegnerschramml** [comment]
Danke. Das Issue schließe ich hiermit.

LG
Simon
