### ISSUE TITLE
Benennung der Optionen bei Ackerzahl ändern

### ISSUE THREAD

**Issue by simonkriegnerschramml** [w3geo/bml-fast#107]
Hallo Arnold,

Wir haben derzeit bei der Auswahl der Ackerzahl (BAS11) die Optionen "kleiner/gleich 30" und "größer 30". Eigentlich müssten diese Optionen korrekterweise in "kleiner 30" und "größer / gleich 30" umbenannt werden.

LG
Simon

**Comment by arnold-pichler** [comment]
Das sollte in der neuen Test-Version passen. Bitte testen, und wenn es passt, dieses Issue schließen!

**Comment by simonkriegnerschramml** [comment]
Warum muss hier eine Zahl per Default eingetragen sein. Jetzt steht hier die Zahl 31. Das wird in 99,99 % der Fälle nicht zutreffend sein. Kann man nicht einfach den Wert aus dem Drop Down Menü anführen. Per Default also "größer / gleich 30".

LG
Simon

**Comment by simonkriegnerschramml** [comment]
> > Warum muss hier eine Zahl per Default eingetragen sein. Jetzt steht hier die Zahl 31. Das wird in 99,99 % der Fälle nicht zutreffend sein. Kann man nicht einfach den Wert aus dem Drop Down Menü anführen. Per Default also "größer / gleich 30".
> > LG Simon
> 
> Achtung: Das ist nur bei den vorhandenen Testfällen der Fall, weil hier ein alter Wert eingetragen ist, für den es jetzt kein Gegenstück in der Liste mehr gibt! Denn vorher hatte ich "kleiner/gleich 30" mit dem Wert 30 und "größer 30" mit dem Wert 31, jetzt ist es 29 und 30 - in den alten Testfällen ist damit ein Wert drin, den es in der Liste nicht mehr gibt. Einfach ändern, ab dann passt es. Ist quasi nur ein Kompatibilitätsproblem.

Das ist leider nicht so. Wenn ich einen völlig neuen Schlag buche, müsste per Default ja etwas anderes als die 31 stehen. Das tut es aber nicht.

LG
Simon

**Comment by arnold-pichler** [comment]
Ach ja, blöd - der Default-Wert war noch auf 31. Danke, ist im nächsten Update korrigiert.

**Comment by arnold-pichler** [comment]
Ist korrigiert, muss nur bei vorhandenen Daten neu vergeben werden, wenn "31" im Feld steht.

**Comment by simonkriegnerschramml** [comment]
Ist umgesetzt - Issue wird geschlossen.
