### ISSUE TITLE
Nmin Defaultwert falsch

### ISSUE THREAD

**Issue by simonkriegnerschramml** [w3geo/bml-fast#108]
Hallo Arnold,

Derzeit wird als Defaultwert in der Zelle Nmin der Wert aus der Spalte "VFW|Nmin selbes Jahr" der Hauptfrucht ausgegeben. Hier muss für die HF 1 (wenn keine genutzte ZWF vorhanden) der Wert aus "VFW|Nmin Folgejahr" der Vorfrucht und für den Fall HF1 auf HF2 der Wert aus "VFW|Nmin selbes Jahr" der HF1 ausgegeben werden.

Das kann man am Beispiel des Feldes mit der Bezeichnung Gemüse 1 erkennen.
[fast-export-2024-10-25 (5).txt](https://github.com/user-attachments/files/17520605/fast-export-2024-10-25.5.txt)

Hier werden in der Zelle Nmin der HF 1 (Kraut (Industrie, früh) 95 kg ausgegeben. Hier müsste aber der Wert der Vorfrucht "Zwiebel (Sommer, trocken)" von 45 stehen.

Ebenso habe ich im Beispiel eine HF 2 mit Blattsalat 7 Wochen. Hier steht in der Zelle Nmin ein Wert von 40. Das entspricht aber dem Wert der Spalte "VFW|Nmin selbes Jahr" der Kultur Blattsalate 7 Wochen. Hier müsste der Wert der HF1 (Kraut (Industrie, früh) stehen" und damit der Wert 95.

LG
Simon

LG
Simon

**Comment by arnold-pichler** [comment]
OK, das hatte ich falsch verstanden, wird geändert. Was ist, wenn es keine Vorfrucht gibt
- und keine Zwischenfrucht?
- und eine ungenutzte Zwischenfrucht?
- und eine genutzte Zwischenfrucht?

**Comment by simonkriegnerschramml** [comment]
> OK, das hatte ich falsch verstanden, wird geändert. Was ist, wenn es keine Vorfrucht gibt
> 
> * und keine Zwischenfrucht?
> * und eine ungenutzte Zwischenfrucht?
> * und eine genutzte Zwischenfrucht?


Hallo Arnold:
Zur Info damit wir nichts durcheinander bringen. Nmin immer nur anzeigen wenn es sich bei der aktuell gebuchten Kultur z.B.: HF1 um eine Gemüsekultur handelt. Defaultwert für HF1 bitte aber nur auslesen, wenn es sich bei der Vorfrucht um eine Gemüsekultur handelt. Das gilt auch für HF1 auf HF2 (usw.). Für den Defaultwert der HF2 muss die HF1 eine Gemüsekultur sein. Ansonsten ist der Wert einfach 0.

> * keine Vorfrucht:
dann ist der Wert gleich 0 für den Defaultwert Nmin - Es kann ja nichts ausgelesen werden.
Das wäre übrigens auch der Fall, wenn die Vorfrucht keine Gemüsekultur ist. Da steht in der Spalte "VFW | Nmin Folgejahr" auch meistens 0 drin oder eben ein Vorfruchtwert, der mit dem Nmin aus rechtlicher Sicht nichts am Hut hat.
> * und keine Zwischenfrucht?: keine Zwischenfrucht - direkter Einfluss der Vorfrucht auf HF1 - ist die Vorfrucht eine Gemüsekultur, dann Defaultwert bei HF1 ausgeben. Existiert hingegen auch keine Vorfrucht, dann kann auch aus dieser nichts ausgelesen werden und der Wert ist wiederum 0.
> * und eine ungenutzte Zwischenfrucht?: haben keinen Einfluss auf den Defaultwert für Nmin. Diese haben nur einen Einfluss auf den Vorfruchtwert. Existiert nun keine Vorfrucht, kann in Sachen Defaultwert nichts ausgelesen werden und der Wert ist 0. Zwischenfrüchte können niemals Gemüsekulturen sein.
> * und eine genutzte Zwischenfrucht? diese stellen einen Unterbrechung der Fruchtfolge dar. genutzte ZWF können aber selber niemals Gemüsekulturen sein. Das heißt der Wert aus Spalte "VFW | Nmin Folgejahr" der Vorfrucht wird zum Vorfruchtwert der Nicht Gemüsekultur "genutzte Zwischenfrucht". Da die genutzte ZWF aber selber keine Gemüsekultur sein kann, kann aus ihr im Falle, dass HF1 eine Gemüsekultur sein sollte, kein Defaultwert ausgelesen werden. Existiert hingegen keine Vorfrucht, so ist der Wert für die Vorfruchtwirkung welche der genutzten ZWF angerechnet werden muss gleich 0. Ebenso ist der Defaultwert für die HF1 (falls es sich um Gemüse handeln sollte) 0.

Du kannst mich auch gerne dahingehend anrufen: 05069021563

LG
Simon

**Comment by arnold-pichler** [comment]
Ich mache jetzt mal die Bugfixes zu allen offenen Issues von dir, sammle dabei offene Fragen und dann müssen wir telefonieren! Spätestens Montag gibt's eine neue Version, dann rufen wir uns zusammen!

**Comment by arnold-pichler** [comment]
Das sollte in der neuen Test-Version passen. Bitte testen, und wenn es passt, dieses Issue schließen!

**Comment by simonkriegnerschramml** [comment]
Hallo Arnold. Also bei mir hat sich an den Werten nichts geändert. Auch wenn ich ein völlig neues Feld bespiele. Es steht noch immer ein Nmin Default Wert von 95 kg, wenn ich die Kultur Kraut buche. 

LG
Simon

**Comment by arnold-pichler** [comment]
Achtung: Da muss man genau schauen - die VORGABE sollte sich ändern. Wenn aber schon ein Wert UNGLEICH der Vorgabe drin steht, dann wird der nicht geändert. Das ist eine Logik, die habe ich jetzt mal so implementiert, aber da kann man diskutieren. 

Der Hintergrund ist folgender:
- Wenn du einen neuen Schlag eingibst, dann Ist NMIN manuell = NMIN Vorgabe, und solange das ist, ändern sich  BEIDE Werte mit der Vorfrucht.
- Wenn du aber jetzt einen manuellen NMIN Wert eingibst, sollte sich der ja nicht einfach ändern, nur weil du dich evtl. bei der Vorfrucht verschaut hast, du solltest ja wissen, was du tust, wenn du einen manuellen Wert eingibst.

Das erschien mir aus User-Sicht brauchbar, ist aber mein Ansatz. Ich kann das auch so machen, dass der manuelle Wert bei jeder Änderung resettet wird.

**Comment by arnold-pichler** [comment]
OK, bitte Beispiel. Und wie gesagt, bitte Reload machen. Evtl. ist die alte Version noch im Cache. Ich habe es gerade probiert mit dem Gemüse-Beispiel:

![image](https://github.com/user-attachments/assets/928cecbd-a276-4adc-806d-70f174bddc5d)

**Comment by arnold-pichler** [comment]
Oh, sehe gerade, dass da zwar die Vorgabe der richtige Wert ist, aber der manuelle Wert ein Unsinn. Das muss ich mir anschauen. Also bitte nur checken, ob die VORGABE passt.

**Comment by arnold-pichler** [comment]
Und wie das so ist - das und der Systemabsturz hängen exakt zusammen. Schon gefunden, muss es nur noch reparieren.

**Comment by arnold-pichler** [comment]
Bitte nochmal schauen. Ich musste das jetzt umbauen wg. dem Absturz, soweit ich das sehe, sollte es passen, aber da musst du das Endurteil sprechen!

**Comment by simonkriegnerschramml** [comment]
Danke. Es passt wieder alles und der Defaultwert wird richtig gesetzt.

LG
Simon
