### ISSUE TITLE
Kuriosum bei N-Saldo bei Gemüse - Ertrag scheint keine Auswirkung auf Berechnung zu haben

### ISSUE THREAD

**Issue by simonkriegnerschramml** [w3geo/bml-fast#110]
Hallo Arnold,

betreffend Feldstück "Gemüse 1".
[fast-export-2024-10-25 (6).txt](https://github.com/user-attachments/files/17520866/fast-export-2024-10-25.6.txt)

Ich habe eine Gemüsekultur auf HF1. Kraut (Industrie, früh) und habe eine errechnete Düngeobergrenze von 275 kg. Ich dünge bis zu einem anrechenbaren Stickstoff von 262,5 kg. Ich ernte eine Menge von 80 Tonnen / ha und müsste damit einen N-Entzug von 335 kg gem. Stammdaten haben. Ertagslage mittel geht bei Kraut von 70 - 110 t/ ha. Ich habe also meine Ertragslage eingehalten und muss bei dieser Kultur gem. Saldierungsart 3 in kg N/ha Entzügen rechnen und es gilt die Düngeobergrenze der erreichten Ertragslage als Entzug je ha. Es bleibt defacto nichts mehr übrig 335 -262,5 < 0. Der Saldo muss erst bei einem Bilanzüberschuss von >20 kg/ha berechnet werden.

In der HF 2 "Blattsalate 7 Wochen" scheint nun aber ein N-Saldo von 157,5 kg auf. Wo kommt der auf einmal her und wie kommt es zu diesem Wert? Hier müsste 0 stehen.

**Comment by simonkriegnerschramml** [comment]
Ertrag hat scheinbar keinen Einfluss auf die Saldierung:

in obigem Beispiel ändert sich auch nichts an der Zahl 157,5, wenn ich den Ertrag bei Kraut ändere. Wenn ich bspw. nur mehr 10 Tonnen ernten würde und damit definitiv in der Ertragslage "niedrig" Ernte und damit nur mehr einen Entzug von 250 kg hätte. Die 157,5 bleibt bei Kultur Blattsalate stehen.
Auch wenn ich 80.000 Tonnen als Ertrag eintrage ändert sich nichts.

[fast-export-2024-10-25 (6).txt](https://github.com/user-attachments/files/17520865/fast-export-2024-10-25.6.txt)


LG
Simon

**Comment by arnold-pichler** [comment]
> Auch wenn ich 80.000 Tonnen als Ertrag eintrage ändert sich nichts.

Ja, gemäß der Vorgabe im Excel für die Saldierungsart 3! Hatte mich auch ein wenig gewundert:

![image](https://github.com/user-attachments/assets/00e8bec1-470f-4e6f-b205-48a60afc1e9b)

Hier wird im Gegensatz zur Saldierungsart 2 NICHT mit der Erntemenge multipliziert. Ist vermutlich ein Fehler im Excel?

**Comment by arnold-pichler** [comment]
> Ich habe eine Gemüsekultur auf HF1. Kraut (Industrie, früh) und habe eine errechnete Düngeobergrenze von 275 kg.

Laut Tabelle ist für `Kraut (Industrie, früh)` die `Düngeobergrenze EL mittel` =  335kg ?

**Comment by simonkriegnerschramml** [comment]
> > Auch wenn ich 80.000 Tonnen als Ertrag eintrage ändert sich nichts.
> 
> Ja, gemäß der Vorgabe im Excel für die Saldierungsart 3! Hatte mich auch ein wenig gewundert:
> 
> ![image](https://private-user-images.githubusercontent.com/36012148/382782048-00e8bec1-470f-4e6f-b205-48a60afc1e9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MjkzNDIsIm5iZiI6MTczMDcyOTA0MiwicGF0aCI6Ii8zNjAxMjE0OC8zODI3ODIwNDgtMDBlOGJlYzEtNDcwZi00ZTZmLWIyMDUtNDhhNjBhZmMxZTliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDE0MDQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzOWYwNWJjMThmY2QxMzI1MGY1NDZmMGI5YTZkMTUyMjEyZTljOGRmYjk3NDM0NDBhYmI1NzhjNzM3ZThlYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zGtsp3wikMjp38vFzVSikRVbOnpVHUKDeIo7_1LMSSs)
> 
> Hier wird im Gegensatz zur Saldierungsart 2 NICHT mit der Erntemenge multipliziert. Ist vermutlich ein Fehler im Excel?

Ja und genau das bedeutet ja, dass ich entlang der erreichten Ertragslage Entzüge gem. Stammdaten auslesen muss. Erreicht man nun Erträge im EL Bereich niedrig, dann ist der Entzug gleich der Düngeobergrenze der Ertragslage niedrig.

LG
Simon

**Comment by simonkriegnerschramml** [comment]
> > Ich habe eine Gemüsekultur auf HF1. Kraut (Industrie, früh) und habe eine errechnete Düngeobergrenze von 275 kg.
> 
> Laut Tabelle ist für `Kraut (Industrie, früh)` die `Düngeobergrenze EL mittel` = 335kg ?

 Das stimmt. Aber 275 kg ist die errechnete Düngeobergrenze. Da sind ja schon alle möglichen Abzüge enthalten. Folgende Entzüge können, je nach erreichtem Ertrag (Daten aus der Ernte Maßnahme), für die Kultur zustande kommen:

EL niedrig: 250 kg
EL mittel: 335 kg
EL hoch 1: 420 kg

LG
Simon

**Comment by arnold-pichler** [comment]
> errechnete Düngeobergrenze von 275 kg.

Ich verstehe vermutlich nicht ganz, was damit gemeint ist. Ich habe eine Düngeobergrenze von 335 (das ist das was ich mangels Begriff als "Düngeobergrenze butto" anzeige). Das hatte ich gemeint. Ist damit meine "Düngeobergrenze Netto" gemeint?

Leider habe ich immer noch keine Angaben dazu, was eigentlich ausgegeben werden soll, im Moment werden ja nur alle Parameter ausgegeben, die im Laufe der Berechnungen aus dem Excel irgendwie eine Rolle gespielt haben.

**Comment by arnold-pichler** [comment]
Aber ich sehe schon einen Fehler: Offenbar nehme ich die ERWARTETE Ertragslage, was natürlich nicht stimmt.

**Comment by simonkriegnerschramml** [comment]
> Aber ich sehe schon einen Fehler: Offenbar nehme ich die ERWARTETE Ertragslage, was natürlich nicht stimmt.

Ja es geht beim Entzug immer um die erreichte Ertragslage auf Basis der Verbuchung der Erntemaßnahme. Bei der Düngeobergrenze geht es um die erwartete Ertragslage.

LG
Simon

**Comment by arnold-pichler** [comment]
OK - einen Fehler habe ich schon entdeckt und der ist in den Stammdaten begründet: Für viele Kulturen, wie auch z.B. das Kraut sind nur bis zu einer gewissen Obergrenze die Ertragsgrenzen eingetragen und danach nichts mehr. Im Fall vom Kraut also nur bis "hoch 1" und danach sind die Felder leer. Das wird im Code dann zu 0 und damit ist die Ernte natürlich immer höher als diese Grenze und die Ernte-Ertragslage immer "hoch 3".

Das ist kein Fehler in den Stammdaten, sondern in deren Interpretation, das habe ich einfach nicht korrekt abgefangen. Das ist aber sicher noch nicht alles. Aber da ich jetzt schon viele geändert habe, werde ich nachher mal eine Update-Version deployen, dieses Issue wird aber wohl noch nicht ganz erledigt sein damit. Aber es ist schwierig, den Fehler jetzt weiter auf einer Basis zu erjagen, die es bei mir so nicht mehr gibt.

**Comment by arnold-pichler** [comment]
Bitte schauen, welche Fehler hier nach dem Update noch übrig bleiben, es hat sich jetzt einiges geändert.

**Comment by simonkriegnerschramml** [comment]
Also das mit den Entzügen je ha (Saldierungsart 3), scheint nun korrekt umgesetzt zu sein. Auch die Grenzen passen perfekt. Ich sehe derzeit keine Fehler, aber ich teste eifrig weiter.

LG
Simon

**Comment by simonkriegnerschramml** [comment]
Das sollte stimmen. Ich schließe das Issue.

LG
Simon
