### ISSUE TITLE
System hängt sich immer wieder auf

### ISSUE THREAD

**Issue by simonkriegnerschramml** [w3geo/bml-fast#112]
Ich kann keinen meiner bestehenden Einträge bearbeiten. Wenn ich auf das Bearbeiten Symbol (Stift) klicke, kann ich weder einen Zoom Faktor verstellen, noch kann ich im System irgendetwas bedienen. 
Einen neunen Schlag kann ich aber eintragen. Sobald ich aber einige Zeit daran arbeite, hängt sich auch hier jegliche Funktionalität auf.

LG
Simon

**Comment by arnold-pichler** [comment]
Hmm. Das klingt etwas danach, dass ich da im Cache noch alte Code-Teile mit den neuen vermischen. Evtl. die Seite ein paar Mal neu laden (mit Shift-F5), oder komplett über die Einstellungen den Browser-Cache leeren.

Was ist mit "Zoom Faktor einstellen" genau gemeint? Die Website kann ja das Betriebssystem nicht beeinflussen oder den Browser, das einzige was passieren kann, ist eine Endlos-Schleife, die den Browser komplett auslastet, Da gibt's dann normalerweise ein "keine Rückmeldung". Der Chrome erkennt das und bietet das Schließen des Tabs an.

**Comment by simonkriegnerschramml** [comment]
Ich verwende Edge in der Arbeit. Und egal was ich mache (Browserdaten löschen etc.). Das System hängt sich immer wieder auf. Auch erneutes laden bringt nichts.

LG
Simon

**Comment by arnold-pichler** [comment]
Edge hat die Chrome Engine, das sollte an sich passen. Was meinst du mit dem "System"? Die Website, der Browser oder der gesamte Computer?

Ich bräuchte halt irgend eine Anleitung zum Nachvollziehen, d.h. in der Art "Wenn ich einen neuen Eintrag mache und dann das und jenes, spätestens dann hängt es sich auf". Oder ist es egal, was du tust und nach einigen Minuten hängt es sich auf?

**Comment by simonkriegnerschramml** [comment]
Ich kann keinen meiner gebuchten Schläge bearbeiten. Wenn ich auf den Schlag klicke kann ich in weiterer Folge das FaST Tool nicht mehr bedienen. Weder Zoom, noch irgendwelche Schaltflächen funktionieren. Weder der Browser, noch der PC hängen sich auf, lediglich das FaST System.

LG
Simon

**Comment by arnold-pichler** [comment]
OK - jetzt konnte ich es nachvollziehen.

**Comment by arnold-pichler** [comment]
Das scheint eine Endlos-Schleife zu sein oder sowas.

**Comment by arnold-pichler** [comment]
Ich werde dem nachgehen, davor hat natürlich jedes weitere Testen keinen Sinn mehr.

**Comment by arnold-pichler** [comment]
So - der Fehler ist bereinigt! Beim mir stürzt es jetzt nicht mehr ab. Das passierte übrigens beim Aussuchen / Ändern einer Kultur, da wurde die Bilanz berechnet und in der Bilanz der NMIN gesetzt und aufgrund der Änderung des NMINS die Bilanz berechnet und .... Fertig war das Drama. Mußte das jetzt umbauen, aber damit sollte es wieder passen.

**Comment by simonkriegnerschramml** [comment]
Passt es funktioniert wieder alles.

LG
Simon
