### ISSUE TITLE
Einheit bei Wirtschaftsdüngern nicht korrekt

### ISSUE THREAD

**Issue by simonkriegnerschramml** [w3geo/bml-fast#113]
Hallo Arnold,

Jetzt ist die Einheit bei Wirtschaftsdüngern auf kg/ha. Diese soll auf m3 / ha lauten. Das war schon mal anders.

LG
Simon

**Comment by arnold-pichler** [comment]
Ah, verstehe schon, das ist passiert bei der Einheitsänderung der "Eigenen Handesdünger", da hat es die Wirtschaftsdünger gleich "mitgenommen". Habe ich geändert.

**Comment by simonkriegnerschramml** [comment]
Danke, passt jetzt so.

LG
Simon
