### ISSUE TITLE
Anrechnung des Stickstoff aus der Bewässerung erst ab 10 kg von Relevanz

### ISSUE THREAD

**Issue by simonkriegnerschramml** [w3geo/bml-fast#115]
Hallo Arnold,

Derzeit wird jeglicher Stickstoff aus dem Bewässerungswasser zur Düngung hinzugerechnet. Es ist aber so, dass dies erst ab 10 kg geschehen soll. Also >=10 kg N/ha. Dies gilt als Summe je Kultur (=Fruchtfolgeglied). Werden nun bspw. drei Bewässerungsmaßnahmen auf einer Kultur verbucht, so müssen diese summiert werden. Ist diese Summe >=10, dann muss diese zur Düngung gerechnet werden. Ist diese darunter ist diese irrelevant.

Außerdem müsste die Darstellung des N-Outputs bei den Düngern irgendwie gerundet dargestellt werden. Derzeit haben wir 4 Kommastellen, wirkt in der Bilanz nicht elegant.

Beispiel:
1. Bewässerung: 3 kg N/ha
2. Bewässerung: 3 kg N/ha
3. Bewässerung: 3,5 kg N/ha
SUMME: 9,5 kg N/ha
Hier dürfte die Bewässerung nicht zum anrechenbaren Stickstoff gezählt werden.

Derzeit wird jeglicher Stickstoff hinzugerechnet.

Das ist am Beispiel "Bewässerung 1" erkennbar.

Hier wurde die Menge von 50 mm bei 50 mg/l NO3 Konzentration bewässert. Ergebnis ist 5,6433 kg N/ha.
Also <10 kg und daher noch irrelevant für den anrechenbaren Stickstoff.
Würde ich jetzt dieselbe Maßnahme auf diese Kultur nochmals buchen, dann wäre als Ergebnis 11,2866 kg N/ha natürlich >=10 kg N/ha und diese 11,2866 kg N/ha müssten Teil des anrechenbaren Stickstoffs werden.

[fast-export-2024-11-13.txt](https://github.com/user-attachments/files/17730472/fast-export-2024-11-13.txt)

LG
Simon

**Comment by simonkriegnerschramml** [comment]
Übrigens betrifft das auch den Vorfruchtwert der Vorfrucht aus dem vorangegangenen Jahr.
Dieser wird bereits korrekt auf die HF1 verrechnet. Dasselbe Prozedere wäre auch bei der Düngung umzusetzen.

Was aber noch zu bedenken ist, dass der Vorfruchtwert auch zum anrechenbaren N der ungenutzten Zwischenfrucht  zählen müsste. Für die Gesamtbilanz ist das aber dann nicht von Relevanz, da dieser Vorfruchtwert beim anrechenbaren N der HF1 in die Gesamtbilanz einfließt. Der Vorfruchtwert reduziert die mögliche Düngung zu einer ungenutzten Zwischenfrucht, nicht aber in der gesamten Bilanz.

Da das Prozedere der Herbstdüngung und der Düngeobergrenzen von Zwischenfrüchten durchaus als "SCHWIERIGE RECHENAUFGABE" gewertet werden kann, würde ich generell von einer Düngemaßnahme zu ungenutzten ZWF Abstand nehmen. Es suggeriert dem User, dass dies alles korrekt geprüft werden kann. Das kann es aber nie zu 100%, zumal sich auch der Gesetzgeber nicht zu 100% sicher ist, was denn nun Gültigkeit hat.

LG
Simon

**Comment by arnold-pichler** [comment]
> Da das Prozedere der Herbstdüngung und der Düngeobergrenzen von Zwischenfrüchten durchaus als "SCHWIERIGE RECHENAUFGABE" gewertet werden kann, würde ich generell von einer Düngemaßnahme zu ungenutzten ZWF Abstand nehmen.

Soll ich also die Düngung für ungenutzte ZF ausblenden?

**Comment by arnold-pichler** [comment]
> Übrigens betrifft das auch den Vorfruchtwert der Vorfrucht aus dem vorangegangenen Jahr.
> Dieser wird bereits korrekt auf die HF1 verrechnet. Dasselbe Prozedere wäre auch bei der Düngung umzusetzen.

Das könnte man aber auch über die Stammdaten lösen? D.h. Vorfruchtwerte unter 10 auf 0 setzen?

**Comment by simonkriegnerschramml** [comment]
> > Übrigens betrifft das auch den Vorfruchtwert der Vorfrucht aus dem vorangegangenen Jahr.
> > Dieser wird bereits korrekt auf die HF1 verrechnet. Dasselbe Prozedere wäre auch bei der Düngung umzusetzen.
> 
> Das könnte man aber auch über die Stammdaten lösen? D.h. Vorfruchtwerte unter 10 auf 0 setzen?

Nein das geht nicht. Der Stickstoff aus der Bewässerung ist kein Vorfruchtwert (Defacto ist dieser in der rechtlichen Auslegung zwar schon gleichbedeutend, aber das würde hier zu weit führen). Für uns ist dieser Wert schlichtweg eine Düngung die erst ab 10 kg N/ha und Kultur angerechnet werden muss. Das kann ich nicht in den Stammdaten der Kulturen abbilden. Oder wie hast du das gemeint?

LG
Simon

**Comment by arnold-pichler** [comment]
> Nein das geht nicht. Der Stickstoff aus der Bewässerung

Ich rede nur vom Vorfruchtwert aus der Vorfrucht. Aber ich bin mir ohnehin nicht ganz sicher, ob aus https://github.com/w3geo/bml-fast/issues/115#issuecomment-2473137687 jetzt eine Änderung notwendig ist? Das mit der Bewässerung implementier ich für die nächste Version.

**Comment by arnold-pichler** [comment]
> Soll ich ein eigenes Issue verfassen hierzu?

Ja, am besten auch für die Bewässerung. Sonst sammeln sich hier zu viele Themen. Danke!

**Comment by simonkriegnerschramml** [comment]
> > Da das Prozedere der Herbstdüngung und der Düngeobergrenzen von Zwischenfrüchten durchaus als "SCHWIERIGE RECHENAUFGABE" gewertet werden kann, würde ich generell von einer Düngemaßnahme zu ungenutzten ZWF Abstand nehmen.
> 
> Soll ich also die Düngung für ungenutzte ZF ausblenden?

Ich bespreche das mit Andi. Er muss darüber entscheiden. Wenn er sagt, dass es erhalten bleiben muss, dann muss ich mich dahinter klemmen und eine Prüfsystematik für die Einhaltung der Düngegrenzen schreiben.

LG
Simon

**Comment by arnold-pichler** [comment]
Neue Version deployed - siehe #116 bzgl. der 10kg-Grenze.

**Comment by simonkriegnerschramml** [comment]
Das ist korrekt umgesetzt. Danke.
