### ISSUE TITLE
Stickstoff aus Bewässerung erst ab 10 kg N/ha pro Kultur relevant

### ISSUE THREAD

**Issue by simonkriegnerschramml** [w3geo/bml-fast#116]
Hallo Arnold,

Derzeit wird jeglicher Stickstoff aus dem Bewässerungswasser zur Düngung hinzugerechnet. Es ist aber so, dass dies erst ab 10 kg geschehen soll. Also >=10 kg N/ha. Dies gilt als Summe je Kultur (=Fruchtfolgeglied). Werden nun bspw. drei Bewässerungsmaßnahmen auf einer Kultur verbucht, so müssen diese summiert werden. Ist diese Summe >=10, dann muss diese zur Düngung gerechnet werden. Ist diese darunter ist diese irrelevant.

Außerdem müsste die Darstellung des N-Outputs bei den Düngern irgendwie gerundet dargestellt werden. Derzeit haben wir 4 Kommastellen, wirkt in der Bilanz nicht elegant.

Beispiel:

Bewässerung: 3 kg N/ha
Bewässerung: 3 kg N/ha
Bewässerung: 3,5 kg N/ha
SUMME: 9,5 kg N/ha
Hier dürfte die Bewässerung nicht zum anrechenbaren Stickstoff gezählt werden.
Derzeit wird jeglicher Stickstoff hinzugerechnet.

Das ist am Beispiel "Bewässerung 1" erkennbar.

Hier wurde die Menge von 50 mm bei 50 mg/l NO3 Konzentration bewässert. Ergebnis ist 5,6433 kg N/ha.
Also <10 kg und daher noch irrelevant für den anrechenbaren Stickstoff.
Würde ich jetzt dieselbe Maßnahme auf diese Kultur nochmals buchen, dann wäre als Ergebnis 11,2866 kg N/ha natürlich >=10 kg N/ha und diese 11,2866 kg N/ha müssten Teil des anrechenbaren Stickstoffs werden.

[fast-export-2024-11-13.txt](https://github.com/user-attachments/files/17730472/fast-export-2024-11-13.txt)

LG
Simon

**Comment by arnold-pichler** [comment]
Neue Version deployed:

- Menge aus Bewässerung wird erst ab 10kg angerechnet
- Maximal 2 Kommastellen - das ist beliebig konfigurierbar, bitte einfach um eine Festlegung!

**Comment by simonkriegnerschramml** [comment]
Das ist jetzt korrekt umgesetzt
