### ISSUE TITLE
Vorfruchtwert aus Nicht Gemüsekulturen darf nicht in den Defaultwert bei Nmin Gemüse einfließen

### ISSUE THREAD

**Issue by simonkriegnerschramml** [w3geo/bml-fast#118]
Hallo Arnold,

Nur Vorfruchtwerte aus Gemüsekulturen dürfen in den Defaultwert bei Nmin einfließen. Ist die Vorfrucht keine Gemüsekultur, so bleit der Defaultwert bei der folgenden Gemüsekultur bei 0. In meinem Beispiel werden die 20 kg Vorfruchtwert aus der Nicht-Gemüsekultur "Winterackerbohne" per Default in die Zelle "Nmin" geschrieben.

Außerdem muss der Vorfruchtwert aus Nicht Gemüsekulturen immer angerechnet werden. Das ist derzeit nicht der Fall wenn der Vorfruchtwert aus einer Nicht Gemüsekultur zufällig dem Wert in der Zelle Nmin entspricht. (siehe #119)

In meinem Beispiel müssten 20 kg aus der Vorfrucht "Winterackerbohne" und 20 kg aus der Zelle Nmin angerechnet werden.

Am Feld "Nicht Gemüse auf Gemüse" erkennbar.
[fast-export-2024-11-13 (1).txt](https://github.com/user-attachments/files/17731604/fast-export-2024-11-13.1.txt)

LG
Simon

**Comment by arnold-pichler** [comment]
Das gilt dann eigentlich auch für HF1 auf HF2 ? Denn da ist es aktuell auch so, dass der Vorgabe NMIN Wert von HF2 aus HF1 genommen wird, egal, ob es Gemüse ist oder nicht.

Wie ist es da mit einem "Vorfruchtwert" ? Der sollte eigentlich egal sein, oder? Weil er ja sowieso bei der HF1 schlagend wird.

**Comment by simonkriegnerschramml** [comment]
> Das gilt dann eigentlich auch für HF1 auf HF2 ? Denn da ist es aktuell auch so, dass der Vorgabe NMIN Wert von HF2 aus HF1 genommen wird, egal, ob es Gemüse ist oder nicht.
exakt so soll es auch bei HF1 auf HF2 usw. sein. 


> Wie ist es da mit einem "Vorfruchtwert" ? Der sollte eigentlich egal sein, oder? Weil er ja sowieso bei der HF1 schlagend wird.
Vorfruchtwert aus nicht Gemüse Kulturen ist immer anzuwenden.
Vorfruchtwert von Gemüse auf nicht Gemüse Kulturen ebenso. 

LG
Simon

**Comment by simonkriegnerschramml** [comment]
> > Nur Vorfruchtwerte aus Gemüsekulturen dürfen in den Defaultwert bei Nmin einfließen
> 
> Bedeutet jetzt:
> 
> * Ist Vorfrucht KEIN Gemüse aber HF1 schon, dann wird HF1 der Vorfruchtwert + ein allenfalls eingegebener NMIN Wert angerechnet
genau

> * Ist Vorfrucht Gemüse und auch HF1, dann wird aber nur der NMIN Wert angerechnet (und die Vorgabe kommt aus der VF)?
In unserem Fall schon, da wir keine Schlagteilungen und Zusammenlegungen abbilden. Also kann deine Frage mit Ja beantwortet werden, außer der Nmin Wert der aus der VF ausgelesen wird (also unser Defaultwert) wird manuell überschrieben.

LG
Simon

**Comment by arnold-pichler** [comment]
> Ist Vorfrucht Gemüse und auch HF1, dann wird aber nur der NMIN Wert angerechnet (und die Vorgabe kommt aus der VF)?

Blöde Frage von mir, dazu gibt es ja eh die Systematisierung im Excel.

**Comment by arnold-pichler** [comment]
Neue Version deployed. Oben genannte Probleme sollten gefixed sein. Allerdings wäre es wichtig, nochmal die Gesamtsystematik zu testen, denn durch die vielen kleinen Änderungen besteht die Gefahr, dass andere Dinge jetzt nicht mehr korrekt sind, ich habe mich zwar bemüht, das alles nochmal durchzuschauen, aber... Die automatischen Tests wären evtl. doch nicht ganz dumm gewesen.

**Comment by simonkriegnerschramml** [comment]
Das passt jetzt so.
