### ISSUE TITLE
Obergrenzen N-Saldo wurden noch nicht spezifiziert.

### ISSUE THREAD

**Issue by simonkriegnerschramml** [w3geo/bml-fast#126]
Hallo Arnold,

in all den Diskussionen ist ein wichtiger Part untergegangen. und Zwar gibt es ab 2025 einen Korridor innerhalb dessen ein N-Saldo berechnet werden muss. Dieser liegt zwischen 20 und 100 kg N Bilanzüberschuss. Die 20 kg sind in den Spezifikationen bereits abgedeckt, nicht jedoch die 100 kg. Das habe ich total vergessen.

Für BAS16 würde ich das nur mit einem Hinweistext anführen - Was in der Zelle steht ist dem User überlassen. Dort würde ich auch Werte >80 kg zulassen. Für HF1 auf HF2 ist das aber von Relevanz. Bei 100 kg Bilanzüberschuss ist für die weitere Verrechnung des N-Saldo Schluss. Es resultieren daraus in weiterer Folge N-Saldi, die im Maximum 60 kg im Feuchtgebiet und 80 kg im Trockengebiet ausmachen (Multiplikation mit dem Reduktionsfaktor 0,6 bzw. 0,8).

Das ist in den Matrizes nicht enthalten, da das kein Entscheidungskriterium darstellt. Es muss nur in den Berechnungen umgesetzt werden, um eine korrekte Ausgabe zu generieren.

LG
Simon

**Comment by arnold-pichler** [comment]
Aber das muss erst ab 2024 umgesetzt werden, d.h. ich müsste da unterscheiden zwischen Berechnungen für 2024 und ab 2025?

**Comment by simonkriegnerschramml** [comment]
Ja und eigentlich schon für die letzte Hauptfrucht aus 2024. Da als Resultat dieser letzten HF ein Saldo steht der für das kommende Jahr von Relevanz ist. Wir geben im Jahr 2024 aus was im Jahr 2025 in BAS 16 stehen müsste. Was der User dann damit macht ist ihm selbst überlassen. Wir geben nur diese Info aus.

LG
Simon

**Comment by simonkriegnerschramml** [comment]
Die Obergrenze wird derzeit noch nicht berücksichtigt.

In meinem Beispiel anhand des Sommerhafer auf HF2 erkennbar. Hier dürfte im Feuchtgebiete maximal 60 kg N-Saldo übrig bleiben (100 kg maximal an Bilanzüberschuss für den N-Saldo multipliziert mit dem Reduktionsfaktor für Feuchtgebiete von 0,6).

Beispielbezeichnung:
Test5 - WRRL und GWA mit genutzter ZWF
[fast-export-2024-12-13 (1).txt](https://github.com/user-attachments/files/18125822/fast-export-2024-12-13.1.txt)


LG
Simon

**Comment by arnold-pichler** [comment]
Ist implementiert, bitte testen!

**Comment by simonkriegnerschramml** [comment]
FIXED. Ich schließe das Issue.

LG
Simon

**Comment by simonkriegnerschramml** [comment]
Hier wurde leider das Bewertungskriterium für die Anrechnung von Nmin manuell nicht mitgedacht.
Bei der Bewertung, welcher Wert denn nun strenger ist, muss natürlich die errechnete Obergrenze gelten und nicht der Bilanzwert x Reduktionsfaktor.

LG
Simon

**Comment by simonkriegnerschramml** [comment]
Ich schließe daher dieses Issue.

LG
Simon
