### ISSUE TITLE
Wirtschaftsjahre dürfen erst ab 2025 verfügbar sein

### ISSUE THREAD

**Issue by simonkriegnerschramml** [w3geo/bml-fast#132]
Wir müssen die Wirtschaftsjahrauswahl ab 2025 begrenzen. Eine Auswahl von 2023 und 2024 können wir nicht abbilden. Hier gab es noch andere Vorgaben betreffend N-Saldierung. Wir haben alle unsere Entscheidungsmatrizes auf die Vorgaben ab dem WJ 2025 spezifiziert. Ansonsten hätten wir eine eigene Vorgehensweise für 2023 und 2024 benötigt. Daher bitte die Wirtschaftsjahrauswahl beginnend mit 2025 umsetzen.

LG
Simon

**Comment by arnold-pichler** [comment]
Ist in der neuen Version umgesetzt.

**Comment by simonkriegnerschramml** [comment]
Ist umgesetzt. Ich schließe das Issue.
