### ISSUE TITLE
Problematik Grundwasserschutz Graz bis Radkersburg (gemäß Abstimmungsmeeting 2024-06-18)

### ISSUE THREAD

**Issue by arnold-pichler** [w3geo/bml-fast#14]
### Problematik:
Werte BAS06 / BAS07 laut XLS Spezifikations-Tabelle:

BAS06 | Fläche im Grundwasserschutz Graz   bis Radkersburg
-- | --
BAS07 | Düngeklasse Grundwasserschutz Graz bis Radkersburg

Im Agraratlas sind pro Schlag folgende Daten vorhanden (Beispiel):

```
    "nitrataktionsprogramm": 4.31504387,
    "bdfl_l16_grundwasserschutz_acker": 4.31504387,
    "bdfl_l26_wasserrahmenrichtlinie_ertragslagen-el_hoch_1": 3.5934204140912755,
    "bdfl_l26_wasserrahmenrichtlinie_ertragslagen-el_mittel": 0.07337849510208116,
    "bdfl_l26_wasserrahmenrichtlinie_ertragslagen-el_hoch_2": 0.6877755716688434,
    "bdfl_l26_wasserrahmenrichtlinie_ertragslagen-el_hoch_3": 0,
    "bdfl_l26_wasserrahmenrichtlinie_ertragslagen-el_mittel_10": 0,
    "bdfl_l26_wasserrahmenrichtlinie_ertragslagen-el_niedrig": 0
```

### Fragen / Antworten aus Meeting:
- Woraus befüllt sich BAS06 ?
  - Vorrübergehende Antwort: Sobald einer der `bdfl_l26_wasserrahmenrichtlinie_ertragslagen-el_...` - Werte > 0 ist, wird BAS 06 mit "JA" angezeigt, ansonsten mit "NEIN"
- Wie befüllt sich BAS07 ? (Vorausgesetzt BAS06 ist "JA")
  -  Es wird die Fläche + Ertragslage übernommen mit dem höchsten Wert. Dabei werden die Werte in die Kategorisierung "A - F" übersetzt, d.h. im obigen Beispiel wäre BAS06 = JA und BAS07 = D (3.593... ha)

### Vom AG zu klären:
  - Ist das korrekt?
  - Genügt die Klasse A-F oder wird auch die Fläche benötigt?

**Comment by simonkriegnerschramml** [comment]
Hallo Arnold,

BAS 06 ist hinfällig. BAS 07 soll hingegen die hinterlegte Ertragslage anzeigen.
Ich würde ein allgemein verständliches Wording vorschlagen, das auch vom User verstanden wird.

„Fläche im Reg. Programm Stmk. – Düngeklasse C“

Dieser Eintrag muss editierbar sein und auch mit einer Option versehen sein, dass der User die Auswahl hat, keine der zutreffenden Düngeklassen auszuwählen und demnach angibt, dass die Fläche nicht in diesem Maßnahmengebiet liegt.

Grundsätzlich ist mir noch aufgefallen, dass in der Verordnung immer von Düngeklassen gesprochen wird und nicht von Ertragslagen. Das könnte man im Sinne der Verständlichkeit ebenfalls so benennen. Es gibt also Düngeklasse A-F.

Meiner Meinung nach ist die Angabe ohne der Fläche ausreichend. Düngeklasse A-F entspricht dem Wording der Verordnung.

LG
Simon


Disclaimer und Datenschutz der Landwirtschaftskammer Oberösterreich
Diese Nachricht ist vertraulich. Im Falle einer Fehlleitung, verständigen Sie bitte den Absender und löschen Sie diese Nachricht und alle Anhänge. Sollten Sie nicht der beabsichtigte Adressat sein, ist jede Offenlegung, Weiterleitung oder sonstige Verwendung dieser Information nicht gestattet. Soweit gesetzlich zulässig, schließt der Absender jede Haftung für Schäden aus Übertragungsfehlern, Viren, fremden Einfluss, Verzögerungen und dergleichen aus. Nähere Informationen zum Datenschutz finden Sie unter:  www.ooe.lko.at/datenschutz<http://www.ooe.lko.at/datenschutz>
Von: Arnold Pichler ***@***.***>
Gesendet: Dienstag, 18. Juni 2024 15:40
An: w3geo/bml-fast ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [w3geo/bml-fast] Problematik Grundwasserschutz Graz bis Radkersburg (gemäß Abstimmungsmeeting 2024-06-18) (Issue #14)

Problematik:

Werte BAS06 / BAS07 laut XLS Spezifikations-Tabelle:
BAS06

Fläche im Grundwasserschutz Graz bis Radkersburg

BAS07

Düngeklasse Grundwasserschutz Graz bis Radkersburg


Im Agraratlas sind pro Schlag folgende Daten vorhanden (Beispiel):

    "nitrataktionsprogramm": 4.31504387,

    "bdfl_l16_grundwasserschutz_acker": 4.31504387,

    "bdfl_l26_wasserrahmenrichtlinie_ertragslagen-el_hoch_1": 3.5934204140912755,

    "bdfl_l26_wasserrahmenrichtlinie_ertragslagen-el_mittel": 0.07337849510208116,

    "bdfl_l26_wasserrahmenrichtlinie_ertragslagen-el_hoch_2": 0.6877755716688434,

    "bdfl_l26_wasserrahmenrichtlinie_ertragslagen-el_hoch_3": 0,

    "bdfl_l26_wasserrahmenrichtlinie_ertragslagen-el_mittel_10": 0,

    "bdfl_l26_wasserrahmenrichtlinie_ertragslagen-el_niedrig": 0

Fragen / Antworten aus Meeting:

  *   Woraus befüllt sich BAS06 ?
     *   Vorrübergehende Antwort: Sobald einer der bdfl_l26_wasserrahmenrichtlinie_ertragslagen-el_... - Werte > 0 ist, wird BAS 06 mit "JA" angezeigt, ansonsten mit "NEIN"
  *   Wie befüllt sich BAS07 ? (Vorausgesetzt BAS06 ist "JA")
     *   Es wird die Fläche + Ertragslage übernommen mit dem höchsten Wert. Dabei werden die Werte in die Kategorisierung "A - F" übersetzt, d.h. im obigen Beispiel wäre BAS06 = JA und BAS07 = D (3.593... ha)

Vom AG zu klären:

  *   Ist das korrekt?
  *   Genügt die Klasse A-F oder wird auch die Fläche benötigt?

**Comment by arnold-pichler** [comment]
Ist mittlerweile umgesetzt.
