### ISSUE TITLE
Fehler bei WRRL Flächen ohne Eintrag

### ISSUE THREAD

**Issue by simonkriegnerschramml** [w3geo/bml-fast#144]
Hallo Arnold,

Wir eine WRRL Fläche angewählt und eine Kultur gewählt welche keinen Eintrag in den Spalten WRRL in den Stammdaten besitzt, so werden keine Werte in der Bilanz ausgegeben. Wenn hier nichts steht, dann gibt es laut Wasserrahmenrichtlinie keine Werte für WRRL. Aber es gibt sehr wohl Werte gem. Nitrataktionsprogrammverordnung. Also wenn keine Werte bei WRRL eingetragen sind müssen die Werte gem. eingetragenen Ertragslagen ausgelesen werden.

Beispiel: Test3 - WRRL Grünmais

[fast-export-2024-12-11 (4).txt](https://github.com/user-attachments/files/18098001/fast-export-2024-12-11.4.txt)

LG
Simon

**Comment by arnold-pichler** [comment]
Wurde mit dem Fix von #140 mit behoben.

**Comment by simonkriegnerschramml** [comment]
#144 gilt als gefixed.
Ich schließe das Issue.

LG
Simon
