### ISSUE TITLE
Systematisierung V3

### ISSUE THREAD

**Issue by arnold-pichler** [w3geo/bml-fast#15]
Ich habe eine V3 der Systematisierung auf die Cloud geladen und in Gelb jene Bereiche markiert, die in der Abstimmung ( 2024-06-18 ) Thema waren.

Neben BAS06 / 07 waren das vor allem die Ernten.

Es genügt, EINE Ernte allgemein zu spezifizieren, ein Eintrag für einen Schlag kann dann 1-X Ernten enthalten, wobei diese eine Zwischen- oder Hauptfrucht sein dürfen. Zwei Zwischenfrüchte in Folge können von der Software verhindert werden, wenn dies gewünscht ist.

**Comment by arnold-pichler** [comment]
Woraus bestehen die Angaben für eine Ernte? Wir haben ja gesagt, dass es da unterschiedliche gibt, also in Tonnen, in m³ usw.

D.h. eine Ernte besteht dann aus einer Zahl für die Menge und einer Einheit (m³ usw.)? Oder noch was? (also z.B. bei Getreide Frucht und  "Abfall" oder sowas - sorry, bin ja kein Fachmann).

Das ist eigentlich nur das, was mir noch fehlt, um es ganz zu verstehen.

**Comment by simonkriegnerschramml** [comment]
Also in der rudimentärsten Form besteht die Ernte aus der Angabe der Einheit und der Menge. Im einfachsten Fall nehmen wir vereinfacht nur jene Kulturen, die auch in der AMA-Düngewerttabelle (also jene die wir morgen Freitag aktualisieren werden) mit m3 angeführt sind, automatisch mit m3. Der Rest wird einfach mit Tonnen angeführt. Wenn wir das anders machen wollen, dann wird’s tw. richtig kompliziert und aufwändig im Hinblick auf die N Saldierung für GW Acker.

LG
Simon


Disclaimer und Datenschutz der Landwirtschaftskammer Oberösterreich
Diese Nachricht ist vertraulich. Im Falle einer Fehlleitung, verständigen Sie bitte den Absender und löschen Sie diese Nachricht und alle Anhänge. Sollten Sie nicht der beabsichtigte Adressat sein, ist jede Offenlegung, Weiterleitung oder sonstige Verwendung dieser Information nicht gestattet. Soweit gesetzlich zulässig, schließt der Absender jede Haftung für Schäden aus Übertragungsfehlern, Viren, fremden Einfluss, Verzögerungen und dergleichen aus. Nähere Informationen zum Datenschutz finden Sie unter:  www.ooe.lko.at/datenschutz<http://www.ooe.lko.at/datenschutz>
Von: Arnold Pichler ***@***.***>
Gesendet: Mittwoch, 19. Juni 2024 07:47
An: w3geo/bml-fast ***@***.***>
Cc: Kriegner-Schramml Simon ***@***.***>; Comment ***@***.***>
Betreff: Re: [w3geo/bml-fast] Systematisierung V3 (Issue #15)


Woraus bestehen die Angaben für eine Ernte? Wir haben ja gesagt, dass es da unterschiedliche gibt, also in Tonnen, in m³ usw.

D.h. eine Ernte besteht dann aus einer Zahl für die Menge und einer Einheit (m³ usw.)? Oder noch was? (also z.B. bei Getreide Frucht und "Abfall" oder sowas - sorry, bin ja kein Fachmann).

Das ist eigentlich nur das, was mir noch fehlt, um es ganz zu verstehen.

**Comment by arnold-pichler** [comment]
Ich meine, hier sollten wir genau so viel reinnehmen, dass
- die Bilanz halbwegs korrekt erstellt werden kann
- es für den User noch benutzbar beibt!

Insofern ist dein Vorschlag wohl am besten! Dann machen wir es so. Dann kommt aus der Düngewerttabelle schon die Einheit? Dann braucht er nur mehr die Menge angeben und die Einheit schreiben wir dazu (denn die Einheit ergibt sich aus der Kultur)

**Comment by simonkriegnerschramml** [comment]
Ja ich werde noch eine Spalte mit der Einheit in die Stammdaten einfügen.

Ach ja, ich habe vergessen zu sagen, dass das derzeit so ist. Für die nächste Gesetzesnovelle ist alles offen was Erntenebenprodukte und dem Saldo generell anbelangt.

LG
Simon

**Comment by simonkriegnerschramml** [comment]
Vielleicht sollte man die die erreichte Ertragslage bei der Eingabe der Erntemenge nebenbei anzeigen. Das erläutere ich nochmal im Detail, nur damit man das platztechnisch mitdenken kann.

LG
Simon
