### ISSUE TITLE
In der Schlagbilanz steht in der Kategorie Stickstoff das chemische Kürzel für Kalium

### ISSUE THREAD

**Issue by simonkriegnerschramml** [w3geo/bml-fast#151]
Hallo Arnold,

In der Schlagbilanz gesamt (kleine und große Ansicht) wird im ersten Parameter " kg K2O" angeführt. Da sollte "kg Njw" bzw. "kg N" stehen.

![gesamtbilanz Bug](https://github.com/user-attachments/assets/cd7b68c1-fd35-4268-a41b-36d344c0ff19)

LG
Simon

**Comment by arnold-pichler** [comment]
Danke, Copy & Paste - Fehler, korrigiere ich noch!

**Comment by arnold-pichler** [comment]
Ist korrigiert.

**Comment by simonkriegnerschramml** [comment]
passt. Ich schließe das Issue.

LG
Simon
