### ISSUE TITLE
Hinweismeldung zu Phosphor erscheint sobald der Entzug überschritten ist

### ISSUE THREAD

**Issue by simonkriegnerschramml** [w3geo/bml-fast#154]
Hallo Arnold,

sobald der Phosphor aus der Düngung den Entzugswert überschreitet, kommt die Hinweismeldung. Auch hier sollte diese erst erscheinen, wenn der Bedarf gem. Ertragslagenschätzung überstiegen wird.

Testfeld: Test7 - Hinweistexte N und P
[fast-export-2024-12-18 (1).txt](https://github.com/user-attachments/files/18181549/fast-export-2024-12-18.1.txt)

LG
Simon

**Comment by arnold-pichler** [comment]
Ist in der aktuellen Version hoffentlich korrekt umgesetzt.

**Comment by simonkriegnerschramml** [comment]
Danke, ist korrekt umgesetzt.

LG
Simon
