### ISSUE TITLE
Stammdaten Kulturen neu einspielen bitte

### ISSUE THREAD

**Issue by simonkriegnerschramml** [w3geo/bml-fast#156]
Es haben sich aufgrund einer spontanen Korrespondenz mit dem BML betreffend AMA Düngewerttabelle, Änderungen an den bisherigen Zahlenwerten für den Vorfruchtwert aus Gemüsekulturen ergeben. daher müsste das Stammdatenfile neu eingespielt werden.

Ich muss dieses neu konvertieren. Ich kann das aber nur von meinem privat PC aus machen, da die technischen Mittel an meinem Arbeitsplatz leider stark eingeschränkt sind und Formatierungsprobleme verursacht. Ich schicke sobald möglich das File heute noch durch.

LG
Simon

**Comment by simonkriegnerschramml** [comment]
Hallo Arnold,

anbei die Daten. Ich hoffe ich habe nirgendwo noch einen Fehler drin.

[2024_12_19_Stammdaten Kulturen.csv](https://github.com/user-attachments/files/18196768/2024_12_19_Stammdaten.Kulturen.csv)
[2024_12_19_Stammdaten Kulturen.xlsx](https://github.com/user-attachments/files/18196770/2024_12_19_Stammdaten.Kulturen.xlsx)

LG
Simon

**Comment by arnold-pichler** [comment]
Auf den ersten Blick schaut das gut aus.

**Comment by arnold-pichler** [comment]
Neue Stammdaten sind drin

**Comment by simonkriegnerschramml** [comment]
Super, Danke.

LG
Simon
