### ISSUE TITLE
Systematisierung Excel

### ISSUE THREAD

**Issue by arnold-pichler** [w3geo/bml-fast#26]
Hier werden die laufend upgedateten Versionen des Systematisierungs-Excels und die dazugehörigen Anmerkungen / Diskussionen gesammelt

**Comment by arnold-pichler** [comment]
[Systematisierung Input Output V5 (AP).xlsx](https://github.com/user-attachments/files/16280173/Systematisierung.Input.Output.V5.AP.xlsx)

@simonkriegnerschramml : Anbei die aktualisierte Version des Excel. Wichtig wäre zu wissen, welche Werte noch bei einer Ernte einzugeben sind (nur bei bestimmten Kulturen), also z.B. die Feuchte usw. Bitte alle anführen, die es geben KANN.

![image](https://github.com/user-attachments/assets/a11257fa-5522-4faa-9294-f7694b755766)

**Comment by simonkriegnerschramml** [comment]
Ich habe noch einen Punkt vergessen und weiß nicht, wo er hier am besten aufgehoben ist.

BAS08 (Vorbeugender Grundwasserschutz - Acker) ist nur auf Ackerflächen von Relevanz. Es war zwar so gedacht, dass BAS08 eh nur angezeigt wird, wenn im Agraratlas der Layer zutreffend ist, aber leider ist mir aufgefallen, dass auch Grünlandflächen im Layer liegen und bei diesen diese Option nicht angezeigt werden soll. Daher bitte BAS 08 und in weiterer Folge BAS09 und BAS10 auf die Nutzungsart Acker einschränken.

LG
Simon

**Comment by simonkriegnerschramml** [comment]
Ich habe eine Änderung am Systematisierungsfile vorgenommen. BAS 
[Systematisierung.Input.Output.V6.AP.xlsx](https://github.com/user-attachments/files/16926335/Systematisierung.Input.Output.V6.AP.xlsx)


LG
Simon

**Comment by arnold-pichler** [comment]
> Ich habe eine Änderung am Systematisierungsfile vorgenommen. BAS16 - N-Saldo wurde an die Berechnungsmatrix angepasst. [Systematisierung.Input.Output.V6.AP.xlsx](https://github.com/user-attachments/files/16926335/Systematisierung.Input.Output.V6.AP.xlsx)
> 
> LG Simon

Das war ja eigentlich schon korrekt, implementiert, oder nicht:

![image](https://github.com/user-attachments/assets/556985db-9e7f-4d19-a483-f5fa5f990117)

**Comment by simonkriegnerschramml** [comment]
Nein, ich habe das Wording geändert, da hier eine klare Unterscheidung zwischen N-Überschuss (=Bilanzüberschuss) und N-Saldo erkennbar sein muss. BAS16 müsste korrekterweise als N-Saldo bezeichnet werden, da hier bereits der Reduktionsfaktor einmalig berücksichtigt werden muss, also die Eingabe durch den User inkl. dieses Berechnungschrittes erfolgen muss. Der Stickstoffüberschuss wäre noch vor dieser Multiplikation zu bewerten.
Daher müsste hier der Parameter BAS16 als "N-Saldo aus dem vorangegangenen Wirtschaftsjahr (kg N/ha)" bezeichnet werden.
Sorry für die Umstände.

Ich ändere das Systematikfile dahingehend noch ab.

LG
Simon

**Comment by arnold-pichler** [comment]
Das ist jetzt aber dann etwas anderes ZUSÄTZLICH zum Stickstoffüberschuss oder nur eine Umbenennung? Und hat wiederum nichts mit https://github.com/w3geo/bml-fast/issues/41#issue-2474843980 zu tun? Ich setze das auf die TO für morgen und wir klären das bitte.

**Comment by simonkriegnerschramml** [comment]
> Das ist jetzt aber dann etwas anderes ZUSÄTZLICH zum Stickstoffüberschuss oder nur eine Umbenennung? Und hat wiederum nichts mit [#41 (comment)](https://github.com/w3geo/bml-fast/issues/41#issue-2474843980) zu tun? Ich setze das auf die TO für morgen und wir klären das bitte.

Das hat mit dem "Nmin Eingabe zur Aussaat von Gemüsekulturen #41" nichts zu tun. Es handelt sich dabei nur um eine Differenzierung, damit man sich besser auskennt, was denn nun hier anzuführen ist.  Der Stickstoffüberschuss stammt aus der Bilanzierung nach der Ernte und entspricht dem Bilanzüberschuss. Der N-Saldo ist hingegen jener Wert den Teilnehmer an der ÖPUL Maßnahme "Vorbeugender Grundwasserschutz - Acker" der Düngeobergrenze der Folgekultur in Abzug bringen müssen. Der Stickstoffüberschuss ist der Basiswert, der zur Berechnung des N-Saldo erforderlich ist. Hierzu wird der Stickstoffüberschuss mit dem Reduktionsfaktor, welcher aus BAS10 resultiert, multipliziert. BAS16 sollte demnach den N-Saldo und nicht den Stickstoffüberschuss beinhalten.

LG
Simon
