### ISSUE TITLE
Auswahllogiken, Anzeigelogiken und Daten Referenz Stammdaten

### ISSUE THREAD

**Issue by simonkriegnerschramml** [w3geo/bml-fast#28]
In diesem Issue werden alle relevanten Logiken für die Auswahl, Anzeige und Daten Referenz zu den Stammdaten platziert.

**Comment by simonkriegnerschramml** [comment]
So nun habe ich das Schema mit den Spaltenbezügen und den Entscheidungskaskaden für die Aussaat Hauptfrucht inkl. der Ertragslagenauswahl, der Anzeige der Düngeobergrenzen für Stickstoff und des Nährstoffbedarfs für Phosphor und Kalium vervollständigt. Bei Fragen bitte gerne melden. Die Datei beinhaltet auch schon einen Punkt für die Entzugszahlen für Phosphor und Kalium. Diese bitte ignorieren, diese habe ich einfach schon mal hineingegeben, da ich diese für die Ertragserfassung benötige und ich diese später einfach herauskopieren kann.

[Aussaat Hauptfrucht - EL Auswahl - Düngeobergrenzen.xlsx](https://github.com/user-attachments/files/16470984/Aussaat.Hauptfrucht.-.EL.Auswahl.-.Dungeobergrenzen.xlsx)

**Comment by simonkriegnerschramml** [comment]
Ich habe die Aussaat Zwischenfrucht ungenutzt und genutzt noch ergänzt und eine Änderung für die Aussaat Hauptfrucht durchgeführt. Ich bin gerade dabei die Maßnahme Ernte zu systematisieren und dabei auch die Entzugsformeln festzulegen. Das wird aber bis inkl. Montag dauern, dass ich das beisammen habe. Das sind dann alle Grundvoraussetzungen für die Berechnung des Saldos und der Bilanzen.

**Comment by arnold-pichler** [comment]
Frage: Die "Vorfrucht", ist das genau die ungenutzte Zwischenfrucht, die nur am Beginn stehen darf?

![image](https://github.com/user-attachments/assets/2b6ed921-6666-43ac-ac3b-36de3acafa9a)

Wenn ja, würde ich sie nämlich da rausgeben und in die Abfolge von Aussaaten / Ernten einfügen.

**Comment by simonkriegnerschramml** [comment]
Nein das ist die letzte Hauptfrucht aus dem vorangegangenen Wirtschaftsjahr.

LG
Simon


Disclaimer und Datenschutz der Landwirtschaftskammer Oberösterreich
Diese Nachricht ist vertraulich. Im Falle einer Fehlleitung, verständigen Sie bitte den Absender und löschen Sie diese Nachricht und alle Anhänge. Sollten Sie nicht der beabsichtigte Adressat sein, ist jede Offenlegung, Weiterleitung oder sonstige Verwendung dieser Information nicht gestattet. Soweit gesetzlich zulässig, schließt der Absender jede Haftung für Schäden aus Übertragungsfehlern, Viren, fremden Einfluss, Verzögerungen und dergleichen aus. Nähere Informationen zum Datenschutz finden Sie unter:  www.ooe.lko.at/datenschutz<http://www.ooe.lko.at/datenschutz>
Am 08.08.2024 13:28 schrieb Arnold Pichler ***@***.***>:

Frage: Die "Vorfrucht", ist das genau die ungenutzte Zwischenfrucht, die nur am Beginn stehen darf?

image.png (view on web)<https://github.com/user-attachments/assets/2b6ed921-6666-43ac-ac3b-36de3acafa9a>

Wenn ja, würde ich sie nämlich da rausgeben und in die Abfolge von Aussaaten / Ernten einfügen.

**Comment by simonkriegnerschramml** [comment]
> Frage: Die "Vorfrucht", ist das genau die ungenutzte Zwischenfrucht, die nur am Beginn stehen darf?
> 
> ![image](https://private-user-images.githubusercontent.com/36012148/356201325-2b6ed921-6666-43ac-ac3b-36de3acafa9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNzkzOTIsIm5iZiI6MTcyMzE3OTA5MiwicGF0aCI6Ii8zNjAxMjE0OC8zNTYyMDEzMjUtMmI2ZWQ5MjEtNjY2Ni00M2FjLWFjM2ItMzZkZTNhY2FmYTlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDA0NTEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhZWIwZDc5YTIxYTBiZTBkMzg1MmU1NzJiMmM5YmFhNzM3YmU1NmY4ZDE0NzRmMjAzZDk2ODQ4MGRhOTAyYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uEw1JzlIgavQqZKHLRtE33oWvz6_0ieCPDXbqQQEOAs)
> 
> Wenn ja, würde ich sie nämlich da rausgeben und in die Abfolge von Aussaaten / Ernten einfügen.

Bitte die Vorfrucht so wie beschrieben umsetzen. Die Vorfrucht ist die letzte Hauptkultur (=bis zur Ernte gebrachte Kultur) des vorangegangenen Wirtschaftsjahres. Diese hat mit der Abfolge in einem Wirtschaftsjahr nichts zu tun. Wir brauchen diese um Vorfruchtwerte auszulesen oder im Falle von Gemüsekulturen den Nmin/Vorfruchtwert zu berechnen.

LG
Simon

**Comment by arnold-pichler** [comment]
AH, OK. Na dann ist es eh jetzt schon korrekt.

**Comment by arnold-pichler** [comment]
@simonkriegnerschramml - sehe ich das richtig, dass eine Zwischenfrucht NUR auf Ackerfläche überhaupt möglich ist (laut Daten)? D.h. auf anderen Flächennutzungsarten muss ich das gar nicht erst einblenden - da gibt es dann nur Hauptfrüchte?

**Comment by arnold-pichler** [comment]
@simonkriegnerschramml - und noch eine Frage:

![image](https://github.com/user-attachments/assets/3c634aaf-87c8-4376-863c-30707bd4dbe4)

Sehe ich das jetzt richtig: Eine Zwischenfrucht (genutzt oder ungenutzt) ist nur als erste Frucht im Jahr möglich, vor den Hauptfrüchten. Danach gibt es NUR MEHR Hauptfrüchte und die beinhalten NICHT die Auswahl einer Zwischenfrucht. D.h. es gibt zwischen den Hauptfrüchten keine Möglichkeit einer Zwischenfrucht?

**Comment by arnold-pichler** [comment]
> Exakt und eben vorfrüchte

Ja, aber die ist dann quasi bei der nachfolgenden Ausaat-Serie als Vorfrucht anzugeben, nicht am Ende. D.h. wenn er am Ende von 2024 noch eine Frucht über den Winter aussät, ist das 2025 die Vorfrucht.

**Comment by simonkriegnerschramml** [comment]
Nein. Die Vorfrucht wurde noch zur ernte gebracht.die letzte Hauptfrucht eines Wirtschaftsjahres ist die Vorfrucht für das nächste Wirtschaftsjahr. Eine im Herbst 2024 angebaute Kultur, die im Kalenderjahr 2025 geerntet wird (bspw. Winterweizen) gehört schon als Hauptkultur in das Wirtschaftsjahr 2025.

LG
Simon


Disclaimer und Datenschutz der Landwirtschaftskammer Oberösterreich
Diese Nachricht ist vertraulich. Im Falle einer Fehlleitung, verständigen Sie bitte den Absender und löschen Sie diese Nachricht und alle Anhänge. Sollten Sie nicht der beabsichtigte Adressat sein, ist jede Offenlegung, Weiterleitung oder sonstige Verwendung dieser Information nicht gestattet. Soweit gesetzlich zulässig, schließt der Absender jede Haftung für Schäden aus Übertragungsfehlern, Viren, fremden Einfluss, Verzögerungen und dergleichen aus. Nähere Informationen zum Datenschutz finden Sie unter:  www.ooe.lko.at/datenschutz<http://www.ooe.lko.at/datenschutz>
Am 09.08.2024 12:25 schrieb Arnold Pichler ***@***.***>:

Exakt und eben vorfrüchte

Ja, aber die ist dann quasi bei der nachfolgenden Ausaat-Serie als Vorfrucht anzugeben, nicht am Ende. D.h. wenn er am Ende von 2024 noch eine Frucht über den Winter aussät, ist das 2025 die Vorfrucht.

**Comment by arnold-pichler** [comment]
Hmm.. OK - das wäre dann eine Verknüpfung der Datensätze am Schlag. Denn ich muss dann z.B. auf einem Schlag bei einem Datensatz für 2025 schauen, ob es auch einen Datensatz für 2024 gibt und muss ihn dann noch fragen, ob die letzte Ernte 2024 die Vorfrucht von 2025 ist? Aber da reden wir noch, sonst wird das ein Endlos-Issue.

**Comment by arnold-pichler** [comment]
@simonkriegnerschramml - Frage zu "Grünbrache":

Da gibt es ja keine Ertragslage und auch keine Ernte, wie soll ich damit umgehen?

**Comment by simonkriegnerschramml** [comment]
Hallo Arnold,

anbei schicke ich einmal einen Versuch der Systematisierung zur Berechnung und Bewertung der Vorfruchtwerte, N-Saldo gem. BAS16 und dem manuell eingetragenen Nmin durch. Es ist sehr komplex und umfangreich geworden, weshalb ich dir auch noch einen Text verfasse, damit es für dich leichter verständlich wird. Die Systematisierung soll alle technisch möglichen Konstellationen abdecken, daher der Umfang.

Die Datei enthält die Systematik von Vorfrucht zu genutzter Zwischenfrucht, genutzter Zwischenfrucht zu Hauptfrucht 1 und Vorfrucht bis Hauptfrucht 1 (inkl. ungenutzter Zwischenfrucht).

Zur Erklärung:
genutzte Zwischenfrüchte müssen wie eigene Hauptfrüchte gerechnet werden, da diese einen eigenständigen Nährstoffbedarf aufweisen und daher bilanziert werden.
Ungenutzte Zwischenfrüchte hingegen sind mehr oder weniger ein Zwischenstück, welche keinen eigenen Bedarf an Nährstoffen aufweisen und daher als Durchlaufposten gerechnet werden. Sie reduzieren aber den N-Saldo (aber nur BAS16, welcher manuell eingetragen werden muss) ein weiteres Mal um den Reduktionsfaktor (BAS10).
In unserem Fall kann nur eine Zwischenfrucht gebucht werden und es handelt sich dann entweder um eine genutzte oder eben eine ungenutzte Zwischenfrucht. Daher wurde die ungenutzte Zwischenfrucht in der durchgehenden Bewertung von Vorfrucht bis hin zur Hauptfrucht 1 integriert.

[Vorfruchtwerte, N-Saldo und Nmin Zusammenspiel.xlsx](https://github.com/user-attachments/files/16694355/Vorfruchtwerte.N-Saldo.und.Nmin.Zusammenspiel.xlsx)


LG
Simon

**Comment by simonkriegnerschramml** [comment]
> Hallo Arnold,
> 
> anbei schicke ich einmal einen Versuch der Systematisierung zur Berechnung und Bewertung der Vorfruchtwerte, N-Saldo gem. BAS16 und dem manuell eingetragenen Nmin durch. Es ist sehr komplex und umfangreich geworden, weshalb ich dir auch noch einen Text verfasse, damit es für dich leichter verständlich wird. Die Systematisierung soll alle technisch möglichen Konstellationen abdecken, daher der Umfang.
> 
> Die Datei enthält die Systematik von Vorfrucht zu genutzter Zwischenfrucht, genutzter Zwischenfrucht zu Hauptfrucht 1 und Vorfrucht bis Hauptfrucht 1 (inkl. ungenutzter Zwischenfrucht).
> 
> Zur Erklärung: genutzte Zwischenfrüchte müssen wie eigene Hauptfrüchte gerechnet werden, da diese einen eigenständigen Nährstoffbedarf aufweisen und daher bilanziert werden. Ungenutzte Zwischenfrüchte hingegen sind mehr oder weniger ein Zwischenstück, welche keinen eigenen Bedarf an Nährstoffen aufweisen und daher als Durchlaufposten gerechnet werden. Sie reduzieren aber den N-Saldo (aber nur BAS16, welcher manuell eingetragen werden muss) ein weiteres Mal um den Reduktionsfaktor (BAS10). In unserem Fall kann nur eine Zwischenfrucht gebucht werden und es handelt sich dann entweder um eine genutzte oder eben eine ungenutzte Zwischenfrucht. Daher wurde die ungenutzte Zwischenfrucht in der durchgehenden Bewertung von Vorfrucht bis hin zur Hauptfrucht 1 integriert.
> 
> [Vorfruchtwerte, N-Saldo und Nmin Zusammenspiel.xlsx](https://github.com/user-attachments/files/16694355/Vorfruchtwerte.N-Saldo.und.Nmin.Zusammenspiel.xlsx)
> 
> LG Simon

Hallo Arnold

Anbei nun der erste Teil des Textes zur Erläuterung des Umfangreichen Excel Files. Darin enthalten sind die Begrifflichkeiten Vorfrucht und Vorfruchtwert, genutzte Zwischenfrucht, ungenutzte Zwischenfrucht und Hauptfrucht 1 mit der Differenzierung der Vorfruchtwerte aufgrund Gemüsekulturen und Nicht Gemüsekulturen, sowie der zu Gemüsekulturen gehörende Nmin.

Dieses File wird noch ergänzt. Es fehlen noch der N-Saldo und der Übergang von Hauptfrucht 1 auf Hauptfrucht 2 (usw.).

[Zusammenspiel Vorfrucht,ZWF,gen.ZWF, HF1, NSaldo.docx](https://github.com/user-attachments/files/16728496/Zusammenspiel.Vorfrucht.ZWF.gen.ZWF.HF1.NSaldo.docx)

LG
Simon

**Comment by simonkriegnerschramml** [comment]
Mir ist noch etwas wichtiges im Zuge der Spezifikation und Testung eines anderen Aufzeichnungsprogramms von eingefallen. genutzte Zwischenfrüchte müssten eigentlich schon geerntet werden. Wir haben ansonsten keinen Anhaltspunkt welche Düngung nun zur genutzten Zwischenfrucht gehört und welche nicht.

LG
Simon

**Comment by arnold-pichler** [comment]
> Mir ist noch etwas wichtiges im Zuge der Spezifikation und Testung eines anderen Aufzeichnungsprogramms von eingefallen. genutzte Zwischenfrüchte müssten eigentlich schon geerntet werden. Wir haben ansonsten keinen Anhaltspunkt welche Düngung nun zur genutzten Zwischenfrucht gehört und welche nicht.
> 
> LG Simon

D.h. wenn hier eine genutzte Frucht eingetragten wird:

![image](https://github.com/user-attachments/assets/17581d4f-8f34-4113-890c-9d07d2e0416f)

Dann muss auch eine Ernte abgefragt werden? Und die Düngung in jedem Fall?

**Comment by simonkriegnerschramml** [comment]
Hallo Arnold,

Es müsste zumindest eine Düngung geben. Aber das könnten wir dann auch gleich für ungenutzte Zwischenfrüchte zulassen. Wir müssen das dann eben anders in der Bilanz, Düngeobergrenzen und dem N-Saldo berechnen. Ernte muss es nicht zwingend geben.

Ich wäre dafür die Düngung in beiden Fällen zuzulassen.

Ich sehe gerade, dass es hier noch ein Missverständnis gibt. Futter Zwischenfrucht ist eine Futternutzung und dies bedeutet, dass es sich um eine genutzte Zwischenfrucht handelt. Wir müssen das unterscheiden. Mit dem Ausdruck "Genutzt / ungenutzt" geht das zu wenig ins Detail. Außer wir würden anhand der Kultur, welche gewählt wird, unterscheiden ob es sich um eine genutzte oder eben ungenutzte Zwischenfrucht handelt. 

Es gibt zwei Wege, diesen Schritt umzusetzen:
1.) Die Auswahl der "Art der Zwischenfrucht" völlig weglassen und anhand der ID unterscheiden, wie im Anschluss die Nährstoffmengen weiter verrechnet werden. Das gibt uns in weiterer Folge auch die Möglichkeit die Herbstdüngung zu prüfen und einen Hinweis auszugeben.

2.) Drop Down "Auswahl bei Art der Zwischenfrucht" ungenutzt oder genutzt und die Kulturauswahl entsprechend dieser Auswahl einschränken.

Mir persönlich gefällt die erste Variante besser und diese schränkt uns auch nicht zu sehr ein. Es wirkt eleganter und er User hat einen Punkt weniger auszuwählen.

Auf alle Fälle sind folgende Kulturenungenutzte Zwischenfrüchte:

1.1.600 Zwischenfrucht ungenutzt ohne Legum.
1.1.610 Zwischenfrucht ungenutzt (1 - 60% Legum.)
1.1.620 Zwischenfrucht ungenutzt (> 60% Legum.)

und folgende Kulturen genutzte Zwischenfrüchte:

1.1.630 Futter-Zwischenfrucht ohne Legum.
1.1.640 Futter-Zwischenfrucht (1 - 60% Legum.)
1.1.650 Futter-Zwischenfrucht (> 60% Legum.)

LG
Simon

**Comment by simonkriegnerschramml** [comment]
> > Hallo Arnold,
> > anbei schicke ich einmal einen Versuch der Systematisierung zur Berechnung und Bewertung der Vorfruchtwerte, N-Saldo gem. BAS16 und dem manuell eingetragenen Nmin durch. Es ist sehr komplex und umfangreich geworden, weshalb ich dir auch noch einen Text verfasse, damit es für dich leichter verständlich wird. Die Systematisierung soll alle technisch möglichen Konstellationen abdecken, daher der Umfang.
> > Die Datei enthält die Systematik von Vorfrucht zu genutzter Zwischenfrucht, genutzter Zwischenfrucht zu Hauptfrucht 1 und Vorfrucht bis Hauptfrucht 1 (inkl. ungenutzter Zwischenfrucht).
> > Zur Erklärung: genutzte Zwischenfrüchte müssen wie eigene Hauptfrüchte gerechnet werden, da diese einen eigenständigen Nährstoffbedarf aufweisen und daher bilanziert werden. Ungenutzte Zwischenfrüchte hingegen sind mehr oder weniger ein Zwischenstück, welche keinen eigenen Bedarf an Nährstoffen aufweisen und daher als Durchlaufposten gerechnet werden. Sie reduzieren aber den N-Saldo (aber nur BAS16, welcher manuell eingetragen werden muss) ein weiteres Mal um den Reduktionsfaktor (BAS10). In unserem Fall kann nur eine Zwischenfrucht gebucht werden und es handelt sich dann entweder um eine genutzte oder eben eine ungenutzte Zwischenfrucht. Daher wurde die ungenutzte Zwischenfrucht in der durchgehenden Bewertung von Vorfrucht bis hin zur Hauptfrucht 1 integriert.
> > [Vorfruchtwerte, N-Saldo und Nmin Zusammenspiel.xlsx](https://github.com/user-attachments/files/16694355/Vorfruchtwerte.N-Saldo.und.Nmin.Zusammenspiel.xlsx)
> > LG Simon
> 
> Hallo Arnold
> 
> Anbei nun der erste Teil des Textes zur Erläuterung des Umfangreichen Excel Files. Darin enthalten sind die Begrifflichkeiten Vorfrucht und Vorfruchtwert, genutzte Zwischenfrucht, ungenutzte Zwischenfrucht und Hauptfrucht 1 mit der Differenzierung der Vorfruchtwerte aufgrund Gemüsekulturen und Nicht Gemüsekulturen, sowie der zu Gemüsekulturen gehörende Nmin.
> 
> Dieses File wird noch ergänzt. Es fehlen noch der N-Saldo und der Übergang von Hauptfrucht 1 auf Hauptfrucht 2 (usw.).
> 
> [Zusammenspiel Vorfrucht,ZWF,gen.ZWF, HF1, NSaldo.docx](https://github.com/user-attachments/files/16728496/Zusammenspiel.Vorfrucht.ZWF.gen.ZWF.HF1.NSaldo.docx)
> 
> LG Simon

Hallo Arnold,

Ich habe nun den N-Saldo und die Folge von HF1 zu HF2 und folgende in das Word eingebaut. Das Excel erhältst du auch zeitnahe.
[Zusammenspiel Vorfrucht,ZWF,gen.ZWF, HF1, NSaldo.docx](https://github.com/user-attachments/files/16836599/Zusammenspiel.Vorfrucht.ZWF.gen.ZWF.HF1.NSaldo.docx)


LG
Simon

**Comment by simonkriegnerschramml** [comment]
Anbei nun das Excel File und das Docx.
[Vorfruchtwerte, N-Saldo und Nmin Zusammenspiel.xlsx](https://github.com/user-attachments/files/16909456/Vorfruchtwerte.N-Saldo.und.Nmin.Zusammenspiel.xlsx)
[Zusammenspiel Vorfrucht,ZWF,gen.ZWF, HF1, NSaldo.docx](https://github.com/user-attachments/files/16909457/Zusammenspiel.Vorfrucht.ZWF.gen.ZWF.HF1.NSaldo.docx)

**Comment by simonkriegnerschramml** [comment]
Und die Berechnung bzw. Bestimmung der Entzugszahlen für die Nährstoffe Stickstoff (N), Phosphor (P) und Kalium (K).
[Nährstoffentzüge N, P und K.xlsx](https://github.com/user-attachments/files/16909502/Nahrstoffentzuge.N.P.und.K.xlsx)

Dies ist der Wert der für die Bilanzierung der Düngehöhe und den Vorfruchtwerten etc. gegenübergestellt wird. Für die Berechnung des N-Saldo dient das jeweilige Ergebnis als Entscheidungsgrundlage und Berechnungsgrundlage.

LG
Simon

**Comment by simonkriegnerschramml** [comment]
So und nun noch das Excelfile für die Nährstoffbilanzierung und den Stickstoffsaldo in Verbindung mit Gemüsekulturen unter Berücksichtigung genutzter Zwischenfrüchten und ungenutzter Zwischenfrüchte. 
In diesem File sind alle Zusammenhänge und Kriterienkombinationen abgebildet, die für die Berechnung der Düngeobergrenze der Kulturen benötigt werden. Auch sind die Berechnungen für die Nährstoffbilanz enthalten.

[N-Bilanz, P-Bilanz, K-Bilanz, N-Saldo, Nmin, Vorfruchtwert.xlsx](https://github.com/user-attachments/files/16970797/N-Bilanz.P-Bilanz.K-Bilanz.N-Saldo.Nmin.Vorfruchtwert.xlsx)
[N-Bilanz, P-Bilanz, K-Bilanz, N-Saldo, Nmin, Vorfruchtwert.xlsx](https://github.com/user-attachments/files/16970797/N-Bilanz.P-Bilanz.K-Bilanz.N-Saldo.Nmin.Vorfruchtwert.xlsx)



LG
Simon

**Comment by arnold-pichler** [comment]
sollte mittlerweile alles implementiert sein.
