### ISSUE TITLE
Systematisierung Input Output V1 (AP) ist auf der NextCloud

### ISSUE THREAD

**Issue by simonkriegnerschramml** [w3geo/bml-fast#3]
Hallo zusammen,

Ich habe einen ersten Entwurf bezüglich der Systematik auf die Next Cloud gespielt.

Die Stammdatengrundlagen müssen nach eingehender Diskussion und aufgrund von Begutachtungsentwürfen (Nitrat Aktionsprogramm VO), sowie Richtlinienpublikation (sachgerechte Düngung im Feldgemüsebau und Addendum zu SGD 8 - Ackerbau und Grünland) überarbeitet werden. Ich bin gerade dabei unsere Stammdaten für den LK Düngerechner, den ÖDüPlan Plus, die AMA Düngewerttabelle und eben die FaST Tool Stammdaten zu überarbeiten und zu aktualisieren.

LG
Simon

**Comment by simonkriegnerschramml** [comment]
Die Datei "Systematisierung Input Output V2 (AP).xlsx" wurde auf die Next Cloud gestellt. Es gab in den Basis Parametern noch Ergänzungen.

LG
Simon

**Comment by arnold-pichler** [comment]
Danke! Schau ich mir morgen an, wir sind heute auswärts bei Terminen. LG
