### ISSUE TITLE
Angabe von Dünger

### ISSUE THREAD

**Issue by arnold-pichler** [w3geo/bml-fast#31]
@simonkriegnerschramml :

- Die Menge des Düngers muss ja angegeben werden, passiert das in L oder T ?
- Bei allem, was kein Handelsdünger ist, müssen die Werte für N(%), P2O5(%) und K2O(%) händisch eingegeben werden, oder?
- Sollen diese Werte bei Handelsdünger gesperrt werden (also nicht vom User veränderbar sein)?

**Comment by simonkriegnerschramml** [comment]
> @simonkriegnerschramml :
> 
> * Die Menge des Düngers muss ja angegeben werden, passiert das in L oder T ?
Das ist eine Grundsatz Entscheidung. Die Einheit ist in den Stammdaten vorgegeben. Die % Werte sind derzeit alle auf Masseprozent und nicht in Volumsprozent angeführt. Das können wir umsetzen, wie wir wollen, da die Hersteller die Nährstoffgehalte in den allermeisten Fällen in Masseprozent anführen.

> * Bei allem, was kein Handelsdünger ist, müssen die Werte für N(%), P2O5(%) und K2O(%) händisch eingegeben werden, oder?
Korrekt. Genauso war das gedacht.

> * Sollen diese Werte bei Handelsdünger gesperrt werden (also nicht vom User veränderbar sein)?
Ja. Wenn der User denkt hier andere Werte eintragen zu müssen, kann er einen "eigenen Dünger" eingeben.

LG
Simon

**Comment by arnold-pichler** [comment]
Haben wir heute geklärt, Danke
