### ISSUE TITLE
Bodenarten - Vorauswahl je Datenlage im Agraratlas

### ISSUE THREAD

**Issue by simonkriegnerschramml** [w3geo/bml-fast#35]
Hallo Arnold,

Wenn ein Schlag als überwiegend (>50%) "schwer" gekennzeichnet ist, dann soll die Bodenart "sL - sandiger Lehm" angeführt werden.
Umgekehrt soll die Bodenart "lS - lehmiger Sand" angezeigt werden.

Die Bodenart muss aber weiterhin frei ausgewählt werden können.

Anbei sende ich auch noch die Datei mit den Bodenarten als Überblick.
[Bodenarten.xlsx](https://github.com/user-attachments/files/16658660/Bodenarten.xlsx)

LG
Simon

**Comment by arnold-pichler** [comment]
@ahocevar - die Daten brauche ich noch in den Schlaginfos.

**Comment by ahocevar** [comment]
`schwere_boeden` hinzugefügt in  #45.

**Comment by arnold-pichler** [comment]
Umgesetzt, im nächsten Update enthalten.
