### ISSUE TITLE
Einheiten für Düngerkategorien Masse und Volumen

### ISSUE THREAD

**Issue by simonkriegnerschramml** [w3geo/bml-fast#36]
Hallo Arnold,

wie heute besprochen kommt hier die Kategorisierung der Einheit der Hauptkategorien der Dünger:

- Handelsdünger: kg oder l
- Wirtschaftsdünger: m3
- Sekundärrohstoffe: m3 oder Tonnen - der User muss das wissen und es kommt auf den Rohstoff an
                                   daher wird hier die Angabe "m3 | t" bevorzugt. Das haben wir in anderen Programmen auch so umgesetzt.
- eigene Handelsdünger: kg oder l

LG
Simon

**Comment by arnold-pichler** [comment]
Umgesetzt, im nächsten Update enthalten.
