### ISSUE TITLE
Problematik Bereichsangaben, Beispielfälle

### ISSUE THREAD

**Issue by arnold-pichler** [w3geo/bml-fast#39]
@simonkriegnerschramml : 

Wie schon im Stammdaten-Issue beschrieben, hier an einigen Fällen festgemacht. Ich habe noch ein Problem mit den Bereichsangaben für die Ertragslagen. Es geht mir vor allem darum, dass ich ja dem Benutzer die Ertragslage und in Klammer die Bereichsangabe anzeige, das sollte dann aber auch plausibel sein. Ich beziehe mich dabei auf die "Vorschrift" aus dem Anzeige-Systematisierungs-Excel:

![image](https://github.com/user-attachments/assets/f1909758-999a-43d0-9b1c-0fe11e1a10ae)

#### Beispiel 1, ID 1.1.1040
- Wechselwiese einjährig - 6 Nutzungen, gräserreich (<40% Legum.)
- "EL niedrig Bereich" = "≥ 12,5 t" , "EL niedrig t / m3 ab" = "0"
- "EL mittel Bereich" = "≥ 12,5 t" , "EL mittel t / m3 ab" = ""
- "EL hoch Bereich" = "≥ 12,5 t" , "EL hoch t / m3 ab" = ""

Fragen:
- Was ist definierend für die Anzahl der möglichen Ertragslagen? Nur das "EL XXX t / m3 ab" Bereich, korrekt?
- Das bedeutet: Hier gibt es eigentlich nur die Ertragslage "niedrig"?
- D.h. das wäre Fall 5 bezugnehmend auf die Excel-Vorschrift? Dann würde die Anzeige aber sein "niedrig (≥ 12,5 t)" - das finde ich verwirrend, zumal er gar nichts ändern kann. D.h. den Bereich sollte man dann weglassen.
- Diese Frage stellt sich für mich für alle Kulturen, wo schon im Bereich für "niedrig" eine "≥" Angabe steht

#### Beispiele 2, ID 1.1.2410 und ID 1.1.2300
- Spargel, Rhabarber jeweils Pflanzjahr
- Alle Bereiche sind "", "EL niedrig t / m3 ab" = "0" , die anderen sind "".

Das ist gleichsam des "Gegenmodell", hier gibt es auch nur einen Bereich und dafür keine Bereichsbeschreibungen - das wäre dann eigentlich genau korrekt so. Allerdings: Wird das im Pflanzjahr überhaupt geerntet?

#### Beispiel 3, ID 1.1.2860 und andere Sonderkulturen
- Brombeere
- "EL niedrig Bereich" = "" , "EL niedrig t / m3 ab" = ""
- "EL mittel Bereich" = "8,0 - 14,0 t" , "EL mittel t / m3 ab" = "0"
- "EL hoch Bereich" = "> 14,0 t" , "EL hoch t / m3 ab" = ""

Fragen:
- Hier ist der Bereich ab "mittel", der ist aber schon ab 0 Tonnen, in der Beschreibung steht dann aber "8 - 14 Tonnen", das passt nicht zusammen
- Der Bereich hoch wäre ab 14 Tonnen, das Feld "EL hoch t / m3 ab" ist aber nicht definiert und dadurch ist der ganze Bereich eigentlich gar nicht relevant, d.h. es gibt nur Mittel für die Brombeere?

Das sind jetzt einmal drei Fälle, die mir während der Umsetzung aufgefallen sind, sie stehen exemplarisch jeweils für eine bestimmte Klasse an Kulturen, wo das dann ähnlich eingetragen ist.

**Comment by arnold-pichler** [comment]
PS: Wir müssen das auch nicht hier im Issue abhandeln, sondern können eine ViKo machen...

**Comment by simonkriegnerschramml** [comment]
> PS: Wir müssen das auch nicht hier im Issue abhandeln, sondern können eine ViKo machen...

Wann wäre es für dich passend?

LG
Simon

**Comment by arnold-pichler** [comment]
> Wann wäre es für dich passend?

Morgen bin ich schon ziemlich eingeteilt. Evtl. Mittwoch gleich in der Früh? Oder Donnerstag, auch gleich in der Früh?

**Comment by simonkriegnerschramml** [comment]
Mittwoch in der Früh würde mir besser passen. Ich schicke dir einen Link. ab Wann geht es bei dir? 

LG
Simon

**Comment by arnold-pichler** [comment]
Bin ab spätestens 08h im Einsatz!

**Comment by simonkriegnerschramml** [comment]
> @simonkriegnerschramml :
> 
> Wie schon im Stammdaten-Issue beschrieben, hier an einigen Fällen festgemacht. Ich habe noch ein Problem mit den Bereichsangaben für die Ertragslagen. Es geht mir vor allem darum, dass ich ja dem Benutzer die Ertragslage und in Klammer die Bereichsangabe anzeige, das sollte dann aber auch plausibel sein. Ich beziehe mich dabei auf die "Vorschrift" aus dem Anzeige-Systematisierungs-Excel:
> 
> ![image](https://private-user-images.githubusercontent.com/36012148/359107496-f1909758-999a-43d0-9b1c-0fe11e1a10ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNzQ4NTAsIm5iZiI6MTcyNDA3NDU1MCwicGF0aCI6Ii8zNjAxMjE0OC8zNTkxMDc0OTYtZjE5MDk3NTgtOTk5YS00M2QwLTliMWMtMGZlMTFlMWExMGFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDEzMzU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwMmYxNjQyM2E2NzBiMTc4YWQ0YjcwYjI3MmQ5NjFlNTU0YTE0NjgxNWI5OWZlMzc5OGI0Mjg3NWJmNmI4NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GQDWuyN7n-iQvQkuaxzY4Zmg--6hXf-nx6P1Aiwi1s4)
> 
> #### Beispiel 1, ID 1.1.1040
> * Wechselwiese einjährig - 6 Nutzungen, gräserreich (<40% Legum.)
> * "EL niedrig Bereich" = "≥ 12,5 t" , "EL niedrig t / m3 ab" = "0"
> * "EL mittel Bereich" = "≥ 12,5 t" , "EL mittel t / m3 ab" = ""
> * "EL hoch Bereich" = "≥ 12,5 t" , "EL hoch t / m3 ab" = ""
> 
> Fragen:
> 
> * Was ist definierend für die Anzahl der möglichen Ertragslagen? Nur das "EL XXX t / m3 ab" Bereich, korrekt?
> * Das bedeutet: Hier gibt es eigentlich nur die Ertragslage "niedrig"?
> * D.h. das wäre Fall 5 bezugnehmend auf die Excel-Vorschrift? Dann würde die Anzeige aber sein "niedrig (≥ 12,5 t)" - das finde ich verwirrend, zumal er gar nichts ändern kann. D.h. den Bereich sollte man dann weglassen.
> * Diese Frage stellt sich für mich für alle Kulturen, wo schon im Bereich für "niedrig" eine "≥" Angabe steht
> 
> #### Beispiele 2, ID 1.1.2410 und ID 1.1.2300
> * Spargel, Rhabarber jeweils Pflanzjahr
> * Alle Bereiche sind "", "EL niedrig t / m3 ab" = "0" , die anderen sind "".
> 
> Das ist gleichsam des "Gegenmodell", hier gibt es auch nur einen Bereich und dafür keine Bereichsbeschreibungen - das wäre dann eigentlich genau korrekt so. Allerdings: Wird das im Pflanzjahr überhaupt geerntet?
> 
> #### Beispiel 3, ID 1.1.2860 und andere Sonderkulturen
> * Brombeere
> * "EL niedrig Bereich" = "" , "EL niedrig t / m3 ab" = ""
> * "EL mittel Bereich" = "8,0 - 14,0 t" , "EL mittel t / m3 ab" = "0"
> * "EL hoch Bereich" = "> 14,0 t" , "EL hoch t / m3 ab" = ""
> 
> Fragen:
> 
> * Hier ist der Bereich ab "mittel", der ist aber schon ab 0 Tonnen, in der Beschreibung steht dann aber "8 - 14 Tonnen", das passt nicht zusammen
> * Der Bereich hoch wäre ab 14 Tonnen, das Feld "EL hoch t / m3 ab" ist aber nicht definiert und dadurch ist der ganze Bereich eigentlich gar nicht relevant, d.h. es gibt nur Mittel für die Brombeere?
> 
> Das sind jetzt einmal drei Fälle, die mir während der Umsetzung aufgefallen sind, sie stehen exemplarisch jeweils für eine bestimmte Klasse an Kulturen, wo das dann ähnlich eingetragen ist.

Ich habe nun die Ertragslagen so angepasst, dass es mit deinem System funktionieren sollte. Ich habe das ursprünglich glaube ich falsch verstanden. Bitte um Rückmeldung bzw. dann eben um Fragen am Mittwoch Vormittag.

LG
Simon

**Comment by arnold-pichler** [comment]
Das ist jetzt korrekt in den Stammdaten.
