### ISSUE TITLE
Eingabeprozedere Nmin Werte für Gemüsekulturen

### ISSUE THREAD

**Issue by simonkriegnerschramml** [w3geo/bml-fast#4]
Hallo zusammen,

Ich bin gerade dabei das Eingabeprozedere der Kulturen zu überarbeiten. Wie sollen wir die Möglichkeit der Eingabe eines Nmin Wertes in der Eingabemaske umsetzen bzw. sollen wir diesen Wert nach der Eingabe der Kultur auch in der Haupttabelle anzeigen, da ansonsten der Zusammenhang zu den berechneten Werten in der Haupttabelle nicht mehr unmittelbar gegeben ist und erst die Aussaat der Hauptfrucht erneut editiert werden müsste, um festzustellen, dass ein Nmin Wert eingetragen wurde.

LG
Simon

**Comment by arnold-pichler** [comment]
@simonkriegnerschramml - können wir evtl. morgen (Mittwoch) oder übermorgen (Donnerstag) kurz telefonieren / ViKo machen, damit ich das verstehe? Bevor hier 1000x hin und her schreiben... Habe dann auch wg. der Herbsdüngung (siehe Email) noch eine Frage. LG

**Comment by simonkriegnerschramml** [comment]
> @simonkriegnerschramml - können wir evtl. morgen (Mittwoch) oder übermorgen (Donnerstag) kurz telefonieren / ViKo machen, damit ich das verstehe? Bevor hier 1000x hin und her schreiben... Habe dann auch wg. der Herbsdüngung (siehe Email) noch eine Frage. LG

Sehr gerne, jederzeit. Morgen wäre mir am liebsten. Meine Telefonnummer: 05069021563

LG
Simon

**Comment by arnold-pichler** [comment]
Ja passt, irgend eine bevozugte Zeit? Bin normalerweise spätestens ab 07h im Büro...

**Comment by simonkriegnerschramml** [comment]
> Ja passt, irgend eine bevozugte Zeit? Bin normalerweise spätestens ab 07h im Büro...

Nein, Ich bin ab halb 8 erreichbar. :)

**Comment by simonkriegnerschramml** [comment]
> Ja passt, irgend eine bevozugte Zeit? Bin normalerweise spätestens ab 07h im Büro...

Boden.Wasser.Schutz.Beratung LK OOE lädt Sie zu einem geplanten Zoom-Meeting ein.

Thema: FaST Tool Herbstdüngethematik und Stammdaten
Zeit: 17.Apr. 2024 08:00 Wien

Beitreten Zoom Meeting
https://us06web.zoom.us/j/89270670144?pwd=kONKG3L6jOghJPKXgv0mWup5sYbgRn.1

Meeting-ID: 892 7067 0144
Kenncode: BWSB
Meeting-ID: 892 7067 0144
Kenncode: 407029

Ortseinwahl suchen: https://us06web.zoom.us/u/kdZ7j38Uds
