### ISSUE TITLE
Fragen und Lösungen aus Videokonferenz 2024-08-19

### ISSUE THREAD

**Issue by arnold-pichler** [w3geo/bml-fast#40]
- Pflichtfelder - siehe Issue https://github.com/w3geo/bml-fast/issues/30
   - Live Überprüfung.
   - Anzeigen, dass keine Berechnung möglich ist, fehlende Felder markieren
   - Aber keine generelle Markierung von Pflichtfeldern
   - Felder, die nicht ausgefüllt sind, aber nicht relevant sind (z.B. eine Hauptkultur "Keine") werden einfach gelöscht beim Speichern

- Ackerzahl
   - Mind. 30 als Default
 
- Vorfrucht, wie genau muss die angegeben werden?
  - siehe https://github.com/w3geo/bml-fast/issues/28#issuecomment-2277833458
  - Aktuelle Darstellung ist ausreichend, aber KEINE FILTER nach Feldnutzungsart

- Grünbrache, Kulturen ohne Ernte, z.B. 1.1.1490
   - Müssen eingetragen werden können, aber teilweise keine Düngung & kein Ertrag
   - wird von Simon noch in der Spalte "Ertragserfassung" kodiert

- Sollen bei ausgewählten Handelsdüngern die Mineralstoff-Felder editierbar bleiben?
   - Nein , sperren! Sonst "Eigene Handelsdünger"

- Sortierung der Dropdowns? Wie in Excel (in Hand von AG), oder...? Alphabetisch?
   - Sortierung aus Excel
   - "Bitte wählen" bzw. "Keine" nach vorn (erstes Element)

- Benennung in der Liste der gespeicherten Einträge?
   - Schlagnummer aus Schlag-Info (Inspire-ID) ?
   - Oder: Wenn Feldstück / Schlagnummer nicht gegeben - evtl. "ohne Namen" oder ähnlicher Default

**Comment by simonkriegnerschramml** [comment]
Hallo Arnold,

Mir ist noch was aufgefallen. Die Einschränkung bezüglich Ackerzahl existiert nur bei der Flächennutzung "Acker" bzw. "Ackerland". Daher bitte dieses Feld nur anzeigen, wenn es sich um die Nutzungsart Acker handelt. Auch die Einschränkung der Ertragslage erfolgt nur bei der Nutzungsart Acker.

Wenn nichts ausgefüllt wird bitte folgenden Wert als Standardwert setzen:
Defaultwert: ">30"

LG
Simon

**Comment by arnold-pichler** [comment]
> Mir ist noch was aufgefallen. Die Einschränkung bezüglich Ackerzahl existiert nur bei der Flächennutzung "Acker" bzw. "Ackerland". Daher bitte dieses Feld nur anzeigen, wenn es sich um die Nutzungsart Acker handelt.

Das heißt, dass das Feld "Ackerzahl" überhaupt nur bei Flaechennutzungsart "Acker" angezeigt werden soll?

> Auch die Einschränkung der Ertragslage erfolgt nur bei der Nutzungsart Acker. Wenn nichts ausgefüllt wird bitte folgenden Wert als Standardwert setzen:
Defaultwert: ">30"

Das ist auch aktuell schon so umgesetzt, dass das nur für Acker gilt. Die Einschränkung ist im Exzel definiert mit "< 30", d.h. ein Default-Wert von 30 wäre eigentlich ausreichend, um die Einschränkung auszuschließen. 

Bei allen Nutzungsarten außer Acker wird das Feld ohnehin ignoriert!

**Comment by simonkriegnerschramml** [comment]
> > Mir ist noch was aufgefallen. Die Einschränkung bezüglich Ackerzahl existiert nur bei der Flächennutzung "Acker" bzw. "Ackerland". Daher bitte dieses Feld nur anzeigen, wenn es sich um die Nutzungsart Acker handelt.
> 
> Das heißt, dass das Feld "Ackerzahl" überhaupt nur bei Flaechennutzungsart "Acker" angezeigt werden soll?
> 
> > Auch die Einschränkung der Ertragslage erfolgt nur bei der Nutzungsart Acker. Wenn nichts ausgefüllt wird bitte folgenden Wert als Standardwert setzen:
> > Defaultwert: ">30"
> 
> Das ist auch aktuell schon so umgesetzt, dass das nur für Acker gilt. Die Einschränkung ist im Exzel definiert mit "< 30", d.h. ein Default-Wert von 30 wäre eigentlich ausreichend, um die Einschränkung auszuschließen.
> 
> Bei allen Nutzungsarten außer Acker wird das Feld ohnehin ignoriert!

Ja, mir ging es aber um die visuelle Darstellung. Was steht in der Zelle, wenn hier nichts geändert wird?

LG
Simon

**Comment by arnold-pichler** [comment]
> Ja, mir ging es aber um die visuelle Darstellung. Was steht in der Zelle, wenn hier nichts geändert wird?

Naja, wenn der Default-Wert 30 ist, steht 30 drin. Wie erwähnt, ich kann das Feld bei Nicht-Acker-Schlägen auch  komplett weglassen.

**Comment by simonkriegnerschramml** [comment]
> > Mir ist noch was aufgefallen. Die Einschränkung bezüglich Ackerzahl existiert nur bei der Flächennutzung "Acker" bzw. "Ackerland". Daher bitte dieses Feld nur anzeigen, wenn es sich um die Nutzungsart Acker handelt.
> 
> Das heißt, dass das Feld "Ackerzahl" überhaupt nur bei Flaechennutzungsart "Acker" angezeigt werden soll?
> 
> > Auch die Einschränkung der Ertragslage erfolgt nur bei der Nutzungsart Acker. Wenn nichts ausgefüllt wird bitte folgenden Wert als Standardwert setzen:
> > Defaultwert: ">30"
> 
> Das ist auch aktuell schon so umgesetzt, dass das nur für Acker gilt. Die Einschränkung ist im Exzel definiert mit "< 30", d.h. ein Default-Wert von 30 wäre eigentlich ausreichend, um die Einschränkung auszuschließen.
> 
> Bei allen Nutzungsarten außer Acker wird das Feld ohnehin ignoriert!



> > Ja, mir ging es aber um die visuelle Darstellung. Was steht in der Zelle, wenn hier nichts geändert wird?
> 
> Naja, wenn der Default-Wert 30 ist, steht 30 drin. Wie erwähnt, ich kann das Feld bei Nicht-Acker-Schlägen auch komplett weglassen.

Ja das soll auch weggelassen werden bei Nicht Acker Schlägen. und ist es möglich hier per Default ein ">" Zeichen vor die 30 zu setzen. Nur dass es für den User klar ist, was hier gemeint ist.

LG
Simon

**Comment by arnold-pichler** [comment]
Die Punkte von hier finden sich in https://github.com/w3geo/bml-fast/issues/42 bzw. sind bereits in die kommende Version integriert.
