### ISSUE TITLE
Nmin Eingabe zur Aussaat von Gemüsekulturen

### ISSUE THREAD

**Issue by simonkriegnerschramml** [w3geo/bml-fast#41]
Wie schon in der Spezifikation unter Punkt 5 "Berechnungslogiken Vorfruchtwerte und N-Saldo aus vorangegangenen Wirtschaftsjahren" beschrieben, benötigen wir für die Vorfruchtwerte / Nmin Werte bei Feldgemüse eine gesonderte Eingabevariante. Da wir bis dato ausschließlich die Vorfrucht auswählen, nicht aber den Vorfruchtwert anzeigen ist mir das aufgrund der gestrigen Besprechung wieder in den Sinn gekommen.

Welche Anforderung gibt es für Gemüsekulturen?

Gemüsekulturen muss im Vorfeld der sogenannte Nmin angerechnet werden. Dieser lässt sich nun berechnen, oder aber auch messen. in erstem Fall stehen uns die Stammdaten zur Verfügung in zweitem Fall aber muss es für den User möglich sein einen Wert manuell einzutragen, der den berechneten Wert schlägt. Um die Berechnungen zu vereinfachen, habe ich diese für die unterschiedlichen Anwendungsfälle bereits berechnet, so dass diese nur mehr ausgelesen werden müssen.

Ich werde eine Systematisierung hierzu verfassen, um hier detailliertere Infos geben zu können.

LG
Simon

**Comment by simonkriegnerschramml** [comment]
Machen wir

**Comment by arnold-pichler** [comment]
In der Testversion umgesetzt.
