### ISSUE TITLE
Problem mit Stickstoffentzügen bei WRRL Steiermark

### ISSUE THREAD

**Issue by simonkriegnerschramml** [w3geo/bml-fast#54]
Hallo zusammen,

Diese Frage ergeht in erster Linie an Ludwig und Andi.

Ich habe ein Problem mit der Bestimmung der Stickstoffentzüge, wenn Kulturen mit der Saldierungsart 3 der Spalte "Saldierungsart 1=t/ha; 2=m3/ha;3=kg N/ha;4=Weichweizen; 5=Braugerste;6=Mais;7=EL Auswahl;8=keine Eingabe" bewertet werden. Demnach gilt als Entzugswert je ha, die Düngeobergrenze der erreichten Ertragslage. Nun gibt es aber auch Flächen, die in das Regionalprogramm Graz bis Radkersburg fallen. Hierbei gibt es keine Tonnenbereiche und keine m3 Bereiche, sondern lediglich die Düngeklassen A-F. Das sind gesamt 6 Düngeklassen. Ein Mapping zur NAPV ist also nicht möglich, da diese (mit der Ausnahme des Körnermaises) im Maximum 5 Ertragslagen aufweist. 

Daher die Frage: ist es in eurem Sinne die Entzugszahlen in allen Fällen der Saldierungsart 3 in den Stammdaten gem. der Daten aus der NAPV, SGD, AMA Düngewerttabelle zu bestimmen? Ich wüsste nicht, wie wir das anders lösen könnten.

LG
Simon

**Comment by arnold-pichler** [comment]
@simonkriegnerschramml - ist das schon beantwortet bzw. in die neuen Unterlagen eingeflossen?

**Comment by simonkriegnerschramml** [comment]
Hallo Arnold,

Ich habe bis dato keine Antwort erhalten, daher habe ich diesen Punkt nach bestem Wissen und Gewissen umgesetzt. Nach mehrmaligem Studium der Gesetzeslage lässt sich das auch so interpretieren. Die Entzüge werden einfach gem. NAPV umgesetzt und es gibt keine Sonderbehandlung für die steirischen Sonderfälle. Also endet das Sonderprozedere mit der Bestimmung der Düngeobergrenze für die Region Graz bis Radkersburg. Alle weiteren Schritte sind dann identisch zum Rest von Österreich.

LG
Simon


Disclaimer und Datenschutz der Landwirtschaftskammer Oberösterreich
Diese Nachricht ist vertraulich. Im Falle einer Fehlleitung, verständigen Sie bitte den Absender und löschen Sie diese Nachricht und alle Anhänge. Sollten Sie nicht der beabsichtigte Adressat sein, ist jede Offenlegung, Weiterleitung oder sonstige Verwendung dieser Information nicht gestattet. Soweit gesetzlich zulässig, schließt der Absender jede Haftung für Schäden aus Übertragungsfehlern, Viren, fremden Einfluss, Verzögerungen und dergleichen aus. Nähere Informationen zum Datenschutz finden Sie unter:  www.ooe.lko.at/datenschutz<http://www.ooe.lko.at/datenschutz>
Am 13.09.2024 14:09 schrieb Arnold Pichler ***@***.***>:

@simonkriegnerschramml<https://github.com/simonkriegnerschramml> - ist das schon beantwortet bzw. in die neuen Unterlagen eingeflossen?

**Comment by arnold-pichler** [comment]
Passt, dann schließe ich das einstweilen hier.
