### ISSUE TITLE
Nachkommastellen bei den Flächenangaben auf 4 Stellen einschränken

### ISSUE THREAD

**Issue by simonkriegnerschramml** [w3geo/bml-fast#59]
Hallo Arnold,

Im System sind derzeit Flächenangaben mit einer Vielzahl an Nachkommastellen versehen. Ich schlage daher vor nach demselben Prinzip, wie die AMA vorzugehen. Die AMA rechnet gem. mündlicher Auskunft mit 12 oder 13 Stellen nach dem Komma. Sie schneidet jedoch für den Mehrfachantrag diese Zahl nach der vierten Kommastelle ab. Es wird daher nicht gerundet sondern lediglich bis Stelle 4 angezeigt und danach nicht mehr dargestellt. Im Gegensatz zur AMA sollten wir aber auch mit diesen 4 Kommastellen in die weiteren Berechnungen gehen, da es sonst zu Inkonsistenzen in den Berechnungen kommen kann.

LG
Simon

**Comment by arnold-pichler** [comment]
D.h. generell alle auf max. 4 Kommastellen abschneiden? Alle Flächenangaben aus den Schlag-Infos (also auch Anteile WRRL etc.)?

**Comment by arnold-pichler** [comment]
Fläche wird mit der in Kürze deployten Testversion auf 4 Nachkommastellen abgetrennt!
