### ISSUE TITLE
"Favoriten" in Drop Downs

### ISSUE THREAD

**Issue by arnold-pichler** [w3geo/bml-fast#65]
Nach einem Vorschlag von Ludwig Gerner:

- Es soll eine Art "Favoritenverwaltung" geben. Denn ein Landwirt pflanzt im Normalfall ja nicht zig unterschiedliche Sachen an, sondern immer wieder die gleichen 4,5 Kulturen,
- Die eleganteste Lösung ist, dass Kulturen, die schon einmal verwendet wurden, in der Auswahlliste vorgereiht werden, also ganz oben erscheinen.

**Comment by simonkriegnerschramml** [comment]
> Nach einem Vorschlag von Ludwig Gerner:
> 
> * Es soll eine Art "Favoritenverwaltung" geben. Denn ein Landwirt pflanzt im Normalfall ja nicht zig unterschiedliche Sachen an, sondern immer wieder die gleichen 4,5 Kulturen,
> * Die eleganteste Lösung ist, dass Kulturen, die schon einmal verwendet wurden, in der Auswahlliste vorgereiht werden, also ganz oben erscheinen.

Das ist durchaus sinnhaft.

LG
Simon

**Comment by arnold-pichler** [comment]
Das machen wir am Ende. Ich habe jetzt die Suche mit den Autocompletes etwas optimiert, evtl. genügt das. Kommt mit der nächsten Version.

**Comment by simonkriegnerschramml** [comment]
Das ist toll umgesetzt. Das passt.

LG
Simon
