### ISSUE TITLE
Neues File zur Spezifikation der Eingabemasken und ersten Berechnungsschritten ist auf der NEXT CLOUD

### ISSUE THREAD

**Issue by simonkriegnerschramml** [w3geo/bml-fast#7]
Hallo,

ein neues File zur Spezifikation der Eingabemasken und ersten Berechnungsschritten ist auf der NEXT CLOUD.

https://next.agrarforschung.at/index.php/s/484eRCNmLGipr7E?path=%2FSpezifikationen%2FSpezifikationen%20Textdokumente 

LG
Simon

**Comment by arnold-pichler** [comment]
Danke! Ich war jetzt leider etwas außer Gefecht (unangenehm hartnäckiger Virus). Habe gestern einen ersten "Überflieger" über die Spezifikation v2 gemacht, das schaut schon sehr gut aus. Schaue mir die neue Datei dann heute noch an. Wie schaut es mit den Lookup Dateien aus, die haben wir noch nicht final, wann sind die geplant?

**Comment by simonkriegnerschramml** [comment]
Zur Info. Die Spezifikationsdatei ist nun die aktualisierte und erweiterte Form der Spezifikation. Diese wurde an das Systematik-File angepasst.

**Comment by arnold-pichler** [comment]
Ist mittlerweile in anderen Issues, schließe hier
