### ISSUE TITLE
Berechnung der Bilanz

### ISSUE THREAD

**Issue by arnold-pichler** [w3geo/bml-fast#70]
@simonkriegnerschramml  - Ich sammle hier Fragen, die für die Berechnung der Bilanz auf meiner Seite auftauchen.

**Comment by arnold-pichler** [comment]
Fragen zum Entzug:

![image](https://github.com/user-attachments/assets/5794cfaa-cf26-4972-bd4e-370f7b92a435)

- Welche Werte aus der Kulturen-Tabelle sind damit gemeint?
- Bei Werten, die von der Ertragslage abhängen, ist da die erwartete oder die geerntete gemeint?

**Comment by simonkriegnerschramml** [comment]
> Fragen zum Entzug:
> 
> ![image](https://private-user-images.githubusercontent.com/36012148/370626398-5794cfaa-cf26-4972-bd4e-370f7b92a435.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNTI3NTYsIm5iZiI6MTcyNzI1MjQ1NiwicGF0aCI6Ii8zNjAxMjE0OC8zNzA2MjYzOTgtNTc5NGNmYWEtY2YyNi00OTcyLWJkNGUtMzcwZjdiOTJhNDM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDA4MjA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4ZmQ0MjcxNjQ2OTQ1NTUzZGVjNDU0OWY2OWRiODhjYjY4ZGFmZDMzNDEwMTU0ODY0NTgzNzUzMjUwYmUwYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QKTjEAGrKRqQ1tmgZDVRPdQqBdVm2g_oQs4el5ezdvU)
> 
> * Welche Werte aus der Kulturen-Tabelle sind damit gemeint?
> * Bei Werten, die von der Ertragslage abhängen, ist da die erwartete oder die geerntete gemeint?

Zur Erklärung:

> * Welche Werte aus der Kulturen-Tabelle sind damit gemeint?
Das bezieht sich auf das Prozedere, wie der Wert ausgelesen wird. Dieses Prozedere und der Bezug zur Kulturen-Tabelle ist im File "Nährstoffentzüge N, P und K" beschrieben.  Hier wird lediglich auf dieses Logikfile referenziert.

> * Bei Werten, die von der Ertragslage abhängen, ist da die erwartete oder die geerntete gemeint?
Für Entzüge ist immer der Erreichte Ertrag aus der Maßnahme "Ernte" entscheidend.
Bei P und K ist das immer die erreichte Ertragslage. Bei N ist das von der Kultur abhängig (Entzug je Tonne oder Kubikmeter oder eben erreichte Ertragslage sind hier möglich).

LG
Simon

**Comment by arnold-pichler** [comment]
> Dieses Prozedere und der Bezug zur Kulturen-Tabelle ist im File "Nährstoffentzüge N, P und K" beschrieben.

Welches ist komplett übersehen hatte. SORRY und DANKE! Das macht die Sache schon klarer.

**Comment by arnold-pichler** [comment]
Und woher kommt dieser Wert für die "Bewässerung"? Hat das was mit den "eigenen Handelsdüngern" zu tun?

![image](https://github.com/user-attachments/assets/e5cef65a-4a8f-4c66-a11c-a80bdc266bb2)

**Comment by simonkriegnerschramml** [comment]
> Und woher kommt dieser Wert für die "Bewässerung"? Hat das was mit den "eigenen Handelsdüngern" zu tun?
> 
> ![image](https://private-user-images.githubusercontent.com/36012148/370670658-e5cef65a-4a8f-4c66-a11c-a80bdc266bb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNjA0NjIsIm5iZiI6MTcyNzI2MDE2MiwicGF0aCI6Ii8zNjAxMjE0OC8zNzA2NzA2NTgtZTVjZWY2NWEtNGE4Zi00YzY2LWExMWMtYTgwYmRjMjY2YmIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDEwMjkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4YzUxMDAxNTY5OWFlZjkyNTA4N2JlNzgyYjkzNGEyMTUzN2U1Mjc5NTYzOWZhY2FlMTRmOThhYTJiZWQ5NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t5BCuifcHfvsTKmKva841EIx7m3BA_z6dwV57Nr7-aE)

Nein der Wert entstammt einer Berechnung. Wenn in Summe zu einer Kultur ab 10 kg N aus dem Bewässerungswasser stammen, dann ist der N aus dem Bewässerungswasser zur Düngung hinzuzurechnen.

Ich glaube, dass das Issue mit der Spezifikation gelöscht wurde. Ich kann dieses nicht mehr finden.

[Spezifikation Überarbeitung Sommer 2024_31.07.2024docx.docx](https://github.com/user-attachments/files/17129620/Spezifikation.Uberarbeitung.Sommer.2024_31.07.2024docx.docx)


Unter Punkt 4.4.3.5 wird beschrieben, dass hier die Eingabe der NO3 (die Zahl 3 bitte tief stellen) in "mg / l" eingetragen werden muss.

Ich sehe aber gerade, dass die Formel in der Spezifikation und auch die Tatsache, dass die Mengeneingabe hier auf mm (=Liter / m2) lauten muss, fehlt. Die Mengeneingabe ist vl. verständlicher, wenn wir diese gleich auf Liter je Quadratmeter lauten lassen. Zumindest gab es im Jahr 2023 bei den Anwendern hierzu einige Fragen, was denn nun "mm" bedeuten solle. 

Ich habe die fehlenden Punkte in Punkt 4.4.3.5 ergänzt.

Hier noch der Bildauszug der Formel aus der NAPV (gesetzliche Grundlage für die Stickstoffdüngung in Österreich):
![image](https://github.com/user-attachments/assets/f597ed9a-0277-4c20-8801-9c458462775e)


LG
Simon

**Comment by arnold-pichler** [comment]
> Unter Punkt 4.4.3.5 wird beschrieben, dass hier die Eingabe der NO3 (die Zahl 3 bitte tief stellen) in "mg / l" eingetragen werden muss.

OK, das bedeutet aber, dass wir Bewässerung als zusätzliche Düngungsmethode einführen müssen? Denn wo soll das sonst eingegeben werden?

**Comment by simonkriegnerschramml** [comment]
Also das steht auch in der Spezifikation (auch in der ersten Version schon enthalten gewesen, die in der Cloud des BML hochgeladen wurde), dass die Bewässerung eine eigenständige Düngemethode darstellt. Das war schon Teil des Excelfiles, das ich (leider unnötigerweise) gemacht hatte.

LG
Simon

**Comment by arnold-pichler** [comment]
Stimmt, dort ist sie drinnen. Grundsätzlich zu den Excel-Files: Ich weiß, da ist viel Mehrarbeit für dich drin gewesen, aber ich tu mir sehr viel leichter als mit dem riesigen Word, systematisch die Regeln umzusetzen. Also Danke an dieser Stelle nochmal für die Mühe.

Ich werde die Bewässerung rasch reinnehmen, das ist dann aber "nur" eine weitere Dünge-Art oder soll das ein extra Posten werden? Denn im angesprochenen Word ist sie unter 4.3.2. unter den Düngern drin, ganz am Anfang aber als eigener Punkt:

![image](https://github.com/user-attachments/assets/fcb507bf-e4aa-4bd2-bb47-25591ddcd264)

Mein Vorschlag: Wir machen aus der Überschrift "Düngung" -> "Bewässerung / Düngung" und nehmen sie als Düngung mit rein. Erhoben werden muss dann aber nur der N-Wert, oder? Bei P und K hat das keine Relevanz, soweit ich sehe.

**Comment by simonkriegnerschramml** [comment]
Hallo Arnold,

Bitte das Wording umdrehen. "Düngung / Bewässerung". Da die Bewässerung nur für einen Bruchteil der Landwirte in Österreich von Relevanz ist.

Für die Bewässerung ist nur der Stickstoff relevant. P und K kommen hier in keinem Gesetzestext vor.
Also nur die Angabe des Nitratgehaltes (NO3 je Liter) ist hier wichtig.

LG
Simon

**Comment by simonkriegnerschramml** [comment]
Und ja es ist ein Unterpunkt der Düngung. Also eine weitere Maßnahmenunterart der Düngung, so wie Mineraldünger, etc.

**Comment by arnold-pichler** [comment]
Perfekt. Und bzgl. L / kg und Dichte gilt dann die Formel von oben (  https://github.com/w3geo/bml-fast/issues/70#issuecomment-2373747264 ) , korrekt?

**Comment by simonkriegnerschramml** [comment]
Die Formel gilt nur für den Stickstoff aus dem Bewässerungswasser. Da brauchen wir keine Dichte. Lediglich die Menge in mm (=l/m2) und eine Nitratkonzentration in mg NO3 / l Bewässerungswasser. Der Rest ergibt sich aus der Formel.

Für alle anderen Düngerarten ist es nur eine Prozentrechnung.

LG
Simon

**Comment by arnold-pichler** [comment]
JA passt, Danke.

**Comment by arnold-pichler** [comment]
Frage: Wird die Bewässerungs-Menge in L oder in mm eingegeben? Die Formel impliziert letzteres?
