### ISSUE TITLE
Berechnung Entzug

### ISSUE THREAD

**Issue by arnold-pichler** [w3geo/bml-fast#72]
@simonkriegnerschramml - ich mach ab jetzt lieber eigene Issues, sonst haben wir alles in #70 zusammenpicken und keiner kennt sich mehr aus.

Frage zum Dokument "Nahrstoffentzuge.N.P.und.K.xlsx" bzw. zu den Stammdaten:

Du hast in dem Excel eine Bindung von Saldierungsart und Erfassungsart:

![image](https://github.com/user-attachments/assets/960ccd5c-28b9-45d2-9282-aa0e724c7714)

D.h. bei Saldierungsart 1 ist die Ertragserfassung immer in t/ha usw. Das ist aber in den Stammdaten nicht so, Beispiel Wintertriticale, da ist die Saldierungsart 1, aber die Erfassungseinheit m³. Und da gibt es mehr Beispiele auch für andere Saldierungsarten.

Was ist da die Regel / Vorgehensweise?

**Comment by simonkriegnerschramml** [comment]
Sorry, das ist ein Fehler meinerseits. 
Aber eine Frage habe dennoch: Also in meinem File steht bei Wintertriticale nichts von Erfassung in m3. Welche Version der Stammdaten verwendest du?

Ich stelle dir das aktuelle File in das Issue sobald ich Zugang zu meinem privaten PC habe. Ich kann mit der Office in der Arbeit leider das gewünschte Format nicht ohne Formatierungsfehler erzeugen. Ich mache das am Nachmittag.

Die Regel besagt, dass die Saldierungsart nicht unmittelbar etwas mit der Ertragserfassungsart zu tun hat. Saldierungsart sagt, wie der Entzugswert bestimmt wird (für Stickstoff). Die Ertragserfassungsart sagt lediglich etwas über die Einheit aus, in welcher der Ertrag erfasst werden muss. Saldierungsart 1 bedeutet, dass es einen Entzugswert je Tonne Erntegut gibt. Saldierungsart 2 bedeutet, dass es einen Entzug je m3 gibt. Saldierungsart 3 bedeutet, dass die Düngeobergrenze der erreichten Ertragslage als Entzug je Hektar schlagend wird. Das kann aber sowohl mit Ertragserfassungsart t oder m3 der Fall sein, bzw. auch mit der Auswahl einer erreichten Ertragslage. Saldierungsart 4 und 5 bedeuten, dass ein Entzug je Tonne aus den zutreffenden Kreuztabellen ausgelesen werden muss, die Erfassung des Ertrages findet in Tonnen statt.

Saldierungsart = Vorgehensweise der Bestimmung des Stickstoffentzuges (nicht aber für Phosphor und Kalium)
Ertragserfassungsart = Einheit in der der Ertrag erfasst werden muss (auch für Phosphor und Kalium und bei Saldierungsart 3 und 7 auch für Stickstoff von Relevanz)

LG
Simon

LG
Simon

**Comment by arnold-pichler** [comment]
> Welche Version der Stammdaten verwendest du?

Die letzte, die ich bekommen habe, 22.08.24 - https://github.com/w3geo/bml-fast/issues/17#issuecomment-2302372081

**Comment by arnold-pichler** [comment]
Nachdem ich für die Berechnung die Ertragslage brauche und die mithilfe der Spalte "EL XXX t / m3 ab" berechnet wird, ist es am Ende egal, ob das m³ oder Tonnen sind. War insofern mehr eine Rohdaten-Frage.

**Comment by simonkriegnerschramml** [comment]
> Nachdem ich für die Berechnung die Ertragslage brauche und die mithilfe der Spalte "EL XXX t / m3 ab" berechnet wird, ist es am Ende egal, ob das m³ oder Tonnen sind. War insofern mehr eine Rohdaten-Frage.

Ja das stimmt.

**Comment by simonkriegnerschramml** [comment]
Welche Ertragslage soll ich für Zwischenfrüchte befüllen? Hier ist es ja so, dass nur eine einzige gibt. In einer Spezifikation habe ich auf die EL mittel referenziert. Soll ich alle Daten löschen und nur die mittlere Ertragslage belassen?

LG
Simon

**Comment by arnold-pichler** [comment]
Mir ist es an sich egal welche. Ich denke aber, die mittlere klingt am ehesten logisch.

**Comment by simonkriegnerschramml** [comment]
Hier nun das neu Stammdatenfile. Ich hoffe ich habe alle Anmerkungen korrigiert. Falls nicht bitte melden. Morgen habe ich den ganzen Zugriff auf den Privaten PC zwecks Formatierung.

[2024_09_30_Stammdaten Kulturen.csv](https://github.com/user-attachments/files/17195465/2024_09_30_Stammdaten.Kulturen.csv)

LG
Simon

**Comment by arnold-pichler** [comment]
Danke, bitte immer das Excel auch mitschicken, tu ich mir leichter beim Test-Kulturen suchen.

**Comment by arnold-pichler** [comment]
> Ich hoffe ich habe alle Anmerkungen korrigiert

Die drei "genzen" waren noch drin, ansonsten schaut es gut aus:
- Düngeobergenze EL mittel A5 wird zu Düngeobergrenze EL mittel A5
- Düngeobergenze EL hoch 2 A5 wird zu Düngeobergrenze EL hoch 2 A5
- Düngeobergenze EL hoch 3 A5 wird zu Düngeobergrenze EL hoch 3 A5
