### ISSUE TITLE
Verständnisfrage Mineralstoffanteile / Menge

### ISSUE THREAD

**Issue by arnold-pichler** [w3geo/bml-fast#73]
@simonkriegnerschramml : 

Aktuell sind alle Mineralstoffangaben im Formular (N / P / K) in % einzugeben und auch bei Handelsdüngern.

Sehe ich das jetzt richtig, dass ich für die Berechnung z.B. der "N-Mengen aus Handelsdüngern" den Prozentanteil der eingegebenen Menge nehmen muss.

Also wenn z.B. 100l eines Handelsdüngers mit 5% N eingebe, sind das dann 5L 

Spielen da die Einheiten eine Rolle? Manche Dünger sind ja in L, manche in KG?

**Comment by simonkriegnerschramml** [comment]
Dafür gibt es die Spalte "Dichte". Grundsätzlich gibt es keinen Wert für Liter Stickstoff. Es gibt nur kg Stickstoff. Flüssige Dünger müssen eben in Liter erfasst werden und die Stickstoffkonzentration schließlich mit der Dichte hochgerechnet werden. Um das für euch zu vereinfachen, wurde in einem Meeting vereinbart, dass die Stickstoffkonzentration (auch für P und K) bereits auf Masseprozent umgerechnet wird. Das heißt, dass das Ergebnis für den jeweiligen Nährstoff auf kg Stickstoff, Phosphor oder Kalium lautet, egal welche Einheit bei der Eingabe verlangt wird.

LG
Simon

**Comment by simonkriegnerschramml** [comment]
Also immer Masse und kein Volumen als Ergebnis der Nährstoffmenge.

LG
Simon
