### ISSUE TITLE
Kornfeuchte / Proteingehalt

### ISSUE THREAD

**Issue by arnold-pichler** [w3geo/bml-fast#75]
@simonkriegnerschramml : 

Die Tabellen für den Entzug bei Weizen / Braugerste reichen von einer Kornfeuchte von 12 - 16 und einem Proteingehalt von 11-22 (Weizen) bzw. 9-16 (B-Gerste). Abseits dieser Werte kann ich ja keinen Entzug berechnen. Soll ich Eingabewerte außerhalb dieser Grenzen im Formular als Fehler anzeigen?

**Comment by simonkriegnerschramml** [comment]
Nein via DropDown nur diese zulassen.

LG
Simon

**Comment by arnold-pichler** [comment]
Ah, OK, perfekt! Danke.
