### ISSUE TITLE
NEUE Stammdaten Files

### ISSUE THREAD

**Issue by simonkriegnerschramml** [w3geo/bml-fast#8]
Ich werde heute die Stammdaten in einer völlig überarbeiteten Form auf die Next Cloud stellen. Ich bin im Zuge der ersten Sortierlisten darauf gekommen, die Stammdaten für die Vorfrüchte nicht separat zu listen. Wir benötigen also nur ein einziges Stammdatenfile für alle Kulturen. Die Spezifikation werde ich dahingehend noch umschreiben, falls das erforderlich sein sollte. Derzeit bezieht sich die Beschreibung auf ein gesondertes Stammdatenfile. Bitte um Rückmeldung, ob ich das in der Spezifikation (.doc File) noch ändern soll.

LG
Simon

**Comment by arnold-pichler** [comment]
Nein, ich denke das wird nicht nötig sein. Ich denke, es werden sich dann ohnehin noch Fragen während der Umsetzung ergeben.
