### ISSUE TITLE
Verständnisfrage zur Vorfruchtwerten & Co

### ISSUE THREAD

**Issue by arnold-pichler** [w3geo/bml-fast#80]
@simonkriegnerschramml - noch einmal eine grundsätzliche Frage, ob ich das auch richtig kapiert habe. Ich habe versucht, das aus all den Word-Dokumenten "zusammenzukratzen", aber es ist primär immer die Berechnung der Faktoren beschrieben, aber kaum oder nur implizit die Ausgabe bzw. wie die Ergebnisse angezeigt werden soll. Deshalb meine "Idee" wie der Outcome sein soll, bitte um Korrektur:

- Ausgangslage: Ich habe eine Kulturfolge, beginnend bei Vorfrucht , Zwischenfrucht, Hauptfrüchten, jeweils mit Düngungen wenn vorhanden
- Aus den Düngungen errechnet sich N-Düngung, P-Bilanz, K-Bilanz (bereits implementiert)
- Davon abgezogen werden die errechneten Entzüge (bereits implementiert)
- Jede Kultur hat eine Düngeobergrenze, d.h. Summe alle Obergrenzen ist die Gesamtobergrenze des Schlags.
   - Aber: Was beschreibt diese Düngeobergrenze? Ist das nur N? Oder...??
- Aufgrund von Vorfrüchten / Zwischenfrüchten usw. ergeben sich Abzüge, die je nach Voraussetzung unterschiedlich ermittelt werden (ist in `N-Bilanz.P-Bilanz.K-Bilanz.N-Saldo.Nmin.Vorfruchtwert.xlsx`  , `Vorfruchtwerte.N-Saldo.und.Nmin.Zusammenspiel.xlsx`  beschrieben)
-  Diese Abzüge haben aber keinen Einfluss auf die Bilanz, wie sie aus den Düngungen berechnet werden, sondern ..? Auf die Düngeobergrenze?

- Was wird letztendlich dem User ausgegeben: Eine Düngebilanz, oder? D.h. die Summe der Obergrenzen - die Summe alle Bilanzen + Abzüge? Da wären dann aber die P/K-Bilanzen ohne Sinn? Es gibt ja keine eigenen Obergrenzen für N/P/K ?`

Ggf. telefonieren wir da noch einmal, damit ich das ganz verstehe. LG

**Comment by simonkriegnerschramml** [comment]
Also hier, muss grundsätzlich zwischen den beiden Begriffen Bilanz und Obergrenze unterschieden werden.

Bilanz:
Das ist die Differenz aus der Nährstoffmenge, welche der Fläche zuzurechnen ist und dem Entzug durch das Erntegut. Diese Bilanz muss es für jede Kultur aber auch als Summe über alle Kulturen geben. Die angesprochene Nährstoffmenge, welche der Fläche zuzurechnen ist, kann (für Stickstoff) aus den Düngemaßnahmen (inkl. Bewässerung), aus dem N-Saldo oder dem Vorfruchtwer oder bei Gemüse aus dem Nmin gemessen stammen.  Diese Nährstoffe stehen der Kultur zur Verfügung und müssen in die Bilanz aufgenommen werden.
Für Phosphor und Kalium hingegen sind nur Düngemaßnahmen relevant.
 
Düngeobergrenze:
Das ist die gesetzliche Grenze bis zu welcher gedüngt werden darf. Diese existiert vorrangig für Stickstoff und Phosphor. Jedoch kann Phosphor nur gesamtbetrieblich geprüft werden, weshalb auf Ebene des Einzelschlages keine Relevanz für uns hat. Diese Grenze wird durch N-Saldo, Vorfruchtwert, Nmin etc. reduziert. Es bleibt weniger an aktiver Düngemöglichkeit übrig. Das hat aber nichts mit der Nährstoffbilanz an sich zu tun. Wird die Düngeobergrenze zu einer Kultur überschritten, so stellt das einen Verstoß dar.

Ich formuliere ein Beispiel, damit das besser nachvollzogen werden kann.

LG
Simon

**Comment by arnold-pichler** [comment]
OK, dann habe ich es grundsätzlich schon kapiert gehabt. D.h. dass die Düngeobergrenze in unserem Tool ausschließlich für Stickstoff angegeben ist. D.h. auch eine Berechnung einer Überschreitung kann dann nur dafür passieren? Aber ja, bitte - ein Beispiel ist immer gut!

**Comment by simonkriegnerschramml** [comment]
Ob wir für Phosphor einen Hinweis bei Überschreitung ausgeben, ist eine Entscheidung, die seitens BML beantwortet werden muss.

Hier ein Beispiel:

Fläche befindet sich im Nitratrisikogebiet (Feuchtgebiet)
Kultur: Körnermais
Vorfrucht: Ackerbohne (20 kg Vorfruchtwert)
Zwischenfrucht: ungenutzte Zwischenfrucht >60% Leguminosen: 20 kg Vorfruchtwert
N-Saldo aus der Ackerbohne: 0 kg
Basiswert für die Düngeobergrenze der unterstellten Ertragslage hoch 1: 160 kg N / ha

resultierende Düngeobergrenze für Körnermais: 160 - 20 - 20 = 120 kg N / ha
120 kg dürfen noch gedüngt werden - Das ist die resultierende Düngeobergrenze.

Bilanz:
Der Landwirt düngt eine Stickstoffmenge von 110 kg.
Gesamt sind der Fläche dann 110 + 20 kg (VFW Ackerbohne) + 20 kg (VFW Zwischenfrucht) = 150 kg N / ha anzurechnen.
Erntemenge: 9 Tonnen / ha
Das entspricht einem Ertrag in Ertragslage "mittel"
Für die Ertragslage "mittel" ist ein Entzugswert von 12,5 kg N / t Erntegut hinterlegt.
Entzug mit dem Erntegut: 9 * 12,5 = 112,5 kg N / ha
Berechnung der Bilanz: 150 - 112,5 = 37,5 kg N/ ha
Das ist aber keine Überschreitung, sondern nur ein Bilanzergebnis. Für alle, die am "Vorbeugenden Grundwasserschutz - Acker" teilnehmen bedeutet dieser Umstand, dass dieser Bilanzüberschuss (weil ja >20 kg) in Form des N-Saldo (Multiplikation mit dem Reduktionsfaktor 0,6 bzw. 0,8) der Düngeobergrenze der Folgekultur in Abzug gebracht werden muss. Gleichzeitig ist dieser N-Saldo der Folgekultur als Nährstoffmenge anzurechnen.

Folgende Angaben sind nur theoretischer Natur, da das in der Praxis so nicht vorkommen wird. Es soll nur die Berechnungslogik veranschaulicht werden.
Folgefrucht im selben Wirtschaftsjahr: Gerste
Ertragslage: hoch 1
Basiswert der Düngeobergrenze: 135 kg N / ha
resultierende Düngeobergrenze nach Abzug des N-Saldo: 135 - (37,5 * 0,6) =112,5 kg N / ha
Der N-Saldo ist aber gleichzeitig der Fläche als vorhandener Nährstoff anzurechnen. Das sind dann 22,5 kg (=37,5 *0,6). Diese Menge ist wiederum Teil der Bilanz der Gerste, welcher dann gemeinsam mit der Nährstoffmenge aus den Düngemaßnahmen die anzurechnende Nährstoffmenge bildet (zur Erklärung: aus dem Körnermais stammt kein Vorfruchtwert, weshalb hier ausschließlich der N-Saldo vorliegt).

Ich hoffe, dass ich damit alle Klarheiten beseitigen konnte.

LG
Simon

**Comment by arnold-pichler** [comment]
> Ich hoffe, dass ich damit alle Klarheiten beseitigen konnte.

😀 Naja... ich probier es halt mal 😉
