### ISSUE TITLE
Vorfrucht -> Hauptfrucht, Unklarheiten im Excel

### ISSUE THREAD

**Issue by arnold-pichler** [w3geo/bml-fast#82]
@simonkriegnerschramml : Im Excel `N-Bilanz.P-Bilanz.K-Bilanz.N-Saldo.Nmin.Vorfruchtwert` im Sheet `N_Vorfrucht auf HF 1` steht oben, dass die Kriterien auf Basis der VORFRUCHT gelistet sind. Da gibt es die Spalte "Nmin manuell vergeben" - das kann ich an sich ja nur ermitteln, indem ich den Wert aus der Tabelle mit dem Wert im Formular vergleiche. ABER: So wie das in der Tabelle ist, ist damit die HAUPTFRUCHT gemeint, nicht die VORFRUCHT. Denn sonst wären solche Kombis gar nicht möglich:

![image](https://github.com/user-attachments/assets/48cbbbf9-4c3d-4dd1-82db-8e29469c319c)
![image](https://github.com/user-attachments/assets/4c2ff711-fac2-4bbe-87c7-de15e3569972)

Sprich:  Wenn die Vorfrucht ein Gemüse ist, ist die manuelle NMin-Eingabe IMMER möglich, bzw. wenn sie KEIN Gemüse ist, ist sie immer NICHT Möglich.

Da passt was nicht.

**Comment by arnold-pichler** [comment]
Ich sehe, du hast es im Excel `Vorfruchtwerte.N-Saldo.und.Nmin.Zusammenspiel.xlsx` nochmal etwas anders beschrieben, mal sehen, ob ich es darum besser ablesen kann.

**Comment by simonkriegnerschramml** [comment]
Hallo Arnold,

Das stimmt schon so. Nmin Eingabemöglichkeit nur zur Aussaat von Gemüsekulturen. Anrechnung des Nmin berechnet, also hier in den Vorfruchtwerten der Stammdaten bereits enthalten, gilt auch für nicht Gemüsekulturen. Nmin Eingabe hat mit der Vorkultur nichts zu tun, sondern ist ausschließlich von der aktuell angebauten Kultur abhängig. Ist diese ein Gemüse, dann Nmin Eingabe möglich, sonst nicht.

Das mag aus fachlicher Sicht nicht ganz konsistent klingen, was anderes gibt aber die gesetzeslage nicht her.

LG
Simon


Disclaimer und Datenschutz der Landwirtschaftskammer Oberösterreich
Diese Nachricht ist vertraulich. Im Falle einer Fehlleitung, verständigen Sie bitte den Absender und löschen Sie diese Nachricht und alle Anhänge. Sollten Sie nicht der beabsichtigte Adressat sein, ist jede Offenlegung, Weiterleitung oder sonstige Verwendung dieser Information nicht gestattet. Soweit gesetzlich zulässig, schließt der Absender jede Haftung für Schäden aus Übertragungsfehlern, Viren, fremden Einfluss, Verzögerungen und dergleichen aus. Nähere Informationen zum Datenschutz finden Sie unter:  www.ooe.lko.at/datenschutz<http://www.ooe.lko.at/datenschutz>
Am 04.10.2024 11:43 schrieb Arnold Pichler ***@***.***>:

@simonkriegnerschramml<https://github.com/simonkriegnerschramml> : Im Excel N-Bilanz.P-Bilanz.K-Bilanz.N-Saldo.Nmin.Vorfruchtwert im Sheet N_Vorfrucht auf HF 1 steht oben, dass die Kriterien auf Basis der VORFRUCHT gelistet sind. Da gibt es die Spalte "Nmin manuell vergeben" - das kann ich an sich ja nur ermitteln, indem ich den Wert aus der Tabelle mit dem Wert im Formular vergleiche. ABER: So wie das in der Tabelle ist, ist damit die HAUPTFRUCHT gemeint, nicht die VORFRUCHT. Denn sonst wären solche Kombis gar nicht möglich:

image.png (view on web)<https://github.com/user-attachments/assets/48cbbbf9-4c3d-4dd1-82db-8e29469c319c>
image.png (view on web)<https://github.com/user-attachments/assets/4c2ff711-fac2-4bbe-87c7-de15e3569972>

Sprich: Wenn die Vorfrucht ein Gemüse ist, ist die manuelle NMin-Eingabe IMMER möglich, bzw. wenn sie KEIN Gemüse ist, ist sie immer NICHT Möglich.

Da passt was nicht.

**Comment by simonkriegnerschramml** [comment]
Jetzt habe ich deine Frage verstanden. Es geht ja hier gar nicht um die Vorfrucht, sondern um die Eingabe der Hauptkultur und welchen Einfluss die Vorkult hat.

LG
Simon


Disclaimer und Datenschutz der Landwirtschaftskammer Oberösterreich
Diese Nachricht ist vertraulich. Im Falle einer Fehlleitung, verständigen Sie bitte den Absender und löschen Sie diese Nachricht und alle Anhänge. Sollten Sie nicht der beabsichtigte Adressat sein, ist jede Offenlegung, Weiterleitung oder sonstige Verwendung dieser Information nicht gestattet. Soweit gesetzlich zulässig, schließt der Absender jede Haftung für Schäden aus Übertragungsfehlern, Viren, fremden Einfluss, Verzögerungen und dergleichen aus. Nähere Informationen zum Datenschutz finden Sie unter:  www.ooe.lko.at/datenschutz<http://www.ooe.lko.at/datenschutz>
Am 04.10.2024 11:43 schrieb Arnold Pichler ***@***.***>:

@simonkriegnerschramml<https://github.com/simonkriegnerschramml> : Im Excel N-Bilanz.P-Bilanz.K-Bilanz.N-Saldo.Nmin.Vorfruchtwert im Sheet N_Vorfrucht auf HF 1 steht oben, dass die Kriterien auf Basis der VORFRUCHT gelistet sind. Da gibt es die Spalte "Nmin manuell vergeben" - das kann ich an sich ja nur ermitteln, indem ich den Wert aus der Tabelle mit dem Wert im Formular vergleiche. ABER: So wie das in der Tabelle ist, ist damit die HAUPTFRUCHT gemeint, nicht die VORFRUCHT. Denn sonst wären solche Kombis gar nicht möglich:

image.png (view on web)<https://github.com/user-attachments/assets/48cbbbf9-4c3d-4dd1-82db-8e29469c319c>
image.png (view on web)<https://github.com/user-attachments/assets/4c2ff711-fac2-4bbe-87c7-de15e3569972>

Sprich: Wenn die Vorfrucht ein Gemüse ist, ist die manuelle NMin-Eingabe IMMER möglich, bzw. wenn sie KEIN Gemüse ist, ist sie immer NICHT Möglich.

Da passt was nicht.

**Comment by arnold-pichler** [comment]
Jein, es ging mir vor allem darum, ob die Systematik im Excel falsch ist oder ob das nur Copy & Paste Fehler sind. Die grundsätzliche Problematik habe ich verstanden. Aber ich halte mich jetzt an `Vorfruchtwerte.N-Saldo.und.Nmin.Zusammenspiel.xlsx` , da ist es nochmal drin, aber etwas anders systematisiert. Ist aber am Ende das gleiche und bisher sehe ich dort keine Fehler (bzw. irgendwas, das ich nicht verstehe).

**Comment by simonkriegnerschramml** [comment]
> Jein, es ging mir vor allem darum, ob die Systematik im Excel falsch ist oder ob das nur Copy & Paste Fehler sind. Die grundsätzliche Problematik habe ich verstanden. Aber ich halte mich jetzt an `Vorfruchtwerte.N-Saldo.und.Nmin.Zusammenspiel.xlsx` , da ist es nochmal drin, aber etwas anders systematisiert. Ist aber am Ende das gleiche und bisher sehe ich dort keine Fehler (bzw. irgendwas, das ich nicht verstehe).

Ich verstehe den Einwand nicht ganz. Die Systematik ist nicht falsch. Nmin gibt es ausschließlich vor Gemüsekulturen. Wenn es, wie im gekennzeichneten Fall nicht möglich ist diesen Wert zu erfassen, dann ist das, wie angeführt, "nicht möglich".  Ich kann nicht mit einem nicht vorhandenen Wert rechnen. Das erwähnte Excel ist notwendig, um den Einfluss auf die Berechnung durch die Vorfrucht zu beschreiben. Es beschreibt keine Eingabeerfordernis, sondern einfach die relevanten Berechnungsparameter im Fall A-Z. Und es ist notwendig Werte aus den Stammdaten mit eventuell vom User eingetragenen Werten abzugleichen, um zu entscheiden welcher Fall der strengere ist und damit umzusetzen ist.

LG
Simon

**Comment by arnold-pichler** [comment]
Ich verwende jetzt ohnehin das andere Excel. Ich denke, das einzige Problem ist die Überschrift "Kriterien auf Basis der Vorfrucht" - dann würde sich "Nmin Eingabe nicht möglich" mit "Vorfrucht = Gemüse" widersprechen, aber hier ist wohl die NMin der Hauptfrucht gemeint. In der anderen Excel ist das dann besser ablesbar. Also alles gut erstmal.

**Comment by simonkriegnerschramml** [comment]
Nochmal. Es geht hier nicht um das Eingabeprozedere. Es geht um den Ablauf unserer Berechnungen. Die Eingabeprozerede und Abhängigkeiten wurden in einem anderen Excel beschrieben (=Systematik Excel + Excel hier in Anlage). Warum soll sich das widersprechen? Nmin Eingabe ist nur "vor" einer Gemüsekultur möglich, nicht nach einer Gemüsekultur. Daher geht es nur um den Nmin Eintrag, der bei der Hauptfrucht eingetragen wurde, einen anderen kann es gar nicht geben.

[Vorfruchtwerte und Nmin Gemüse.xlsx](https://github.com/user-attachments/files/17275082/Vorfruchtwerte.und.Nmin.Gemuse.xlsx)

LG
Simon

**Comment by arnold-pichler** [comment]
> Nochmal. Es geht hier nicht um das Eingabeprozedere. 

Jaja, das ist schon klar.

> Daher geht es nur um den Nmin Eintrag, der bei der Hauptfrucht eingetragen wurde, einen anderen kann es gar nicht geben.

Nein, wenn bei der Vorfrucht ein Gemüse ausgewählt wird, gibt es auch dort einen NMin Wert, der händisch verändert werden kann!

**Comment by arnold-pichler** [comment]
@simonkriegnerschramml  - Eine Frage allerdings: Wie entscheide ich, ob der NMin Wert Manuell vergeben wurde? Ich kann eigentlich nur den eingegebenen Wert vergleichen mit "VFW | Nmin selbes Jahr" der Kultur? Denn der wird ja als Default gesetzt, kann aber geändert werden.

**Comment by simonkriegnerschramml** [comment]
> > Nochmal. Es geht hier nicht um das Eingabeprozedere.
> 
> Jaja, das ist schon klar.
> 
> > Daher geht es nur um den Nmin Eintrag, der bei der Hauptfrucht eingetragen wurde, einen anderen kann es gar nicht geben.
> 
> Nein, wenn bei der Vorfrucht ein Gemüse ausgewählt wird, gibt es auch dort einen NMin Wert, der händisch verändert werden kann!

Nein es gibt keinen manuellen Nmin aus der Vorfrucht. Es gibt entweder einen berechneten (vorgegebenen Wert) auf Basis der Vorfrucht oder einen eingetragenen Wert zur Aussaat der Hauptfrucht, der den berechneten ablösen kann.

Es gibt aber keinen manuellen den ich bei der Vorfrucht eingetragen werden könnte.

LG
Simon

**Comment by simonkriegnerschramml** [comment]
> @simonkriegnerschramml - Eine Frage allerdings: Wie entscheide ich, ob der NMin Wert Manuell vergeben wurde? Ich kann eigentlich nur den eingegebenen Wert vergleichen mit "VFW | Nmin selbes Jahr" der Kultur? Denn der wird ja als Default gesetzt, kann aber geändert werden.

Dann muss die Zelle leer bleiben und man schreibt den Deafult Wert irgendwo daneben. Ich verstehe das Problem schon. Dass eigentlich eine einzige Zelle für zwei Zwecke genutzt werden soll, das geht nicht wirklich gut.

LG
Simon

**Comment by arnold-pichler** [comment]
Zum NMin der Vorfrucht: Aktuell gibt es den im Formular. Ich habe jetzt nochmal nachgeschaut und ich denke, ich verstehe, woher der kommt - https://github.com/w3geo/bml-fast/issues/41#issue-2474843980

Das habe ich so aufgefasst, dass der auch für die Vorfrucht existieren muss, wenn es eine Gemüsekultur gibt. D.h. den kann ich wieder rausgeben?

Und nochmal zu "manuell" :

> Dann muss die Zelle leer bleiben und man schreibt den Deafult Wert irgendwo daneben. Ich verstehe das Problem schon. Dass eigentlich eine einzige Zelle für zwei Zwecke genutzt werden soll, das geht nicht wirklich gut.

Das gefällt mir nicht sehr, ich sehe kein Problem damit, per Default den Wert aus der Tabelle reinzuschreiben, den aber editierbar zu machen. Wie gesagt, ich brauche dann ja nur vergleichen und weiß, ob der Wert geändert wurde, sprich eine manuelle Eingabe darstellt.

**Comment by simonkriegnerschramml** [comment]
Ich fasse zusammen:

Wenn eine Gemüse als Hauptkultur angebaut wird, dann muss der Düngeobergrenze dieser Gemüsekultur ein sogenannter Nmin - Wert in Abzug gebracht werden.

Vorrangig soll dieser Wert durch eine Messung unmittelbar vor dem Anbau der Gemüsekultur festgestellt werden = manuelle Eingabe
Wenn dieser Wert nicht vorhanden sein soll, dann muss dieser aus der Summe des Mindestvorrates und der Stickstoffnachlieferung der Vorkultur berechnet werden.

Eine Berechnung ist für uns nicht notwendig, da die relevanten Werte bereits in den Stammdaten als Summe ausgewiesen wurde. Da dieser Wert aber als Vorfruchtwert und nicht als Nmin bezeichnet wird (sich aber an einigen Stellen unterschiedlich zu nicht Gemüsekulturen verhält) kann es zu Verwirrungen kommen. 

Auf alle Fälle schlägt ein gemessener Nmin immer den berechneten Nmin aus Gemüsevorkulturen. Ein gemessener Nmin schlägt aber nie einen Vorfruchtwert von Nicht Gemüsekulturen. Dieser bliebt immer erhalten und muss zum Messergebnis addiert werden. Wird hingegen kein manueller Wert eingetragen, so existiert in diesen Fällen (=Vorfrucht ist Nicht-Gemüsekultur) bestenfalls ein Vorfruchtwert aus der Nicht-Gemüsekultur.

ACHTUNG: Es gibt aber neue Regelungen/ Interpretation/ Rechtsauslegung hinsichtlich der Unterbrechung von Gemüsefruchtfolgen, die hier noch nicht berücksichtigt werden konnten. Hier gibt es leider immer noch offene Fragen und Ungereimtheiten, die noch mit dem BML (Sektion 1 und 2) zu klären sind.

LG
Simon

**Comment by simonkriegnerschramml** [comment]
> Zum NMin der Vorfrucht: Aktuell gibt es den im Formular. Ich habe jetzt nochmal nachgeschaut und ich denke, ich verstehe, woher der kommt - [#41 (comment)](https://github.com/w3geo/bml-fast/issues/41#issue-2474843980)
> 
> Das habe ich so aufgefasst, dass der auch für die Vorfrucht existieren muss, wenn es eine Gemüsekultur gibt. D.h. den kann ich wieder rausgeben?

JA, der muss weg. Bei der Vorfrucht muss nur die Auswahl der Kultur stattfinden. mehr nicht.

> 
> Und nochmal zu "manuell" :
> 
> > Dann muss die Zelle leer bleiben und man schreibt den Deafult Wert irgendwo daneben. Ich verstehe das Problem schon. Dass eigentlich eine einzige Zelle für zwei Zwecke genutzt werden soll, das geht nicht wirklich gut.
> 
> Das gefällt mir nicht sehr, ich sehe kein Problem damit, per Default den Wert aus der Tabelle reinzuschreiben, den aber editierbar zu machen. Wie gesagt, ich brauche dann ja nur vergleichen und weiß, ob der Wert geändert wurde, sprich eine manuelle Eingabe darstellt.

? Wie kann man dann den Default Wert wieder herstellen, wenn man diesen überschrieben hat und man dies unbeabsichtigt getan haben sollte?

**Comment by arnold-pichler** [comment]
> ? Wie kann man dann den Default Wert wieder herstellen, wenn man diesen überschrieben hat und man dies unbeabsichtigt getan haben sollte?

Stimmt. Guter Punkt. Werde ich mir was überlegen.

**Comment by simonkriegnerschramml** [comment]
Ich habe nun neue Überlegungen bezüglich dem Berechnungsprozedere des N-Saldo und des Vorfruchtwertes angestellt. Ich möchte mich dahingehend aber zumindest telefonisch noch mit dir abstimmen. hättest du heute einmal kurzfristig Zeit?

Telefonnummer: 05069021563

LG
Simon

**Comment by simonkriegnerschramml** [comment]
Hallo Arnold,

Anbei die überarbeitete Systematik. Das sollte so passen. Die in hellem Orange gehaltenen Zeilen sind NEU bzw. wurden diese geändert. Die Zeile in dunklem Orange, ist jene, die noch mit einem Fragezeichen versehen ist.

[N-Bilanz, P-Bilanz, K-Bilanz, N-Saldo, Nmin, Vorfruchtwert - Update nach Rüme Neudorfer zu ZWF.xlsx](https://github.com/user-attachments/files/17307438/N-Bilanz.P-Bilanz.K-Bilanz.N-Saldo.Nmin.Vorfruchtwert.-.Update.nach.Rume.Neudorfer.zu.ZWF.xlsx)


LG
Simon

**Comment by simonkriegnerschramml** [comment]
> Hallo Arnold,
> 
> Anbei die überarbeitete Systematik. Das sollte so passen. Die in hellem Orange gehaltenen Zeilen sind NEU bzw. wurden diese geändert. Die Zeile in dunklem Orange, ist jene, die noch mit einem Fragezeichen versehen ist.
> 
> [N-Bilanz, P-Bilanz, K-Bilanz, N-Saldo, Nmin, Vorfruchtwert - Update nach Rüme Neudorfer zu ZWF.xlsx](https://github.com/user-attachments/files/17307438/N-Bilanz.P-Bilanz.K-Bilanz.N-Saldo.Nmin.Vorfruchtwert.-.Update.nach.Rume.Neudorfer.zu.ZWF.xlsx)
> 
> LG Simon

So, jetzt haben wir wieder eine unschlüssige Situation. Ich habe seitens BML Sektion II eine doch eher verwirrende Interpretation bekommen. Die neuen Umsetzungen, die ich eingebaut habe, müssen wieder umgeschrieben werden. ich muss mir aber selber mal ein neuen Bild von dieser Situation machen. Tut mir leid, das ist jetzt schon etwas frustrierend. Für dich, aber auch für mich.

LG
Simon

**Comment by arnold-pichler** [comment]
@simonkriegnerschramml - noch eine Verständnisfrage:
 
Im Excel gibt es ja verschiedene Sheets zu N-Saldo und Vorfruchtwert:
![image](https://github.com/user-attachments/assets/071ca210-5d14-4df3-b144-aa005cd61941)

Also z.B:
- N_Vorfrucht auf HF 1
- N_Vorfrucht - gen.ZWF - N-Saldo
- N_gen.ZWF auf HF1

In JEDEM dieser Sheets gibt es eine Spalte "Vorfruchtwert der Vorfrucht basierend auf BAS15" - das ist aber immer derselbe Fall, d.h. die Sheets beinhalten eigentlich tw. die selben Fälle, oder? Sie unterscheiden sich nur dadurch, auf was der N-Saldo anzurechnen ist, oder? Zumindest habe ich es so aus dem Vergleich einiger Fälle so verstanden.

**Comment by arnold-pichler** [comment]
> Die neuen Umsetzungen, die ich eingebaut habe, müssen wieder umgeschrieben werden

Da geht es jetzt nur um die neuen Fälle? Also die hell und dunkel orange hinterlegten?

**Comment by simonkriegnerschramml** [comment]
> > Die neuen Umsetzungen, die ich eingebaut habe, müssen wieder umgeschrieben werden
> 
> Da geht es jetzt nur um die neuen Fälle? Also die hell und dunkel orange hinterlegten?

Ich denke "JA". Ich muss das aber nochmals durchdenken. Ich würde sagen, dass der ursprüngliche Zustand der Systematik wieder seine Gültigkeit erlangen wird müssen. Die Interpretation, die ich jetzt erhalten haben, ist doch eher fraglich, ob diese so umgesetzt werden darf und rechtlichen Halt bietet.

Ich melde mich dann heute Nachmittag.

LG
Simon

**Comment by simonkriegnerschramml** [comment]
> > @simonkriegnerschramml - noch eine Verständnisfrage:
> > Im Excel gibt es ja verschiedene Sheets zu N-Saldo und Vorfruchtwert: ![image](https://private-user-images.githubusercontent.com/36012148/376533661-071ca210-5d14-4df3-b144-aa005cd61941.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5ODMxMjQsIm5iZiI6MTcyODk4MjgyNCwicGF0aCI6Ii8zNjAxMjE0OC8zNzY1MzM2NjEtMDcxY2EyMTAtNWQxNC00ZGYzLWIxNDQtYWEwMDVjZDYxOTQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDA5MDAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjYzJkMjQ5OTdjMjJiN2JmMzU2NjRmNWIwZWQwZmU2ZWM3MTNjMzliMjY2YWQ4MzQ1NzI2MmRlNmZkNWIyMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.26ZhG2NVyLLb9pu3E1yr_yzRMjww0Nb9avzXciL3LHU)
> > Also z.B:
> > 
> > * N_Vorfrucht auf HF 1
> > * N_Vorfrucht - gen.ZWF - N-Saldo
> > * N_gen.ZWF auf HF1
> > 
> > In JEDEM dieser Sheets gibt es eine Spalte "Vorfruchtwert der Vorfrucht basierend auf BAS15" - das ist aber immer derselbe Fall, d.h. die Sheets beinhalten eigentlich tw. die selben Fälle, oder? Sie unterscheiden sich nur dadurch, auf was der N-Saldo anzurechnen ist, oder? Zumindest habe ich es so aus dem Vergleich einiger Fälle so verstanden.
> 
> Es sind alle Fälle beschrieben, die zustande kommen können. Es gibt natürlich Konstellationen, die zum selben Ergebnis führen. Es ist aber wichtig die Referenz abzubilden. Es ist beispielsweise beschrieben, was im Programm angezeigt werden muss wenn ich die Düngeobergrenze der genutzten Zwischenfrucht darstellen muss, aber auch was bei der darauf folgenden Hauptfrucht angezeigt werden muss.
> 
> Daher ist die Vorfrucht und der ggf. anzurechnende Vorfruchtwert an mehreren Stellen von Relevanz.
> 
> Bitte auch nicht den N-Saldo mit dem Vorfruchtwert verwechseln. Das sind grundsätzlich unterschiedliche Dinge und diese sind auch unterschiedlich zu handhaben.
> 
> Falls du mich anrufen möchtest, um das zu klären bin ich heute bis 11:45 und dann wieder ab ca. 15:00 Uhr erreichbar.
> 
> Tel.: 05069021563
> 
> LG Simon

Wir stellen den alten Stand wieder her. Diese Systematik entspricht der strengeren Auslegung und sollte daher Beratungsspielraum zulassen. Die Frage, die sich noch stellt, ist die Ausgabe der Düngeobergrenze von ungenutzten Zwischenfrüchten. Bisher habe ich kein Sheet mit der Berechnung der Düngeobergrenze der ungenutzten Zwischenfrucht in den Systematiken enthalten. Das würden wir aber jetzt dennoch benötigen. Eine Bilanzierung brauchen wir aber dennoch nicht für die ungenutzte Zwischenfrucht.

Ich füge das noch ein und stelle dann die Datei hier rein.

LG
Simon

**Comment by arnold-pichler** [comment]
> Ich füge das noch ein und stelle dann die Datei hier rein. 

Bis wann wird das ca. der Fall sein? Kann ich einstweilen einfach mit der Vorgänger-Version arbeiten?

**Comment by simonkriegnerschramml** [comment]
> > Ich füge das noch ein und stelle dann die Datei hier rein.
> 
> Bis wann wird das ca. der Fall sein? Kann ich einstweilen einfach mit der Vorgänger-Version arbeiten?

Ich bin mir aufgrund der jüngsten Ausführen noch unsicher, was denn nun zur Berechnung der Düngeobergrenze der ungenutzten Zwischenfrucht benötigt wird. Ich kann das nicht ergänzen ohne sicher zu gehen es korrekt umzusetzen. Daher bitte mit der Vorgängerversion arbeiten. Die Düngeobergrenze ungenutzter Zwischenfrüchte muss dann noch ergänzt werden. Ich bin aber dabei das nun final ausfindig zu machen.

LG
Simon

**Comment by simonkriegnerschramml** [comment]
Wie weit kann ich die Testungen fortführen? gibt es schon neue Updates zu testen?

LG
Simon

**Comment by arnold-pichler** [comment]
Bekomme ich noch eine neue Version des Excel? Oder bleibt es jetzt fix bei der Vorgänger-Version? Bin aktuell so "mittendrin", melde mich, wenn ich einen Update eingespielt habe.

**Comment by simonkriegnerschramml** [comment]
> Bekomme ich noch eine neue Version des Excel? Oder bleibt es jetzt fix bei der Vorgänger-Version? Bin aktuell so "mittendrin", melde mich, wenn ich einen Update eingespielt habe.

Wir werden eine Berechnung zur Düngeobergrenze der ungenutzten Zwischenfrucht brauchen. So viel ist schon mal fix. Wie genau diese aussehen wird, dazu brauche ich aber noch die Bestätigung seitens BML Sektion I (Wasserwirtschaft) und Sektion II (Landwirtschaft). Ich bemühe mich aber ständig um neue Info diesbezüglich. Einen Alleingang kann und will ich nicht machen. Ich muss diese Funktion also nachschießen.

Sorry

LG
Simon

**Comment by arnold-pichler** [comment]
Ja, nicht schlimm. Dann mach ich mal mit dem Rest nach dem Vorgänger-Sheet weiter. War die Woche etwas im Stress, kann sein, dass ich erst am WE so richtig zum Arbeiten komme (das WE ist des Selbständigen ruhigste Arbeitszeit :-) )

**Comment by simonkriegnerschramml** [comment]
Also es wird nun vorläufig nichts neues kommen. Die Düngeobergrenze für Zwischenfrüchte schreibe ich gerade noch dazu und dann sollte das abgeschlossen sein. Ich gebe aber keine Gewähr, dass das Prozedere in Zukunft noch geändert werden wird können. Das liegt aber nicht in unseren Händen.

LG
Simon
