### ISSUE TITLE
Suchfunktion in den Drop Down Feldern erst nach Löschen des vorhandenen Eintrages möglich

### ISSUE THREAD

**Issue by simonkriegnerschramml** [w3geo/bml-fast#85]
Hallo Arnold,

Ich habe im Zuge der Testungen festgestellt, dass vor eingetragene Werte wie "bitte wählen" zuerst manuell aus der Zelle gelöscht werden müssen, bevor die Suche in den entsprechenden Drop Downs funktioniert. Löscht man den Inhalt vorher nicht, so schreibt man einfach am vor eingetragenen Wert weiter.

Bsp.: Ich möchte einen Handelsdünger auswählen und öffne das Drop Down Menü. Dort steht nach dem Öffnen der Eintrag "bitte wählen". Fange ich nun einfach zu tippen an, dann schreibe ich einfach beim Ausdruck "bitte wählen" hinten dran. Ich muss also vorher "bitte wählen" manuell löschen, um nach meinem gewünschten Eintrag zu suchen.

Das ist auch bei den Kulturen etc. so.

Ist es möglich hier die Suchfunktion anders zu gestalten?

LG
Simon

**Comment by arnold-pichler** [comment]
Ja, ist es. Ursprünglich war das ein Drop-Down. Da konnte man gar nicht suchen, nur auswählen, das fand ich etwas unpraktisch. Deshalb habe ich es TESTWEISE einmal durch Auto-Complete-Felder ergänzt, das ist, was du aktuell siehst. Damit kann man durch Tippen die Auswahl einschränken. Aber ja, das Ändern gestaltet sich als unschön - ich habe da schon eine Idee, das werde ich noch ergänzen.

**Comment by arnold-pichler** [comment]
Im Update durch eine meines Achtens ganz gute Lösung ersetzt. Das mit der auto-sortierten Reihenfolge der Favoriten (Vorschlag von Ludwig) können wir zusätzlich noch umsetzen! Siehe https://github.com/w3geo/bml-fast/issues/66#issuecomment-2434524979
