### ISSUE TITLE
Düngeobergrenze und Bilanz wird erst nach Eintrag der Erntemenge ausgegeben

### ISSUE THREAD

**Issue by simonkriegnerschramml** [w3geo/bml-fast#86]
Hallo Arnold,

Grundsätzlich ist es für den User während der Eingabe einer Düngung von Interesse die zugrundeliegende Düngeobergrenze zu sehen. Bis Dato wird die Bilanz und damit auch der Parameter "Düngeobergrenze" erst nach Buchung der Ernte ausgegeben.

LG
Simon

**Comment by arnold-pichler** [comment]
OK, verstehe, d.h. du meinst, sobald eine bestimmte Kultur ausgewählt ist, sollte deren Düngeobergrenze laut Tabelle sichtbar sein,  die Abzüge werden dann erst berechnet, sobald genug Angaben dafür da sind?

**Comment by simonkriegnerschramml** [comment]
Genau. Die Düngeobergrenze ist dynamisch und ändert sich mit den Angaben.


Disclaimer und Datenschutz der Landwirtschaftskammer Oberösterreich
Diese Nachricht ist vertraulich. Im Falle einer Fehlleitung, verständigen Sie bitte den Absender und löschen Sie diese Nachricht und alle Anhänge. Sollten Sie nicht der beabsichtigte Adressat sein, ist jede Offenlegung, Weiterleitung oder sonstige Verwendung dieser Information nicht gestattet. Soweit gesetzlich zulässig, schließt der Absender jede Haftung für Schäden aus Übertragungsfehlern, Viren, fremden Einfluss, Verzögerungen und dergleichen aus. Nähere Informationen zum Datenschutz finden Sie unter:  www.ooe.lko.at/datenschutz<http://www.ooe.lko.at/datenschutz>
Am 11.10.2024 15:59 schrieb Arnold Pichler ***@***.***>:

OK, verstehe, d.h. du meinst, sobald eine bestimmte Kultur ausgewählt ist, sollte deren Düngeobergrenze laut Tabelle sichtbar sein, die Abzüge werden dann erst berechnet, sobald genug Angaben dafür da sind?
