### ISSUE TITLE
Stickstoffdüngung zu ungenutzter Zwischenfrucht wird nicht zur Düngung der folgenden Hauptkultur gerechnet

### ISSUE THREAD

**Issue by simonkriegnerschramml** [w3geo/bml-fast#87]
Hallo Arnold,

Folgende Konstellation:
BAS05: JA (Nitratrisikogebiet)
BAS08: JA
BAS09: JA (Teilnahme am vorbeugenden Grundwasserschutz-Acker)
N-Saldo (BAS16): 20 kg
Zwischenfrucht: ungenutzt 1-60% Leg.
Hauptfrucht: Körnermais EL hoch 1

Düngung zur Zwischenfrucht: 15 Kubikmeter Schweinegülle á 2,5 kg Njw (2 kg P und 2 kg K)
- resultierende Düngung: 37,5 kg Njw, 30 kg P2O5 und 30 kg K2O

Düngung zu Körnermais:
- 300 kg / ha Harnstoff 46:0:0 - das sind 138 kg Njw

In der Bilanz wird zum anrechenbaren Stickstoff nur der Stickstoff aus der Harnstoffdüngung gerechnet. Es fehlen folgende Komponenten:
1.) Stickstoff aus dem N-Saldo (der übrigens aufgrund der Zwischenfrucht korrekt durch eine weitere Multiplikation mit dem Reduktionsfaktor berechnet wurde) = 12 kg
2.) Stickstoff aus der Düngung der ungenutzten Zwischenfrucht = 37,5 kg

damit sind für den anrechenbaren Stickstoff zur Kultur Körnermais gesamt 187,5 kg (12+37,5+138) zu rechnen und nicht 138 kg.

LG
Simon

**Comment by simonkriegnerschramml** [comment]
Selbiges gilt auch für Phosphor und Kalium.

ungenutzte Zwischenfrucht: sämtliche Düngung muss auf die Folgekultur gerechnet werden
genutzte Zwischenfrucht: Düngung wird zur Zwischenfrucht gerechnet

LG
Simon

**Comment by arnold-pichler** [comment]
Diese Teile sind noch nicht umgesetzt bitte! Aber danke erstmal für den Hinweis!

**Comment by arnold-pichler** [comment]
Sollte jetzt alles passen.

**Comment by simonkriegnerschramml** [comment]
Leider wird die gedüngte Menge zu ungenutzten ZWF noch nicht zur HF 1 gerechnet.

Ich habe 15 kg N auf die ZWF gebucht und an den Zahlen der HF 1 hat sich nichts verändert.

LG
Simon

**Comment by simonkriegnerschramml** [comment]
SCHLAG-DATEN:
{
  "fnar_code": "A",
  "inspire_id": "https://data.inspire.gv.at/0095/bbd8ee1b-76a1-451f-88ef-84e9c7a1faaf/elu.ExistingLandUseObject/114901036/MFA-2024",
  "sl_flaeche_brutto_ha": 8.02910667,
  "snar_bezeichnung": "KÖRNERMAIS",
  "layer": "invekos_schlaege_polygon",
  "loading": false,
  "id": 1395009,
  "extent": [
    14.246310107409967,
    48.111657792504985,
    14.250819236040117,
    48.11464083140021
  ],
  "parts": [
    {
      "type": "Polygon",
      "coordinates": [
        [
          [
            14.249482154846204,
            48.114476753092134
          ],
          [
            14.249482154846204,
            48.112080209933225
          ],
          [
            14.248840101063264,
            48.11200275580521
          ],
          [
            14.248123280704032,
            48.11191075089448
          ],
          [
            14.247504360973847,
            48.11182255138502
          ],
          [
            14.247074872255336,
            48.11175987143858
          ],
          [
            14.246520660817634,
            48.111657792504985
          ],
          [
            14.246405325829993,
            48.1116757011045
          ],
          [
            14.246332570910468,
            48.11173659029615
          ],
          [
            14.246310107409967,
            48.11188836524653
          ],
          [
            14.24631513655187,
            48.11197634078687
          ],
          [
            14.246344305574908,
            48.1120070090696
          ],
          [
            14.246323518455041,
            48.1120273799626
          ],
          [
            14.246321506798278,
            48.112080881500304
          ],
          [
            14.246341288089766,
            48.11219527163044
          ],
          [
            14.246372468769561,
            48.11237323619946
          ],
          [
            14.24641437828542,
            48.11268260207129
          ],
          [
            14.24642946571113,
            48.11278020191645
          ],
          [
            14.246438518166554,
            48.112840865946964
          ],
          [
            14.24644991755487,
            48.11291361791865
          ],
          [
            14.246471710503114,
            48.11304457120809
          ],
          [
            14.246471039950858,
            48.11304457120809
          ],
          [
            14.246512949466718,
            48.11330356673116
          ],
          [
            14.24656726419927,
            48.113625462545315
          ],
          [
            14.246615208685412,
            48.113895199835326
          ],
          [
            14.249482154846204,
            48.114476753092134
          ]
        ]
      ]
    },
    {
      "type": "Polygon",
      "coordinates": [
        [
          [
            14.250291176140312,
            48.11464083140021
          ],
          [
            14.250301234424118,
            48.114586437148745
          ],
          [
            14.250305928289894,
            48.11456964878792
          ],
          [
            14.250307939946653,
            48.11456382882156
          ],
          [
            14.250417910516266,
            48.114277754277396
          ],
          [
            14.250428304076197,
            48.114249997351095
          ],
          [
            14.250429980456834,
            48.11424619196487
          ],
          [
            14.25061605870724,
            48.11381416687294
          ],
          [
            14.250623434782034,
            48.11380185522384
          ],
          [
            14.250697195529941,
            48.113625462545315
          ],
          [
            14.25071764737368,
            48.11356547098873
          ],
          [
            14.25071865320206,
            48.11356211325031
          ],
          [
            14.250726699829107,
            48.11353793752701
          ],
          [
            14.250754192471506,
            48.11345779939995
          ],
          [
            14.250754863023763,
            48.11345556090302
          ],
          [
            14.250771962106231,
            48.11340519469556
          ],
          [
            14.250773973762993,
            48.11339377834835
          ],
          [
            14.25077430903912,
            48.11339221139855
          ],
          [
            14.250774644315248,
            48.113389972898716
          ],
          [
            14.250808171927934,
            48.11321425035854
          ],
          [
            14.250809848308569,
            48.113165674722296
          ],
          [
            14.250819236040117,
            48.112885412551094
          ],
          [
            14.25081387162209,
            48.11286571355501
          ],
          [
            14.250813536345964,
            48.112863922736835
          ],
          [
            14.250793419778349,
            48.112788708316174
          ],
          [
            14.250772967934614,
            48.11275826435272
          ],
          [
            14.250622764229776,
            48.11253597810227
          ],
          [
            14.25055537372828,
            48.11244934664455
          ],
          [
            14.250455796718603,
            48.11232130194864
          ],
          [
            14.250432327389722,
            48.11229712564159
          ],
          [
            14.250354208052164,
            48.112210717636344
          ],
          [
            14.249675273895269,
            48.11210349091999
          ],
          [
            14.249053001403812,
            48.1120284992422
          ],
          [
            14.249053001403812,
            48.11438967721517
          ],
          [
            14.250291176140312,
            48.11464083140021
          ]
        ]
      ]
    }
  ]
}
{
  "nitrataktionsprogramm": 0,
  "bdfl_l16_grundwasserschutz_acker": 0,
  "bdfl_l26_wasserrahmenrichtlinie_ertragslagen-el_hoch_3": 0,
  "bdfl_l26_wasserrahmenrichtlinie_ertragslagen-el_hoch_2": 0,
  "bdfl_l26_wasserrahmenrichtlinie_ertragslagen-el_hoch_1": 0,
  "bdfl_l26_wasserrahmenrichtlinie_ertragslagen-el_mittel": 0,
  "bdfl_l26_wasserrahmenrichtlinie_ertragslagen-el_mittel_10": 0,
  "bdfl_l26_wasserrahmenrichtlinie_ertragslagen-el_niedrig": 0,
  "schwere_boeden": 0
}

**Comment by arnold-pichler** [comment]
Die Schlagdaten sind mir eigentlich egal - die sehe ich ja dann eh. Bitte den Fall exportieren und mir den Export schicken, siehe Testsystematik (#63)

**Comment by simonkriegnerschramml** [comment]
[fast-export-2024-10-25.txt](https://github.com/user-attachments/files/17517710/fast-export-2024-10-25.txt)

**Comment by simonkriegnerschramml** [comment]
passt das so? Da kann ich aber immer nur alle Einträge auf einmal exportieren. Ich schreibe dann die Feldstücksbezeichnung dazu damit man sich auskennt.

**Comment by simonkriegnerschramml** [comment]
Ich mache das Issue wieder auf. Die grundsätzliche Berechnung muss ja so funktionieren. Also die Düngung, welche auf eine ungenutzte Zwischenfrucht gebucht wird, muss in die Düngung der HF 1 einfließen. Und zwar für alle Nährstoffe. Also für N, P und K.

LG
Simon

**Comment by arnold-pichler** [comment]
> Also die Düngung, welche auf eine ungenutzte Zwischenfrucht gebucht wird, muss in die Düngung der HF 1 einfließen. Und zwar für alle Nährstoffe. Also für N, P und K

OK? Das wusste ich nicht bzw. habe ich das aus den Excel offenbar nicht korrekt entnommen. Wird natürlich gleich nachgebaut.

**Comment by arnold-pichler** [comment]
> passt das so? Da kann ich aber immer nur alle Einträge auf einmal exportieren. Ich schreibe dann die Feldstücksbezeichnung dazu damit man sich auskennt.

Ja, bitte dem entsprechenden Feldstück einen Namen geben, damit ich mich auskenne. Eventuell einfach die Issue-Nummer? Also z.B "Issue 87" oder sowas ? Aber egal, ich muss es nur irgendwo rauslesen können.

**Comment by simonkriegnerschramml** [comment]
> > Also die Düngung, welche auf eine ungenutzte Zwischenfrucht gebucht wird, muss in die Düngung der HF 1 einfließen. Und zwar für alle Nährstoffe. Also für N, P und K
> 
> OK? Das wusste ich nicht bzw. habe ich das aus den Excel offenbar nicht korrekt entnommen. Wird natürlich gleich nachgebaut.

Das konnte in keinem Excel enthalten sein. Weil hier keine Düngemaßnahmen beschrieben sind. Das war im Word docx.

LG
Simon

**Comment by simonkriegnerschramml** [comment]
> > passt das so? Da kann ich aber immer nur alle Einträge auf einmal exportieren. Ich schreibe dann die Feldstücksbezeichnung dazu damit man sich auskennt.
> 
> Ja, bitte dem entsprechenden Feldstück einen Namen geben, damit ich mich auskenne. Eventuell einfach die Issue-Nummer? Also z.B "Issue 87" oder sowas ? Aber egal, ich muss es nur irgendwo rauslesen können.

Ja, die Systematik werde ich ich dahingehend anpassen.

**Comment by arnold-pichler** [comment]
> Ich mache das Issue wieder auf. Die grundsätzliche Berechnung muss ja so funktionieren. Also die Düngung, welche auf eine ungenutzte Zwischenfrucht gebucht wird, muss in die Düngung der HF 1 einfließen. Und zwar für alle Nährstoffe. Also für N, P und K.

Im Grunde wird es bei der Zwischenfrucht ausgewiesen, allerdings nicht von der Düngeobergrenze der Zwischenfrucht abgezogen (damit wäre es auch bei der Gesamt-DüngeOG abgezogen):

![image](https://github.com/user-attachments/assets/8779ca97-dd65-41d7-9dcd-e41a8e70e4e7)

 Wäre es so nicht logischer? Also die ZF als Beginn des Fruchtfolgeglieds zu betrachten? Denn wenn ich es bei der HF1 abziehe, muss ich für die ZF entweder gar keine Bilanz (und auch keine DüngeOG?? ausgeben) oder auf 0 setzen, weil sonst ja die Summe nicht stimmt?

BtW: Teil der Ausgabe soll vermutlich auch eine N/P/K-Summe sein? Das fehlt aktuell ja noch.

**Comment by simonkriegnerschramml** [comment]
> > Ich mache das Issue wieder auf. Die grundsätzliche Berechnung muss ja so funktionieren. Also die Düngung, welche auf eine ungenutzte Zwischenfrucht gebucht wird, muss in die Düngung der HF 1 einfließen. Und zwar für alle Nährstoffe. Also für N, P und K.
> 
> Im Grunde wird es bei der Zwischenfrucht ausgewiesen, allerdings nicht von der Düngeobergrenze der Zwischenfrucht abgezogen (damit wäre es auch bei der Gesamt-DüngeOG abgezogen):
> 
> ![image](https://private-user-images.githubusercontent.com/36012148/381091296-8779ca97-dd65-41d7-9dcd-e41a8e70e4e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMTM4MjMsIm5iZiI6MTczMDIxMzUyMywicGF0aCI6Ii8zNjAxMjE0OC8zODEwOTEyOTYtODc3OWNhOTctZGQ2NS00MWQ3LTlkY2QtZTQxYThlNzBlNGU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDE0NTIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhNjEyZDY1MGM4OGViM2MxNWI3NDFmYTQzNWY4NmExZDI5MmE0MmI3NzgwNGJmODVhNGUyMzAyNTU5YWY0ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.X_0fyYHM5GW0fR7QnnjQnxnoOH2bfDIhDuAqAdtp0do)
> 
> Wäre es so nicht logischer? Also die ZF als Beginn des Fruchtfolgeglieds zu betrachten? Denn wenn ich es bei der HF1 anrechne, muss ich für die ZF entweder gar keine Bilanz (und auch keine DüngeOG?? ausgeben) oder auf 0 setzen, weil sonst ja die Summe nicht stimmt?
> 
> BtW: Teil der Ausgabe soll vermutlich auch eine N/P/K-Summe sein? Das fehlt aktuell ja noch.

Gem. NAPV (Stickstoffdüngeverordnung) muss die Düngung, welche auf eine ungenutzte Zwischenfrucht erfolgt zu100% der Folgefrucht zugerechnet werden.
Eine ungenutzte Zwischenfrucht soll auch nicht bilanziert werden, da diese keinen Entzug aufweist. Sie besitzt jedoch einen Düngebedarf - damit ist klargestellt, dass die ZWF im Herbst gedüngt werden darf. Jedoch beeinflusst diese Obergrenze in keiner Weise die Bilanz auf der Fläche. Die Düngung muss also beachtet werde, nicht jedoch die Düngeobergrenze.
Daher wäre mein Vorschlag lediglich eine Aussaat Zwischenfrucht zu  buchen aber sonst nichts. also nur im Falle einer ungenutzten Zwischenfrucht. für genutzte Zwischenfrüchte brauchen wir hingegen das volle Programm.

LG
Simon

**Comment by arnold-pichler** [comment]
OK. Muss hier allerdings noch einmal ganz sicher gehen - ich habe den Ausdruck "Bilanz" etwas schlampig verwendet. Ich meine damit die "Parameter-Aufstellung", sprich das da:

![image](https://github.com/user-attachments/assets/a5c32c11-3c72-4995-9ede-1432e27c70a2)

Deshalb nochmal meine Fragen:
- Soll das für die UNGENUTZTE ZF komplett weggelassen werden?
- Wenn die Düngung der ungenutzten ZF der Hauptfrucht angerechnet wird, dann beinflußt sie ja auch die Düngeobergrenze der HF, weil ich muss die Düngung der ZF dann ja der Düngung der HF zurechnen und damit fließt sie in die Abzüge ein?

**Comment by simonkriegnerschramml** [comment]
> OK. Muss hier allerdings noch einmal ganz sicher gehen - ich habe den Ausdruck "Bilanz" etwas schlampig verwendet. Ich meine damit die "Parameter-Aufstellung", sprich das da:
> 
> ![image](https://private-user-images.githubusercontent.com/36012148/381423531-a5c32c11-3c72-4995-9ede-1432e27c70a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNzUwNjAsIm5iZiI6MTczMDI3NDc2MCwicGF0aCI6Ii8zNjAxMjE0OC8zODE0MjM1MzEtYTVjMzJjMTEtM2M3Mi00OTk1LTllZGUtMTQzMmUyN2M3MGEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDA3NTI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1MTQxZmI0MmJkODBiZjA0YzRlZTNmMzA3YTk0NjQ3OGE5YjY4NWNiNGM0ZmU0NzVmMzBiZDVjYjM5NTNiOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.g-i29DMT-XRKfKiuZbwSLSQrzl2MoY2Dg06Cv-2Sjn8)
> 
> Deshalb nochmal meine Fragen:
> 
> * Soll das für die UNGENUTZTE ZF komplett weggelassen werden?
> * Wenn die Düngung der ungenutzten ZF der Hauptfrucht angerechnet wird, dann beinflußt sie ja auch die Düngeobergrenze der HF, weil ich muss die Düngung der ZF dann ja der Düngung der HF zurechnen und damit fließt sie in die Abzüge ein?

Hallo Arnold,

Die Entscheidung, dass die Information einer Düngeobergrenze für Zwischenfrüchte möglicherweise von Interesse sein wird, kann und will ich nicht den Auftraggebern vorwegnehmen.
Aus meiner Sicht machen wir uns das Leben bedeutend einfacher, wenn wir die ZWF nicht bilanzieren und auch nicht düngen. Dadurch würde sich auch die zweite Frage erübrigen. Auf alle Fälle ist eine aktive Düngung hinsichtlich der Nährstoffwerte für N, P und K zu 100% zum anrechenbaren Nährstoff (N, P und K) der HF 1 zu rechnen.

Eine Bilanz brauchen wir für die ungenutzte ZWF dennoch. Wir müssen ja irgendwo den Vorfruchtwert der Vorfrucht abbilden, da ja auch aus der ZWF ein solcher stammen kann und im blödesten Fall aus Vorfrucht und ZWF ein Vorfruchtwert auf die HF1 gerechnet werden muss. Ansonsten können wir nur mehr die Summe aus beiden Werten bei der Bilanz der HF1 anzeigen. Aus Gründen der Nachvollziehbarkeit würde ich diese Angaben abbilden, für die Berechnungen ändert sich dabei aber nichts. 

Und zur Erklärung:
Es verringert sich dadurch nicht die Düngeobergrenze der HF1. Es wird nur eine Düngung darauf gebucht. Es wird ja immer die Düngeobergrenze der Düngung gegenüber gestellt. Die Düngung ist also Teil des anrechenbaren Nährstoffs, jedoch kein Abzug von der Düngeobergrenze. Das ist schließlich nur für die Bilanz von Relevanz.

LG
Simon

**Comment by simonkriegnerschramml** [comment]
> > Es verringert sich dadurch nicht die Düngeobergrenze der HF1
> 
> Ich denke, dass ich noch ein wenig ein Verständnisproblem habe, was den nun von der Düngeobergrenze abzuziehen ist, quasi was das "netto" in meiner Aufstellung ergibt.

Das Netto in deiner Aufstellung ist, so denke ich, die Gegenüberstellung von anzurechnendem Nährstoff und ausgelesener Düngeobergrenze. Aber bitte Nagel mich nicht fest. Ich stelle die Sinnhaftigkeit dieses Netto und Brutto Wertes ohnehin in Frage. Eigentlich sollte die Gesamtbilanz eine Gegenüberstellung aller anzurechnenden Nährstoffmengen aus allen Hauptfrüchten und genutzten Zwischenfrüchten, dem Entzug gegenübergestellt werden. Und deine derartige Gesamtbilanz kann man erst nach Verbuchung einer Erntemaßnahme ausgeben.

LG
Simon

**Comment by simonkriegnerschramml** [comment]
> > Es verringert sich dadurch nicht die Düngeobergrenze der HF1
> 
> Ich denke, dass ich noch ein wenig ein Verständnisproblem habe, was den nun von der Düngeobergrenze abzuziehen ist, quasi was das "netto" in meiner Aufstellung ergibt.

Ja es erhöht den Wert für den anrechenbaren Stickstoff / Phosphor/ Kalium der HF1 und der gesamten Schlagbilanz. Aber es verringert nicht die maximal möglich aktive Düngung auf dem Schlag, da die Düngung auf eine ungenutzte ZWF gleichbedeutend, wie eine Düngung direkt auf die HF1 ist - so als ob ich anstatt der ZWF eigentlich die HF 1 gedüngt hätte. Die Düngung zur ZWF zählt schon so als ob es eine Düngung der HF 1 wäre. Daher die Idee, gar nicht erst eine Düngung auf ungenutzte ZWF zuzulassen.

LG
Simon

**Comment by arnold-pichler** [comment]
>  Ich stelle die Sinnhaftigkeit dieses Netto und Brutto Wertes ohnehin in Frage. Eigentlich sollte die Gesamtbilanz eine Gegenüberstellung aller anzurechnenden Nährstoffmengen aus allen Hauptfrüchten und genutzten Zwischenfrüchten, dem Entzug gegenübergestellt werden. Und deine derartige Gesamtbilanz kann man erst nach Verbuchung einer Erntemaßnahme ausgeben.

Naja - das kommt ja nur von mir. Das ist aktuell
- BRUTTO: die aus der Tabelle gelesene Düngeobergrenze
- NETTO:    Btuttowert - nsaldo - vorfruchtwert - vorfruchtwertzwischenfrucht - nminmanuell

Wobei je nach Situation einige dieser Werte 0 sein können.

Ich habe letztlich noch keine genaue Ausgabe-Spezifikation, also was eigentlich dargestellt werden soll! Das ist alles einstweilen nur auf meinem Mist gewachsen.... (gedüngt, sozusagen).

**Comment by arnold-pichler** [comment]
Siehe neue Version bzw. Anmerkungen dazu.

**Comment by simonkriegnerschramml** [comment]
Der Wert den ich zur Zwischenfrucht dünge, wird noch nicht zur HF 1 gerechnet.

LG
Simon

**Comment by arnold-pichler** [comment]
> Ich werde heute Andi anrufen und Ihn zu einer Abstimmung bewegen, damit wir endlich die notwendigen Entscheidungen parat haben.

Nur zur Info: Der @SchnablAndreas hat mich heute angemailt und ich habe ihn über die offenen Punkte informiert, da kommt jetzt hoffentlich was in Bewegung.

**Comment by arnold-pichler** [comment]
> Der Wert den ich zur Zwischenfrucht dünge, wird noch nicht zur HF 1 gerechnet.

Ich denke, da gibt es ein Missverständnis meinerseits. Ich berechne aktuell den Entzug bzw. die Bilanz für die Zwischenfrucht und das wird angezeigt und fließt in die GESAMTE Berechnung ein (wird aktuell von der "Düngeobergrenze gesamt" abgezogen):

![image](https://github.com/user-attachments/assets/e0e0e0b0-9657-4230-9255-f742f822341f)

Ich bin mir jetzt nicht ganz klar, wie das zur HF 1 gerechnet wird? Und ob das nur bei ungenutzten ZF passieren soll? Das war ja schon mal meine Frage, ob für ungenutzte ZF überhaupt diese Berechnung auftauchen soll?

**Comment by simonkriegnerschramml** [comment]
> > Der Wert den ich zur Zwischenfrucht dünge, wird noch nicht zur HF 1 gerechnet.
> 
> Ich denke, da gibt es ein Missverständnis meinerseits. Ich berechne aktuell den Entzug bzw. die Bilanz für die Zwischenfrucht und das wird angezeigt und fließt in die GESAMTE Berechnung ein (wird aktuell von der "Düngeobergrenze gesamt" abgezogen):
> 
> ![image](https://private-user-images.githubusercontent.com/36012148/385703548-e0e0e0b0-9657-4230-9255-f742f822341f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0OTI4OTAsIm5iZiI6MTczMTQ5MjU5MCwicGF0aCI6Ii8zNjAxMjE0OC8zODU3MDM1NDgtZTBlMGUwYjAtOTY1Ny00MjMwLTkyNTUtZjc0MmY4MjIzNDFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDEwMDk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjYzAwYzZiNWM5ZmNlMjBjZWE1ZDNhNjM2YzFkNTg2NDBmOTE0MWNjYWRlY2M1NmM4Yzk5NTM5ODJlODUxNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7qN9xBjMiOwH9KatRnk49ZLXPY9lfKq0ESP9dz2Utzs)
> 
> Ich bin mir jetzt nicht ganz klar, wie das zur HF 1 gerechnet wird? Und ob das nur bei ungenutzten ZF passieren soll? Das war ja schon mal meine Frage, ob für ungenutzte ZF überhaupt diese Berechnung auftauchen soll?

Das sind sehr schwer zu beantwortende Fragen, wenn es um die Details geht. Grundsätzlich bin ich der Meinung, dass ungenutzte Zwischenfrüchte nicht saldiert und bilanziert werden dürfen. Was aber klar ist und das steht auch als Fußnote in der Nitrat-Aktionsprogramm-Verordnung, ist dass jegliche aktive Düngung zu einer ungenutzten Düngung 
 zu 100% der folgenden Hauptkultur anzurechnen ist.

Also ist die Düngung, die auf eine ungenutzte ZWF gebucht wird auch gleichzeitig eine Düngung zur HF 1. Der anrechenbare N der HF 1 muss um diesen Wert erhöht werden. Das heißt aber auch wiederum, dass für die Gesamtbilanz über alle Kulturen eines Schlages dieser Wert nicht doppelt gerechnet werden darf.

LG
Simon

**Comment by arnold-pichler** [comment]
> Das sind sehr schwer zu beantwortende Fragen, wenn es um die Details geht. Grundsätzlich bin ich der Meinung, dass ungenutzte Zwischenfrüchte nicht saldiert und bilanziert werden dürfen. Was aber klar ist und das steht auch als Fußnote in der Nitrat-Aktionsprogramm-Verordnung, dass jegliche aktive Düngung zu einer ungenutzten Zwischenfrucht zu 100% der folgenden Hauptkultur anzurechnen ist.
> 
> Also ist die Düngung, die auf eine ungenutzte ZWF gebucht wird auch gleichzeitig eine Düngung zur HF 1. Der anrechenbare N der HF 1 muss um diesen Wert erhöht werden. Das heißt aber auch wiederum, dass für die Gesamtbilanz über alle Kulturen eines Schlages dieser Wert nicht doppelt gerechnet werden darf.

OK. Dann werde ich das aber so umsetzen, dass es zunächst einmal für ungenutzte Zwischenfrüchte diese "Parameteraufstellung" nicht gibt und auch die Düngeobergrenze nicht angezeigt wird. Ob man dann überhaupt eine Düngung zulassen soll, müsst ihr bitte noch entscheiden - @SchnablAndreas

**Comment by arnold-pichler** [comment]
@simonkriegnerschramml : Die ungenutzte Zwischenfrucht hat ja auch eine Düngeobergrenze. Was geschieht mit der? Wir die ignoriert? Aktuell kommt sie ja zur gesamten Obergrenze dazu.

**Comment by simonkriegnerschramml** [comment]
> @simonkriegnerschramml : Die ungenutzte Zwischenfrucht hat ja auch eine Düngeobergrenze. Was geschieht mit der? Wir die ignoriert? Aktuell kommt sie ja zur gesamten Obergrenze dazu.

Die ungenutzte Zwischenfrucht hat eine Düngeobergrenze, welche aber nur für die Kultur an sich anzuwenden ist. die Kultur darf gedüngt werden, aber nur in einem abgegrenzten Rahmen. Sie hat einen Bedarf, damit eine Düngung gerechtfertigt ist, jedoch keinen Entzug, da ja keine Abfuhr von Erntegut stattfindet.

Die Düngeobergrenze ist hierbei ausschließlich ein Instrumentarium um die maximal erlaubte Düngehöhe zu Zwischenfrüchten zu regulieren. Diese stellt jedoch bei ungenutzten Zwischenfrüchten keinen Entzug dar.

LG
Simon

**Comment by simonkriegnerschramml** [comment]
> Muss ich sie aber anzeigen? Aktuell habe ich es jetzt so gemacht, dass für die ungenutzte ZF gar nichts angezeigt wird, aber die Düngung zur HF1 kommt.

OK, ja angezeigt sollte diese Grenze schon werden. Es gibt jedoch auch eine Herbstdüngegrenze von 60 kg N ab Lager / ha. irgendwie sollte man das anzeigen, wenn man es schon nicht prüft. Generell ist die Düngung zur ungenutzten ZWF aber suboptimal, weil es dem User suggeriert, dass es hier eine Querprüfung der gesetzlichen Vorgaben gibt. Wenn ich schon eine Düngung buchen kann, dann geht man zumindest davon aus. Bitte lass den Zustand einmal so, wie dieser jetzt ist. Ich habe Andi bezüglich einer Antwort befragt - Er wird das noch besprechen müssen.

LG
Simon

**Comment by arnold-pichler** [comment]
Ich mach jetzt mal die Anrechnung zur HF1, weil das muss ja sowieso sein. Den Rest lass ich dann erstmal drin, ist dann halt nicht konsistent bis zur Entscheidung.

**Comment by arnold-pichler** [comment]
Neue Version deployed:
- Die Düngung der ZF wird zur HF1 angerechnet (in der Ausgabe sind bis zur Entscheidung bzgl. Düngung von ZF diese Werte auch bei der ZF angeführt).

Der Rest nach Entscheidung.

**Comment by simonkriegnerschramml** [comment]
> Neue Version deployed:
> 
> * Die Düngung der ZF wird zur HF1 angerechnet (in der Ausgabe sind bis zur Entscheidung bzgl. Düngung von ZF diese Werte auch bei der ZF angeführt).
> 
> Der Rest nach Entscheidung.

Danke, das ist auch korrekt umgesetzt. Ich schließe das Issue aber vorerst noch nicht, da ja möglicherweise noch Handlungsbedarf besteht.

LG
Simon

**Comment by simonkriegnerschramml** [comment]
Wurde besprochen. Düngung zu ungenutzten Zwischenfrüchten wird in nächster Version weggelassen. Issue wird geschlossen.

LG
Simon

**Comment by arnold-pichler** [comment]
In der aktuellen Version ist die Düngung nur mehr für genutzte ZF möglich!
