### ISSUE TITLE
Bilanz für ungenutzte Zwischenfrüchte nicht notwendig

### ISSUE THREAD

**Issue by simonkriegnerschramml** [w3geo/bml-fast#88]
Hallo Arnold,

Derzeit wird für ungenutzte Zwischenfrüchte eine vollständige Bilanz ausgegeben. Da diese Kulturen aber keinen eigenen Nährstoffbedarf besitzen, brauchen wir hier auch keine Bilanzierung. Lediglich Werte wie Düngeobergrenze, Vorfruchtwert für die Folgekultur und Stickstoffsaldo für die Folgekultur sind hier von Interesse.

LG
Simon

**Comment by arnold-pichler** [comment]
Hier läuft aktuell einfach die selbe Routine über alle Kulturen und rein datentechnisch ist auch die Zwischenfrucht eine Kultur (die "0te"). Deshalb werden hier alle Debugging-Werte ausgegeben. Die tatsächliche Ausgabe muss dann ja erst spezifiziert werden. Die aktuelle ist mal nur für mich zum Programmieren bzw. auch für euch zum Testen.

**Comment by arnold-pichler** [comment]
Aktuell ist sie mal drin für Debugging etc. - was wir endgültig ausgeben und was nicht ist ja noch zu spezifizieren, wenn in den Berechnungen mal alles passt.
