### ISSUE TITLE
Düngung mit Wirtschaftsdüngern - Nährstoffmengen falsch berechnet

### ISSUE THREAD

**Issue by simonkriegnerschramml** [w3geo/bml-fast#89]
Hallo Arnold,

Wenn ich eine Düngung mit Wirtschaftsdüngern buche, dann wird die daraus resultierende Nährstoffmenge falsch berechnet.

Bspw.: Ich dünge mit 15 m3 Schweinegülle, welche je m3 einen Stickstoffgehalt von 2,5 kg Njw aufweist. Es resultieren 15*2,5=37,5 kg Njw. 

Derzeit werden im Programm 0,38 kg Njw ausgegeben. Ich denke also gerundete 0,375 kg.
Es ist also ein Fehler um eine Zehnerpotenz. Bitte die Einheiten nochmal checken.

LG
Simon

**Comment by simonkriegnerschramml** [comment]
Ah sich sehe gerade, dass wir hier die Einheit "%" stehen haben. Das sollte nicht so sein. Wir brauchen bei Sekundärrohstoffen und Wirtschaftsdüngern unbedingt die Einheit je "m3 | t" oder man entscheidet sich auf nur m3 oder nur Tonnen.

Es muss also die Konzentration in Nährstoffmenge in kg je m3 oder Nährstoffmenge in kg je Tonne angeführt und dann auch so berechnet werden.

Vorschlag:
Wirtschaftsdünger: immer m3
Sekundärrohstoffe: immer Tonnen

LG
Simon

**Comment by arnold-pichler** [comment]
OK, Danke. Kann sein, dass ich da in den Specs was übersehen habe oder es fehlte dort, ändere ich dann gleich. D.h. die "%" sind dann nur für Handelsdünger und Eigener Handelsdünger, korrekt?

**Comment by simonkriegnerschramml** [comment]
Genau


Disclaimer und Datenschutz der Landwirtschaftskammer Oberösterreich
Diese Nachricht ist vertraulich. Im Falle einer Fehlleitung, verständigen Sie bitte den Absender und löschen Sie diese Nachricht und alle Anhänge. Sollten Sie nicht der beabsichtigte Adressat sein, ist jede Offenlegung, Weiterleitung oder sonstige Verwendung dieser Information nicht gestattet. Soweit gesetzlich zulässig, schließt der Absender jede Haftung für Schäden aus Übertragungsfehlern, Viren, fremden Einfluss, Verzögerungen und dergleichen aus. Nähere Informationen zum Datenschutz finden Sie unter:  www.ooe.lko.at/datenschutz<http://www.ooe.lko.at/datenschutz>
Am 11.10.2024 16:03 schrieb Arnold Pichler ***@***.***>:

OK, Danke. Kann sein, dass ich da in den Specs was übersehen habe oder es fehlte dort, ändere ich dann gleich. D.h. die "%" sind dann nur für Handelsdünger und Eigener Handelsdünger, korrekt?

**Comment by arnold-pichler** [comment]
> Wirtschaftsdünger: immer m3
Sekundärrohstoffe: immer Tonnen

Achtung - da haben wir dann aber einen Missmatch - die Menge erheben wir nämlich sowohl bei Wirtschaftsdünger wie auch bei Sekundärrohstoffen immer in m³ ! Soll ich das auf Tonnen ändern?

**Comment by arnold-pichler** [comment]
@simonkriegnerschramml : Noch Fragen dazu - ich habe es mir zwar schon aus div. Docs zusammengesucht, aber zur Sicherheit. In den ganzen Excel Files stehen nämlich keine Einheiten, in den Word Docs schon, aber ganz sicher bin ich mir nicht:
- Die Düngeobergrenze ist in kg / ha angegeben oder?
- Bedeutet auch, ich muss den Wert noch mit der Fläche  multiplizieren?
- Damit ist das auch die Einheit für die ganzen Abzüge / Bilanzen, oder?
- Also mit den obigen Einheiten, Beispiel Sekundärrohstoffe:
  - Düngemenge von 1 Tonne
  - Stickstoffanteil von 10kg / Tonne
  - entspricht als einem Abzug von 10kg oder von 0,01 Tonnen?

**Comment by simonkriegnerschramml** [comment]
> > Wirtschaftsdünger: immer m3
> > Sekundärrohstoffe: immer Tonnen
> 
> Achtung - da haben wir dann aber einen Missmatch - die Menge erheben wir nämlich sowohl bei Wirtschaftsdünger wie auch bei Sekundärrohstoffen immer in m³ ! Soll ich das für Sekundärrohstoffe auf Tonnen ändern?

Wirtschaftsdünger: m3
Sekundärrohstoffe: egal da es keine Rolle spielt. Wir führen in den Programmen meist die Einheit "m3 | t". Aber falls das nicht gehen sollte bitte einfach m3 nehmen.

LG
Simon

**Comment by simonkriegnerschramml** [comment]
> @simonkriegnerschramml : Noch Fragen dazu - ich habe es mir zwar schon aus div. Docs zusammengesucht, aber zur Sicherheit. In den ganzen Excel Files stehen nämlich keine Einheiten, in den Word Docs schon, aber ganz sicher bin ich mir nicht:
> 
> * Die Düngeobergrenze ist in kg / ha angegeben oder?
KORREKT
> * Bedeutet auch, ich muss den Wert noch mit der Fläche  multiplizieren?
NEIN, da je "ha" immer je ha bedeutet und den fixen Bezug von 10.000 m2 aufweist. Die Fläche spielt nur insofern eine Rolle, dass wir gem. VO auf Schlagebene Bilanzieren müssen. Die Fläche spielt erst in der Bilanz eine Rolle, da müssen wir /ha und /Schlag ausgeben.
> * Damit ist das auch die Einheit für die ganzen Abzüge / Bilanzen, oder?
JE ha ist die Einheit für die Abzüge
> * Also mit den obigen Einheiten, Beispiel Sekundärrohstoffe:
>   
>   * Düngemenge von 1 Tonne
>   * Stickstoffanteil von 10kg / Tonne
>   * entspricht als einem Abzug von 10kg oder von 0,01 Tonnen?
Der Abzug bedeutet einfach 10 kg Stickstoff wenn eine Tonne ausgebracht werden sollte. Stickstoff wird für die Bilanz immer in kg gerechnet. Bitte nie Tonnen heranziehen. Die Dimensionen belaufen sich im Maximalfall um 380 kg. Tonnen wären hier nie ganzzahlig.

LG
Simon

**Comment by arnold-pichler** [comment]
Ah, OK, verstehe soweit. Dann mach ich bei den Sekundärrohstoffen "m³|t" als Label, soll ich dann für die 3 Mineralstoffe "kg / m³|t" als Label machen?

**Comment by simonkriegnerschramml** [comment]
> Ah, OK, verstehe soweit. Dann mach ich bei den Sekundärrohstoffen "m³|t" als Label, soll ich dann für die 3 Mineralstoffe "kg / m³|t" als Label machen?

Als Konzentrationsangabe macht das durchaus Sinn. Danke. Der User muss dann eben wissen in welcher Form er das eingibt. Hintergrund ist, dass der User bei Senkundärrohstoffen in manchen fällen Tonnen auf dem Lieferschein stehen hat und in den meisten Fällen eben m3.

LG
Simon

**Comment by arnold-pichler** [comment]
Ist in der aktuellen Version wie oben besprochen implementiert.
