### ISSUE TITLE
Frage bzgl. N-Saldo bzw. Bilanzüberschuss der genutzten Zwischenfrucht

### ISSUE THREAD

**Issue by arnold-pichler** [w3geo/bml-fast#91]
@simonkriegnerschramml : 

Sollte das hier
![image](https://github.com/user-attachments/assets/f7b3d739-c946-4038-b8b5-e82088faec31)

und das hier
![image](https://github.com/user-attachments/assets/0078062f-8169-4355-8665-dcbcbe3f83e9)

nicht eigentlich das selbe sein?
Denn was ist sonst die "N-Saldoberechnung für die genutzte Zwischenfrucht" und wofür brauche ich sie?

Excel "N-Bilanz.P-Bilanz.K-Bilanz.N-Saldo.Nmin.Vorfruchtwert.xlsx" , Sheets "N_Vorfrucht - gen.ZWF - N-Saldo" bzw. "N_gen.ZWF auf HF1"

**Comment by simonkriegnerschramml** [comment]
Das eine ist eine Bilanzberechnung und das andere eine Saldoberechnung, bei der auch der Reduktionsfaktor eine Rolle spielt. Sprich im Sheet "N_gen.ZWF auf HF1" steht die Bilanzberechnung der genutzten ZWF.  Der Bilanzüberschuss muss dann nach Multiplikation mit BAS10 der HF1 in Abzug gebracht werden.
Im Sheet "N-Vorfrucht - gen.ZWF - N-Saldo" steht hingegen die gesamte Berechnung des N-Saldo, welcher der HF1 in Abzug gebracht werden soll. Der genutzten ZWF hingegen wird der Wert BAS16 ohne Multiplikation mit BAS10 abgezogen.
Die Erläuterung im Sheet "N-Vorfrucht - gen.ZWF - N-Saldo" brauchst du für die Ausweisung eines N-Saldo nach der genutzten ZWF - also, dem Wert der angezeigt wird, wenn man den anzurechnenden N-Saldo für die HF 1 darstellen möchte.

Also das eine braucht man für den Bilanzüberschuss und das andere für den N-Saldo.

LG
Simon

**Comment by arnold-pichler** [comment]
OK, also hier verstehe ich es dann ja:
![image](https://github.com/user-attachments/assets/ac28d115-d84f-450d-b4d4-16f0126fd3df)

Das bezieht sich auf die HF1 , ist klar.

**Comment by arnold-pichler** [comment]
Aber hier habe ich 2x einen N-Saldo, das hat mich etwas verwirrt. 
![image](https://github.com/user-attachments/assets/51f06ad8-a7c4-4835-b680-1722211eb64b)

Aber sehe ich das jetzt richtig - der "linke" N-Saldo wird der Düngeübergrenze der ZF abgezogen und der rechte der HF1 ?

**Comment by simonkriegnerschramml** [comment]
> Weil der Begriff "Bilanzüberschuss" hier ständig verwendet wird, aber als solches nirgendwo exakt erklärt ist (auch nicht in den ga
Snzen Word-Files) - ich gehe davon aus, dass damit einfach das hier gemeint ist:
> 
> ![image](https://private-user-images.githubusercontent.com/36012148/378384922-4dfe94dc-cd8d-4225-b16f-5f17bde9b79b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MDg5NzgsIm5iZiI6MTcyOTUwODY3OCwicGF0aCI6Ii8zNjAxMjE0OC8zNzgzODQ5MjItNGRmZTk0ZGMtY2Q4ZC00MjI1LWIxNmYtNWYxN2JkZTliNzliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDExMDQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyOWMzYzZjNzUzZGE5ZjBhMWIzZjBjYzRiYTVmZWViOTlmODc5MjlmMzQwM2I0NTE1NTdlYjE2ODI4MmQ3YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.r_xNZQub-kerqAoV5ew9CRzhECNO9HExsknxoFQ8s3E)
> 
> D.h. wenn diese N-Bilanz positiv ist, ist es ein Überschuss??

Ja, genau. Ich nenne das Bilanzüberschuss, weil für den N-Saldo nur Überschüsse zählen. N- Saldo kann nicht negativ sein. Die Bilanz hingegen schon. Sorry ist vl. etwas blöd gewählt.

LG
Simon

**Comment by simonkriegnerschramml** [comment]
> Aber hier habe ich 2x einen N-Saldo, das hat mich etwas verwirrt. ![image](https://private-user-images.githubusercontent.com/36012148/378368617-51f06ad8-a7c4-4835-b680-1722211eb64b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MDg5NzgsIm5iZiI6MTcyOTUwODY3OCwicGF0aCI6Ii8zNjAxMjE0OC8zNzgzNjg2MTctNTFmMDZhZDgtYTdjNC00ODM1LWI2ODAtMTcyMjIxMWViNjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDExMDQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzNmZlNDE1OTQ5MWZkYjhhMTUyOTVjYTM0OWFiNzBkNzA4MWJiMTM4MzdkYWM2NmE3MzlhZGEwMjIyMmI2NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mQstHS-__SP_oGIqbaQKfIirdf9Od1B0aZNgmG8P9bw)
> 
> Aber sehe ich das jetzt richtig - der "linke" N-Saldo wird der Düngeübergrenze der ZF abgezogen und der rechte der HF1 ?


Links steht das was von der Düngeobergrenze der Zwischenfrucht abgezogen werden muss. Rechts steht das was nach der Zwischenfrucht auf die HF1 weitergerechnet wird. Der N-Saldo, der durch die Zwischenfrucht entstehen kann, wird rechnerisch rechts mit der Überschrift "N-Saldoberechnung für die genutzte Zwischenfrucht" dargestellt. Das soll aber nur eine generelle Darstellung sein, was denn für die Saldoberechnung benötigt wird. In diesem Fall würde der N-Saldo nach einer genutzten Zwischenfrucht eben aus aus dem anrechenbaren Stickstoff, bestehend aus BAS16 (=N-Saldo aus der Vorfrucht), dem Vorfruchtwert aus der Vorfrucht und der Düngung, welche auf der Zwischenfrucht erfolgte und dem N-Entzug, in diesem Fall eben die Düngeobergrenze gem. der Stammdaten. Die Darstellung ist für die Ausweisung des N-Saldo nach der Zwischenfrucht, damit dieser auch dort angezeigt werden kann.

Man hätte das anders benennen müssen "N-Saldoberechnung der genutzten Zwischenfrucht" oder "N-Saldoberechnung nach der genutzten Zwischenfrucht".

> Aber sehe ich das jetzt richtig - der "linke" N-Saldo wird der Düngeobergrenze der ZF abgezogen und der rechte der HF1 ?
Ja grundsätzlich schon. Ich habe das aber vom Berechnungsprozedere her anders gegliedert. die Abzuziehenden Parameter sind LINKS und die Berechnungsschritte stehen RECHTS. 

Bitte die Logiken Fruchtfolgeglied für Fruchtfolgeglied denken.  In jedem Sheet ist beschrieben, was denn nun abgezogen werden muss.

LG
Simon

**Comment by simonkriegnerschramml** [comment]
Aber bitte gerne telefonisch nachfragen. 05069021563

**Comment by arnold-pichler** [comment]
> Aber bitte gerne telefonisch nachfragen. 05069021563

JA, müssen wir - morgen (Dienstag) vormittag Zeit? Wann geht es am besten?

**Comment by simonkriegnerschramml** [comment]
Du kannst mich gerne jederzeit anrufen.

05069021563

LG
Simon
