### ISSUE TITLE
Können wir das Bundeland anhand des Schlages erkennen?

### ISSUE THREAD

**Issue by simonkriegnerschramml** [w3geo/bml-fast#92]
Hallo an Alle,

 sind in den Schlagdaten des Agraratlas auch Informationen über das Bundesland enthalten?

LG
Simon

**Comment by arnold-pichler** [comment]
@ahocevar  - Soweit ich sehe, nicht?

**Comment by simonkriegnerschramml** [comment]
OK, Dann muss ich die Hinweismeldung weniger genau gestalten bzw. prüfen. Der Text wird dann etwas länger für alle die am Vorbeugenden Grundwasserschutz Acker teilnehmen.

LG
Simon

**Comment by arnold-pichler** [comment]
Wenn das ganz dringend ist, dann wäre es sich möglich, das BL über eine Verschneidung reinzubringen, aber sich nur mit viel Aufwand. Ich schließe das hier einmal.
