### ISSUE TITLE
Nitratrisikogebiet - irgend eine Relevanz???

### ISSUE THREAD

**Issue by arnold-pichler** [w3geo/bml-fast#93]
@simonkriegnerschramml :
Beim Testen ist mir jetzt eines aufgefallen: Das "Nitratrisikogebiet" hat eigentlich keine Auswirkung? Das ist nirgendwo als Kriterium drin bei den Berechnungen?

Denn ich habe ja immer nur BAS08 und BAS09 als Entscheidungsfaktoren, also Fläche im Grundwasserschutz und Teilnahme am Programm.

**Comment by simonkriegnerschramml** [comment]
Ja natürlich hat das eine Relevanz. Das ist der Basisparameter 05 (BAS05) und dieser gibt über den Basiswert der Düngeobergrenze Bescheid. Also jenen Wert, von dem all dies gelisteten Parameter in Abzug gebracht werden. 

Ich rufe daher folgendes File in Erinnerung.
[Aussaat Hauptfrucht - EL Auswahl - Düngeobergrenzen.xlsx](https://github.com/user-attachments/files/17501824/Aussaat.Hauptfrucht.-.EL.Auswahl.-.Dungeobergrenzen.xlsx)

Um den Ausgangswert der Düngeobergrenze gem. Stammdaten "Kulturen" korrekt auszulesen, ist es notwendig die Flächen anhand der Kriterien Nitratrisikogebiet und WRRL Graz bis Radkersburg (Regionalprogramm Steiermark) zu unterscheiden.

Auch im Bereich der Bestimmung der N-Entzüge (Relevanz für die Bilanzierung und Saldierung) spielt das eine Rolle. Also für alle Kulturen bei denen die Saldierungsart auf kg N/ha oder EL Auswahl lautet.

Folgende einfache Beispiele:

1.) Winterweichweizen < 14% RP in Ertragslage hoch 1:
Düngeobergrenze außerhalb von Nitratrisikogebieten: 170 kg kg Njw/ha
Düngeobergrenze innerhalb von Nitratrisikogebieten: 150 kg Njw/ha

Das ist der Basiswert, von welchem die Abzüge, wie N-Saldo und Vorfruchtwert abgezogen werden.

2.) Kultur Ölkürbis in Ertragslage hoch 1:
Ölkürbis besitzt keinen pro Tonnen Entzug

Düngeobergrenze außerhalb von Nitratrisikogebieten: 105 kg kg Njw/ha
Düngeobergrenze innerhalb von Nitratrisikogebieten: 90 kg Njw/ha

Ertrag Ölkürbis: 500 kg und damit ist die erreichte Ertragslage "niedrig", da diese <0,6 t liegt.
N-Entzug außerhalb von Nitratrisikogebieten: 65 kg Njw/ha
N-Entzug innerhalb von Nitratrisikogebieten: 55 kg Njw/ha

3.) Zwischenfrüchte (egal ob genutzt oder ungenutzt):
Düngeobergrenze außerhalb von Nitratrisikogebieten: 170 kg kg Njw/ha
Düngeobergrenze innerhalb von Nitratrisikogebieten: 150 kg Njw/ha

Düngeobergrenze der Zwischenfrucht ungenutzt ohne Legum. oder Futter-Zwischenfrucht ohne Legum.:
- außerhalb von Nitratrisikogebieten: 80 kg Njw/ha
- innerhalb von Nitratrisikogebieten: 70 kg Njw/ha

Zwischenfrucht ungenutzt (1 - 60% Legum.) oder Futter-Zwischenfrucht (1 - 60% Legum.):
- außerhalb von Nitratrisikogebieten: 40 kg Njw/ha
- innerhalb von Nitratrisikogebieten: 30 kg Njw/ha

Zwischenfrucht ungenutzt (> 60% Legum.) oder Futter-Zwischenfrucht (> 60% Legum.):
- außerhalb von Nitratrisikogebieten: 40 kg Njw/ha
- innerhalb von Nitratrisikogebieten: 30 kg Njw/ha

Bei genutzten ZWF ist das auch gleichzeitig der N-Entzug für die Bilanzierung und Saldierung.

LG
Simon

**Comment by arnold-pichler** [comment]
Ach - dumm, klar - bei der EINGABE ist es relevant. Ich war jetzt so vertieft die ganze Zeit in die Berechnung der N-Abzüge, dass ich das vergessen hatte. Dann passt schon, das ist ja eh schon lange implementiert.
