### ISSUE TITLE
Einheit der eigenen Handelsdünger soll statt m3 auf Kilogramm lauten

### ISSUE THREAD

**Issue by simonkriegnerschramml** [w3geo/bml-fast#97]
Hallo Arnold,

Derzeit wird bei den eigenen Handelsdüngern bei der Eingabe der Menge m3 angezeigt. Bitte hier analog zu Handelsdüngern mit kg arbeiten.

LG
Simon

**Comment by arnold-pichler** [comment]
Das sollte in der neuen Test-Version passen. Bitte testen, und wenn es passt, dieses Issue schließen!

**Comment by simonkriegnerschramml** [comment]
Ist umgesetzt. Issue wird geschlossen
