### ISSUE TITLE
keine Info über Düngeobergrenze, Vorfruchtwert, N-Saldo, Düngemenge usw. zur Kultur wird angezeigt

### ISSUE THREAD

**Issue by simonkriegnerschramml** [w3geo/bml-fast#99]
Hallo Arnold,

Derzeit wird keine Info (Links Unten) über die einzelnen relevanten Parameter angezeigt, solange keine Ernte verbucht ist. Das ist aber der letzte Schritt und man benötigt diese Info während der Eingabe dringend, vor allem für die Düngeobergrenze. Eine Netto und Brutto Düngeobergrenze bring mir da leider nichts, weil da alle Kulturen des Schlages summiert dargestellt werden und eben die einzelne Düngeobergrenze gar nicht dargestellt wird.

Es wird auch keine Düngemenge dargestellt, die aus den gebuchten Düngemaßnahmen stammt. Diese Info braucht jeder User schon bei der Eingabe der Düngung und nicht erst bei der Ernte.

LG
Simon

**Comment by arnold-pichler** [comment]
Verstehe. Ich werde das dahingehend umstellen, dass immer die gesamte Tabelle sichtbar ist und ZUSÄTZLICH die Fehlermeldungen, d.h. dem User ist dann klar, dass das noch nicht vollständig ist. Mal sehen, ob ich das auch noch optisch besser hervorheben kann.

**Comment by arnold-pichler** [comment]
Bitte meine Lösung in der neuen Version begutachten.
